### ISSUE TITLE
Swift support & example?

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#1]
Is it possible to use EarlGrey with Swift? If so, are there any plans for an example repository to demonstrate simple usage?

**Comment by bootstraponline** [comment]
I found one.
https://github.com/google/EarlGrey/tree/master/Demo/EarlGreyExample/EarlGreyExampleSwift

**Comment by tirodkar** [comment]
You can also look at the guide [here](https://github.com/google/EarlGrey/blob/master/docs/install-and-run.md#swift) for more information.

**Comment by bootstraponline** [comment]
Thanks!
