### ISSUE TITLE
Readme Slack and Google Group Updates Needed

### ISSUE THREAD

**Issue by normand1** [google/EarlGrey#1055]
The links for Google Groups and Slack are probably great for those who already have access, but for people like me who have not been invited yet they aren't very useful. Is there someone I can email about getting an invite to one of these groups?

**Comment by khandpur** [comment]
You can post on this thread: https://groups.google.com/forum/#!topic/earlgrey-discuss/RpmBE74oFNk%5B151-175%5D. If you rather not post on a public thread, you can send a pm to either myself or @tirodkar

Also the google group is open to public.

**Comment by normand1** [comment]
I'm not able to view the Google Group from either the link in the readme or from the link you just sent.

<img width="794" alt="Screen Shot 2019-10-15 at 7 34 08 AM" src="https://user-images.githubusercontent.com/1393261/66841272-4c51d700-ef1e-11e9-8845-0d23bb516cd0.png">
