### ISSUE TITLE
My custom  matcher push an error " caught "NSInvalidArgumentException", "-[UIRemoteKeyboardWindow placeholder]: unrecognized selector sent to instance ..."

### ISSUE THREAD

**Issue by huadashao520** [google/EarlGrey#106]
![image](https://cloud.githubusercontent.com/assets/5190054/15696177/a41387b2-27e0-11e6-9497-fc611644c76e.png)

code:
-(id<GREYMatcher>)matcherForTextFieldWithPlaceHolder:(NSString*) placeholder{
    
    MatchesBlock matches = ^BOOL(UITextField *textfield) {
        return [textfield.placeholder isEqualToString:placeholder];
        
    };
    DescribeToBlock describe = ^void(id<GREYDescription> description) {
        
        [description appendText:@"matcherForTextFieldWithPlaceHolder"];
        
    };
    return [[GREYElementMatcherBlock alloc] initWithMatchesBlock:matches
            
                                                descriptionBlock:describe];
}

Thanks for your attention,
How to fix this issue ?

**Comment by tirodkar** [comment]
The error seems to be that the `textfield` does not respond to the placeholder selector. Could you modify your block to be like:
```
MatchesBlock matches = ^BOOL(UITextField *textfield) {
    return [textField respondsToSelector:@selector(placeholder)] && [textfield.placeholder isEqualToString:placeholder];
};
```
