### ISSUE TITLE
AX Exchange error when MFMailComposeViewController has been initialized.

### ISSUE THREAD

**Issue by PikaRules** [google/EarlGrey#108]
**Description**

when EarlGrey tries to open a  viewController where the MFMailComposeViewController has been initialized,  many warning messages start being printed on the console. and earlgrey keeps waiting  forever until the test is marked as failed.

**The warning message is:**

`AX Exchange error: Error Domain=Accessibility Code=0 "Remote service does not respond to _accessibilityMachPort" UserInfo={NSLocalizedDescription=Remote service does not respond to _accessibilityMachPort}`

**observations:**

If you turn off synchronization the test continues until it finish, which marks the test as success. but the warning messages keeps appearing.

**Comment by tirodkar** [comment]
Based on looking around for this error, this looks like a Synchronization problem with the MFMailComposeViewController. Thanks for bringing this to our attention. Is there a simply way by which we could repro this?

**Comment by PikaRules** [comment]
To reproduce it you just need to create an instance of MFMailComposeViewController on some ViewController and add it as a property of that ViewController, create that instance inside viewDidLoad()
the view controller needs to have some view attached to it. 
and this view should have some accessibilityElements turned on with an accessibilityIdentifier settled.

then, create a simple test that opens that viewController

after that, the error posted above should appear in the console log of xcode.

**Comment by tirodkar** [comment]
@PikaRules, was there any update on this from your side? Is it still present?

**Comment by khandpur** [comment]
Fixed by commit: https://github.com/google/EarlGrey/commit/9744dfe35334393c19a01b66610abe754eafc3ab
