### ISSUE TITLE
how go to  other's page to perform UI and action?

### ISSUE THREAD

**Issue by thomas0326** [google/EarlGrey#114]
i want to go to other's page ,because i need to test UI element on other page

**Comment by tirodkar** [comment]
Hey, for clarification - do you mean a different app process or so? EarlGrey currently cannot perform actions in other processes. Could you provide us details of what the "other's page" means?

**Comment by thomas0326** [comment]
I'm sorry. 
only I want to find other interface elements to perform action
I want to know can i find out other element ?

**Comment by tirodkar** [comment]
I see. You can inspect the hierarchy and find other elements by their characteristics like accessibility label, id etc. To do so, put a breakpoint in the test and do:

`[GREYElementHierarchy hierarchyStringForElement:(UIWindow*)[[[UIApplication sharedApplication] delegate]window]];`

Tell us if that works.

**Comment by thomas0326** [comment]
OK，think you

**Comment by thomas0326** [comment]
hello, 
![image](https://cloud.githubusercontent.com/assets/12085333/15772493/fe8d9ede-29a3-11e6-9add-ad9403d28612.png)   why only start no end or path？ 

I need to draw  swiping right  and down path , how do I code?

**Comment by thomas0326** [comment]
I perfom a gesture to unLock  occur a error:
![image](https://cloud.githubusercontent.com/assets/12085333/15772845/27ae3c2c-29a6-11e6-9788-8eb1cb3f3c06.png)

**Comment by tirodkar** [comment]
You can use something similar to the following for performing scrolls - For a right scroll,

```
[[EarlGrey selectElementWithMatcher:grey_accessibilityLabel(@"Label")]
      performAction:grey_scrollInDirection(kGREYDirectionRight, 100)];
[[EarlGrey selectElementWithMatcher:grey_accessibilityLabel(@"Label")]
      performAction:grey_scrollInDirection(kGREYDirectionDown, 100)];
```

In case you are trying to scroll to find a particular element, you can also use [`usingSearchAction:onElementWithMatcher`](https://github.com/google/EarlGrey/blob/346a3ab785b2ce1b58bf008191c60c330202bf9f/EarlGrey/Core/GREYInteraction.h#L150).

**Comment by thomas0326** [comment]
thanks ，and why xStartPoint and yStartPoint can not less than 0.1?   

![image](https://cloud.githubusercontent.com/assets/12085333/15774668/24242620-29b0-11e6-8885-8b7cfd574b1c.png)

**Comment by tirodkar** [comment]
We've kept that as a minimum amount so as to ensure that the scroll always took place at a starting point away from the edge.

**Comment by khandpur** [comment]
Where does it say that it must be >= 0.1? 

[GREYActions.h](
https://github.com/google/EarlGrey/blob/346a3ab785b2ce1b58bf008191c60c330202bf9f/EarlGrey/Action/GREYActions.h#L334)

**Comment by tirodkar** [comment]
It has to be greater than 0 and less than one - [GREYActions.h](https://github.com/google/EarlGrey/blob/346a3ab785b2ce1b58bf008191c60c330202bf9f/EarlGrey/Action/GREYActions.h#L146)

**Comment by tirodkar** [comment]
@thomas0326, is your problem resolved? Feel free to re-open this question if needed.
