### ISSUE TITLE
#import "EarlGrey/EarlGrey.h" not found

### ISSUE THREAD

**Issue by liuhua820522** [google/EarlGrey#117]
I installed the project by manual and with object c project. After I followed the install document and try to do something, the above error occured and I can click the EarlGreay keyword goto the file.
Also @import module will failed.

I created a new project and the .xcodeproj file in under the root dic. But the one which failed the orignal .xcodeproj is under e.g.  source/projectname/   After I set the file path in settings like "$(SRCROOT)/EarlGrey.xcodeproj" the full file path is like ..../source/projectname/...earlGrey.xcodeproj. So maybe this is the issue? How do I drag the xcodeproj to the project and how to set the ring file path here? Thanks.

**Comment by tirodkar** [comment]
Is EarlGrey.framework present in your Build Phases? Are you able to use it with Pods by any chance? What do your Build Phases look like?

**Comment by tirodkar** [comment]
@liuhua820522, was there any update on this?

**Comment by tirodkar** [comment]
Closing due to inaction.
