### ISSUE TITLE
GREYElementFilter No added to EarlGrey Project under AppFramework

### ISSUE THREAD

**Issue by Ad1991** [google/EarlGrey#1175]
I pulled latest changes from EarlGrey2 today and it started failing at build with error:

>Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_GREYElementFilter", referenced from:
      objc-class-ref in GREYElementInteraction.o
ld: symbol(s) not found for architecture x86_64

It seems that `GREYElementFilter` is added as part of commit `5b0a6d40aeb980320e144bbf7df82e45cf245a16` and used in `GREYElementFinder` and `GREYElementInteraction.m` but not added to project file.

**Comment by tirodkar** [comment]
Thanks for pointing this out. Sending a fix in a few minutes.

**Comment by tirodkar** [comment]
Should be fixed in https://github.com/google/EarlGrey/pull/1176

**Comment by Ad1991** [comment]
Thanks for quick response @tirodkar .
