### ISSUE TITLE
Swift conditional example

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#118]
Is this the correct way to handle pointers with Swift?

I think this would be useful as a FAQ entry. It works in my test suite.

```swift
GREYCondition(name: "Wait for collection view to populate", block: { _ in
    let errorOrNil = UnsafeMutablePointer<NSError?>.alloc(1)
    errorOrNil.initialize(nil)

    EarlGrey().selectElementWithMatcher(collectionViewMatcher)
              .assertWithMatcher(grey_notNil(), error: errorOrNil)

    let success = errorOrNil.memory == nil
    errorOrNil.destroy()
    errorOrNil.dealloc(1)

    return success
}).waitWithTimeout(20.0)
```

**Comment by bootstraponline** [comment]
version 2:

```swift
GREYCondition(name: "Wait for collection view to populate", block: {() -> Bool in
    let errorOrNil: UnsafeMutablePointer<NSError?> = UnsafeMutablePointer<NSError?>.alloc(1)
    errorOrNil.initialize(nil)

    EarlGrey().selectElementWithMatcher(collectionViewMatcher).assertWithMatcher(grey_notNil(), error: errorOrNil)

    let success = errorOrNil.memory == nil
    errorOrNil.destroy()
    errorOrNil.dealloc(1)

    return success
}).waitWithTimeout(20.0)
```

**Comment by sid-github** [comment]
You should probably use `AutoreleasingUnsafeMutablePointer` to avoid manually releasing the error pointer.

**Comment by bootstraponline** [comment]
I'd like to but I'm not sure how to do that. I see this error:

> Cannot convert value of type 'AutoreleasingUnsafeMutablePointer<NSError?>' (aka 'AutoreleasingUnsafeMutablePointer<Optional<NSError>>') to expected argument type 'UnsafeMutablePointer<NSError?>' (aka 'UnsafeMutablePointer<Optional<NSError>>')

**Comment by bootstraponline** [comment]
I think I figured it out in https://github.com/google/EarlGrey/pull/122#issuecomment-224308174 The trick is to use `&` with `var error : NSError?`
