### ISSUE TITLE
EarlGrey 2.0: AppFramework won't build

### ISSUE THREAD

**Issue by echamberlain** [google/EarlGrey#1180]
AppFramework fails to build on a fresh download with the following error:

`~/Mobile/EarlGrey/UILib/Visibility/GREYVisibilityChecker.m:122:61: Variable 'result' may be uninitialized when used here.
`
There are also a number of warnings like:

`Unknown warning option '-Wsizeof-array-div'; did you mean '-Wsizeof-array-decay'?`

Are those expected?

**Comment by tirodkar** [comment]
Should be fixed in  https://github.com/google/EarlGrey/pull/1181
