### ISSUE TITLE
Can't build EarlGrey2 TestLib

### ISSUE THREAD

**Issue by adamec31** [google/EarlGrey#1254]
Hello,
I followed setup guide for installing EarlGrey 2. The App framework builds ok, but TestLib shows error on this line `#import " IWYU pragma: export` - `Missing terminating '"' character`. When I comment all those imports, and try to build TestLib, XCode throws more semantic issues e.g. `Unknown type name 'GREY_EXTERN'` or `Cannot find protocol declaration for 'GREYInteraction'; did you mean 'UIInteraction'?`. Can you please help me to make it work? Thank you.

**Comment by tirodkar** [comment]
Can you pull the latest now? This is fixed.

https://github.com/google/EarlGrey/blob/earlgrey2/TestLib/EarlGreyImpl/EarlGrey.h

**Comment by adamec31** [comment]
Thank you very much, build succeeded
