### ISSUE TITLE
dyld: could not load inserted library

### ISSUE THREAD

**Issue by adamec31** [google/EarlGrey#1255]
Hello, when I run generated testExample() with Earlgrey2, I get this error `dyld: could not load inserted library '@executable_path/Frameworks/AppFramework.framework/AppFramework' because image not found`. Although I got Copy files in build phases set up correctly and
<img width="727" alt="Snímka obrazovky 2020-04-03 o 9 33 52" src="https://user-images.githubusercontent.com/22500502/78335636-47e1af00-758e-11ea-832a-b58ccef47c07.png">
 I can also see AppFramework.framework in finder:
<img width="577" alt="Snímka obrazovky 2020-04-03 o 9 34 51" src="https://user-images.githubusercontent.com/22500502/78335697-65af1400-758e-11ea-8fe5-e071d80c8468.png"> Any ideas? Thank you.

**Comment by tirodkar** [comment]
Remove the angular brackets *<>* around <SygixNaviNative.app>?

**Comment by adamec31** [comment]
Thank you, trivial mistake..
