### ISSUE TITLE
Accessibility matchers on AX=N elements

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#127]
```xml 
<UILabel:0x7fdafc439980; AX=N; AX.id='description_label'; AX.frame={{15, 309}, {384, 0}}; AX.activationPoint={207, 309}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{0, 0}, {384, 0}}; alpha=1; interaction=N; text=''>
```

One of the applications I'm automating has accessibility ids set correctly, but the elements are always `AX=N`. I have to use non-accessibility matchers to find these elements. Why can't I use accessibility matchers to find non-accessible elements that have accessibility attributes like id and label?

**Comment by tirodkar** [comment]
If you look at accessibilityLabel or so in GREYMatchers, you'll notice that we check if the element is accessible when performing a match. So it doesn't matter if the label is set, the element has to be accessible itself to match.

**Comment by bootstraponline** [comment]
Right, I understand that. What I'm asking about is matching non-accessible elements using their label.

**Comment by bootstraponline** [comment]
It looks like this already works... so closing.

>  expression -- EarlGrey().selectElementWithMatcher(grey_accessibilityID("email_field")).assertWithMatcher(grey_notNil())

```
> |--<UITextField:0x7a08d4e0; AX=N; AX.id='email_field'; AX.frame={{28, 353}, {358, 30}}; AX.activationPoint={207, 368}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{8, 56}, {358, 30}}; alpha=1; text=''>
>
> |  |  |--<UITextField:0x7a08d4e0; AX=N; AX.id='email_field'; AX.frame={{28, 353}, {358, 30}}; AX.activationPoint={207, 368}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{8, 56}, {358, 30}}; alpha=1; text=''>
```

I thought AX=N means we can't use accessibility matchers, but we can.

**Comment by khandpur** [comment]
Accessibility id is for testing purposes so it can be used by elements that aren't actually accessible (isAccessibilityElement = NO). On the other hand, accessibility label and hints, etc aren't They require isAccessibilityElement = YES.
