### ISSUE TITLE
[EarlGrey2] Requesting to add sha256 sum EarlGreyApp Pod Spec(s).

### ISSUE THREAD

**Issue by joolurik** [google/EarlGrey#1272]
Hi,

For all of the HTTP sourced pod specs, we have sha256 checksum verification when importing. The current EarlGreyApp POD spec doesn't have sha256 sum.

Could you amend the EarlGrepApp pod spec to have sha256 checksum?
Here is the pod specs, i am referring
https://github.com/CocoaPods/Specs/blob/5488470e44a7763892472dcf1cda8c319683beb9/Specs/2/2/d/EarlGreyApp/2.0.0-rc/EarlGreyApp.podspec.json
https://github.com/CocoaPods/Specs/blob/7501155f57c914382112df53d75f3b25c19e5321/Specs/2/2/d/EarlGreyApp/2.0.0/EarlGreyApp.podspec.json

Thanks,

**Comment by tirodkar** [comment]
Can you add more details on why this is needed?

**Comment by joolurik** [comment]
My company have replicating cocoa-pod repository and we sync/import from cocoa-pod repository on nightly basis. For importing cocoa-pods, we have checklist where we validate each pod spec before importing. One of the checklist, if the pod source is HTTP, the pod spec contain sha256 checksum for validating downloaded file.

Currently, EarlGreyApp pod spec doesn't contain sha256  checksum so the earlgreyapp pod is not importing into my companies repository.

I have tried amending the EarlGrey Spec but i have learned pod specs not amendable once created. The only possible way is to delete/deprecate and import new pod spec for that i need to have ownership on pod spec.
 
Let me know if you need more information.
