### ISSUE TITLE
Exception: com.google.earlgrey.ElementInteractionErrorDomain

### ISSUE THREAD

**Issue by pavan-appannagari** [google/EarlGrey#1278]
Hello,
 I setup EarlGrey 2.0 on my machine and managed to automate a single UI screen where I was able to click on a button but the script has been failing in the subsequent screen identifying ui elements and failing with this exception:

Exception: com.google.earlgrey.ElementInteractionErrorDomain
Upon opening the report I observed the following in the logs

I soon realized I need to tweak  GREYConfiguration but started seeing other errors please advice how to overcome this issue.Greatly appreciate any feedback on this issue.

FYI I tried making these  changes
 let greyConfig = GREYConfiguration()
 greyConfig.setValue(60.0, forConfigKey:GREYConfigKey.interactionTimeoutDuration)
 // greyConfig.setValue(30.0, forConfigKey:GREYConfigKey.caLayerMaxAnimationDuration)

But it failed with 
Assertion Failure: GREYConfiguration.m:49: failed: caught "NSInvalidArgumentException", "-[GREYConfiguration setValue:forConfigKey:]: unrecognized selector sent to instance 0x600002520260"
====================================================================
Log Report follows for Exception: com.google.earlgrey.ElementInteractionErrorDomain
====================================================================
UI Test Activity: 
Assertion Failure: BofAUITests.swift:75: Exception: com.google.earlgrey.ElementInteractionErrorDomain

Exception Name: com.google.earlgrey.ElementInteractionErrorDomain
Exception Reason: {
  "User Info" :   {
    "NSLocalizedDescription" : "App not idle within 30 seconds.",
    "NSUnderlyingError" : {
  "Description Glossary" :   {
    "GREYAppStateTracker" : "Waiting for network requests to finish. By default, EarlGrey tracks all network requests. To change this behavior, refer to GREYConfiguration.
Waiting for UIView's draw/layout pass to complete. A draw/layout pass normally completes in the next runloop drain.

Full state transition call stack for all objects:
<CALayer: 0x600001da54a0> => Waiting for UIView's draw/layout pass to complete. A draw/layout pass normally completes in the next runloop drain.
(
	0   AppFramework                        0x00000001027c60f9 -[GREYAppStateTrackerObject setState:] + 73
	1   AppFramework                        0x00000001027b1a26 __133-[GREYAppStateTracker grey_changeState:usingOperation:forObject:orInternalObjectDeallocationTracker:orExternalAppStateTrackerObject:]_block_invoke + 1302
	2   AppFramework                        0x00000001027b0b3f -[GREYAppStateTracker grey_performBlockInCriticalSection:] + 367
	3   AppFramework                        0x00000001027b13bd -[GREYAppStateTracker grey_changeState:usingOperation:forObject:orInternalObjectDeallocationTracker:orExternalAppStateTrackerObject:] + 1693
	4   AppFramework                        0x00000001027af6a0 -[GREYAppStateTracker trackState:forObject:] + 112
	5   AppFramework                        0x00000001027d14e6 -[CALayer(GREYApp) greyswizzled_setNeedsDisplayInRect:] + 134
	6   QuartzCore                          0x00007fff2b12db91 -[CALayer setNeedsDisplay] + 44
	7   AppFramework                        0x00000001027d18b3 -[CALayer(GREYApp) greyswizzled_setNeedsDisplay] + 355
	8   UIKitCore                           0x00007fff48565281 -[UIView(Rendering) setNeedsDisplay] + 82
	9   AppFramework                        0x00000001027ecdc3 -[UIView(GREYApp) greyswizzled_setNeedsDisplay] + 355
	10  UIKitCore                           0x00007fff48543e60 -[UIView initWithFrame:] + 127
	11  UIKitCore                           0x00007fff47a6a3da -[UIControl initWithFrame:] + 64
	12  UIKitCore                           0x00007fff47a5a338 -[UIButton initWithFrame:] + 91
	13  UIKitCore                           0x00007fff4838928f -[UITextField clearButton] + 113
	14  Foundation                          0x00007fff25712bba -[NSObject(NSKeyValueCoding) valueForKey:] + 317
	15  UIKitCore                           0x00007fff4838e479 -[UITextField valueForKey:] + 124
	16  AccessibilityUtilities              0x00007fff2e5a38c0 __57-[NSObject(UIAccessibilitySafeCategory) safeValueForKey:]_block_invoke + 30
	17  AccessibilityUtilities              0x00007fff2e5a3c10 -[NSObject(UIAccessibilitySafeCategory) _accessibilityPerformSafeValueKeyBlock:withKey:onClass:] + 69
	18  AccessibilityUtilities              0x00007fff2e5a35e8 -[NSObject(UIAccessibilitySafeCategory) safeValueForKey:] + 236
	19  UIKit                               0x0000000111314916 -[UITextFieldAccessibility _accessibilityRightButtons] + 75
	20  UIKit                               0x0000000111315261 -[UITextFieldAccessibility accessibilityElements] + 281
	21  UIAccessibility                     0x00007fff47494e06 -[NSObject(AXPrivCategory) _accessibilityElements] + 69
	22  UIAccessibility                     0x00007fff474b7274 -[NSObjectAccessibility accessibilityElementCount] + 81
	23  AppFramework                        0x000000010280a1e3 GREYTraversalExploreImmediateChildren + 1891
	24  AppFramework                        0x000000010281036c -[GREYTraversalDFS grey_nextObjectDFS] + 300
	25  AppFramework                        0x0000000102810013 -[GREYTraversalDFS enumerateUsingBlock:] + 339
	26  AppFramework                        0x0000000102811fcf +[GREYElementHierarchy hierarchyStringForElement:withAnnotationDictionary:] + 783
	27  AppFramework                        0x0000000102811c6d +[GREYElementHierarchy hierarchyStringForElement:] + 301
	28  AppFramework                        0x000000010281198b __39+[GREYElementHierarchy hierarchyString]_block_invoke + 635
	29  AppFramework                        0x0000000102811b2f __39+[GREYElementHierarchy hierarchyString]_block_invoke.19 + 47
	30  AppFramework                        0x00000001027ba7e2 __59-[GREYDispatchQueueTracker grey_dispatchSyncCallWithBlock:]_block_invoke + 50
	31  libdispatch.dylib                   0x00007fff5223f7b9 _dispatch_client_callout + 8
	32  libdispatch.dylib                   0x00007fff5224c861 _dispatch_async_and_wait_invoke + 109
	33  libdispatch.dylib                   0x00007fff5223f7b9 _dispatch_client_callout + 8
	34  libdispatch.dylib                   0x00007fff5224bc9b _dispatch_main_queue_callback_4CF + 1212
	35  CoreFoundation                      0x00007fff23bd4049 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	36  CoreFoundation                      0x00007fff23bceca9 __CFRunLoopRun + 2329
	37  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	38  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	39  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621

Thanks

**Comment by tirodkar** [comment]
Your app didn't idle within 60 seconds - can you check if you have a network request or an infinite animation? Generally animations are printed in the UI hierarchy.

**Comment by pavan-appannagari** [comment]
Thank you very much for the prompt reply.Yes,I do see several network requests with Waiting for network requests to finish even tough the appeared screen is positioned for subsequent actions.I pasted one below as example .Is there anyway I can overcome this?would you recommend somehow explicitly instruct in code to whitelist or ignore certain urls for synchronization?please advice how it can be done in Earlgrey 2 using Swift.

NSCFLocalDataTask:0x7fe26cc05610, URL:"https://yfjkbjkbjk/ghjgbjkjkk/use/
<__NSCFLocalDataTask:0x7fe28ce10b60, 

Waiting for network requests to finish. By default, EarlGrey tracks all network requests. To change this behavior, refer to GREYConfiguration.

**Comment by pavan-appannagari** [comment]
This implementation helped me resolve the issue

let urls: [String] = [".*abc.*",".*pqr.*]
let greyConfig = GREYConfiguration.shared
greyConfig.setValue(urls, forConfigKey:GREYConfigKey.urlBlacklistRegex)
