### ISSUE TITLE
Use of undeclared type 'GREYActionBlock' - GREYActionBlock not properly imported in CocoaPods setup (EarlGrey 2.0)

### ISSUE THREAD

**Issue by whoyawn** [google/EarlGrey#1282]
Used the example project to test out the method outlined in [the FAQ: Is there a way to return a specific element](https://github.com/google/EarlGrey/blob/master/docs/faq.md#is-there-a-way-to-return-a-specific-element)

At the bottom of `EarlGreyExampleSwiftUITests.swift` I declare the following:

```
// Must use a wrapper class to force pass by reference in Swift 3 closures.
// inout params cannot be modified within closures. http://stackoverflow.com/a/28252105
open class Element {
  var text = ""
}

/*
 *  Example Usage:
 *
 *  let element = Element()
 *  domainField.performAction(grey_replaceText("hello.there"))
 *             .performAction(grey_getText(element))
 *
 *  GREYAssertTrue(element.text != "", reason: "get text failed")
 */
public func grey_getText(_ elementCopy: Element) -> GREYActionBlock {
  return GREYActionBlock.action(withName: "get text",
  constraints: grey_respondsToSelector(#selector(getter: UILabel.text))) { element,
                                                                           errorOrNil -> Bool in
        let elementObject = element as? NSObject
        let text = elementObject?.perform(#selector(getter: UILabel.text),
                                          with: nil)?.takeRetainedValue() as? String
        elementCopy.text = text ?? ""
        return true
    }
}
```

I'm met with the error `Use of undeclared type 'GREYActionBlock'`. I'm able to call `GREYAction`, but not `GREYActionBlock`.

**Comment by tirodkar** [comment]
That's intended - you can't have a custom action in your test as it's only going to cause threading issues and we don't support it. You need the text here - try using a GREYAssertion instead.

**Comment by tsaarva** [comment]
If we're not intended to use this, why are there tests in the FunctionalTests project (referenced from EarlGrey2) that use GREYActionBlock?  I'm trying to upgrade from 1.0 and we've used this in several places...

**Comment by tirodkar** [comment]
@tsaarva are you referring to the GREYActionBlocks present in the HostDOCategories? Those are linked into the application side.

**Comment by tsaarva** [comment]
I was in the wrong branch....now that I'm in EarlGrey2, I see this:
```
// TODO: 3 tests are not ported since GREYActionBlock is not supported by eDO // // NOLINT
// on test side. Will need to find workaround for it.
```

**Comment by tirodkar** [comment]
Yes, those tests were not moved as they were using GREYActionBlocks exclusively on the test side. I believe those should already be ported, so I'll look into investigating that comment.
