### ISSUE TITLE
grey_allOf / grey_anyOf C-Functions are not exported to Swift.

### ISSUE THREAD

**Issue by tirodkar** [google/EarlGrey#13]
As can be seen in [EarlGreyExampleSwiftTests.m](https://github.com/google/EarlGrey/blob/master/Demo/EarlGreyExample/EarlGreyExampleSwiftTests/EarlGreyExampleSwiftTests.swift#L58), grey_allOf and grey_anyOf are not exported to Swift. Instead, we have to use them by calling their `init` methods. This needs to be investigated and the function calls fixed.

**Comment by mhnuman** [comment]
Init

**Comment by khandpur** [comment]
Wasn't this fixed by a recent PR?

**Comment by tirodkar** [comment]
This requires a separate update for the grey_allOf and grey_anyOf api.

**Comment by bootstraponline** [comment]
Is this fixed now with #82?

**Comment by tirodkar** [comment]
Yes, please use grey_allOfMatchers / grey_anyOfMatchers. Closing this for now.
