### ISSUE TITLE
Failing to compile on Xcode 12 beta 6 and iOS 14

### ISSUE THREAD

**Issue by githubist16** [google/EarlGrey#1432]
Is this supported? I also pulled the latest commit on earlgrey2 branch and getting error:

'Failed to build module 'XCTest' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.2.26.4 clang-1200.0.29.4)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)'

Error is tied to importing XCTest

Any insights

**Comment by tirodkar** [comment]
Can you tell us what you ran?

**Comment by githubist16** [comment]
It was an environment issue. Closing
