### ISSUE TITLE
Not possible to assert that a particular UIButton has a particular text

### ISSUE THREAD

**Issue by adil-hussain-84** [google/EarlGrey#1435]
It seems that it's not possible to assert that a particular `UIButton` (matched by its accessibility identifier) has a particular text with EarlGrey 1.16 (I've not tried it with EarlGrey 2). So if I set a `UIButton`'s accessibility identifier and text as follows...

```
someButton.accessibilityIdentifier = "SomeButton"
someButton.setTitle("Press Me", for: .normal)
```

... it would be great if I could write an assertion as follows...

```
EarlGrey.selectElement(with: grey_accessibilityID("SomeButton")).assert(grey_text("Press Me"))
```

This fails and I've created a super minimal Xcode project which demonstrates this [here](https://github.com/adil-hussain-84/EarlGreyExperiment).

Instead, I have to give the `UILabel` within the `UIButton` an accessibility identifier as follows...

```
someButton.titleLabel?.accessibilityIdentifier = "TitleLabelInSomeButton"
someButton.setTitle("Press Me", for: .normal)
```

... and then write my assertion as follows...

```
EarlGrey.selectElement(with: grey_accessibilityID("TitleLabelInSomeButton")).assert(grey_text("Press Me"))
```

This works but is not as elegant as asserting on the `UIButton` itself. It would be great if I could assert that the text within the `UIButton` itself is as expected.

**Comment by adambournsonos** [comment]
You may want to try `grey_buttonTitle`

For example,

`EarlGrey.selectElement(with: grey_accessibilityID("SomeButton")).assert(grey_buttonTitle("Press Me")`

**Comment by adil-hussain-84** [comment]
Thanks, that's perfect. Exactly what I was looking for.
