### ISSUE TITLE
Requesting a release with fixes for Xcode 12.0 and above

### ISSUE THREAD

**Issue by ravimandala** [google/EarlGrey#1483]
Aditya (@tirodkar)/ Sundeep (@sskhandp)
LinkedIn is using EarlGrey v1 for testing some of our iOS apps and we are blocked by ssue https://github.com/google/EarlGrey/issues/1461 at the moment. Can you please make a release with fixes from https://github.com/google/EarlGrey/pull/1481 (and optionally https://github.com/google/EarlGrey/pull/1482)?

\cc @chenxiao0228, @jmkk

**Comment by tirodkar** [comment]
We're not doing any more releases with EG 1 as the project has been deprecated for over a year now. We've just done a new EG 2 release with iOS 14 / Xcode 12 support. Please look at integrating with EarlGrey 2.0.

I'd highly recommend using submodules to get the latest OSS code with EarlGrey.
