### ISSUE TITLE
Please add me to Slack channel and Google Group

### ISSUE THREAD

**Issue by shaneong** [google/EarlGrey#1507]
Hi, I am looking into upgrading current test setup that uses EarlGrey 1.15 to EarlGrey 2.2, but found the documentation does not quite provide an easy way to do so. 

I was not able to access the links to the Slack channel nor the Google group listed on the main page readme. Can someone please add me to these platforms so I can seek help? Also, if anyone can point me to the right documentation for upgrading, that would be great as well.

**Comment by tirodkar** [comment]
Shane, mind sharing your email so we can add you? You can also do so on the Google group listed on the main page.

**Comment by shaneong** [comment]
The Google group link shows Content unavailable for me both signed in and logged out. 
<img width="1394" alt="Screen Shot 2020-12-07 at 3 59 38 PM" src="https://user-images.githubusercontent.com/26782048/101419601-3717d480-38a5-11eb-962f-b7cb84c537dd.png">

Please send the Slack invite to shengxun1997@gmail.com, thanks.

**Comment by tirodkar** [comment]
You should have an invite.

**Comment by liweijian** [comment]
@tirodkar Just wondering if maybe you could send me a slack invite ?

My email(base64): bGl3ZWlqaWFuLmh1c3RAZ21haWwuY29t
