### ISSUE TITLE
Compiler error when using EarlGrey from Swift target

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#151]
I have a complex setup in the app I'm automating and unfortunately it looks like EarlGrey triggers a Swift compiler bug.
<img width="1140" alt="earlgrey_import_error" src="https://cloud.githubusercontent.com/assets/1173057/16244894/43c08922-37cc-11e6-9e95-3636903f48c4.png">

One of our iOS developers investigated and discovered that if the macro in `EarlGrey.h` is renamed to anything other than `EarlGrey` (the module name) then everything works.

When I reproduced the setup on my example app, everything worked as expected. I'm not sure how to resolve the error other than locally modifying the header.

**Comment by tirodkar** [comment]
Is this on CocoaPods?

**Comment by bootstraponline** [comment]
> Is this on CocoaPods?

No, EarlGrey is loaded via Carthage. I've asked permission to see if I can share the project with Google. Will let you know when I hear back.

**Comment by tirodkar** [comment]
That would be great. Try changing the EarlGrey.zip file's name or so.

**Comment by bootstraponline** [comment]
> That would be great. Try changing the EarlGrey.zip file's name or so.

If I rename `Carthage/Build/iOS/EarlGrey.framework` then everything breaks. 😭

**Comment by tirodkar** [comment]
Try clicking on `EarlGrey.h` and literally type in `EarlGrey.h`. I know sometimes the naming acts in a weird way. Don't rename EarlGrey.framework, but the zip or so that you download.

**Comment by bootstraponline** [comment]
> but the zip or so that you download.

I don't download a zip... carthage checks out EarlGrey from GitHub master and then builds the framework.

I'll have approval to share the project soon. Will be easier to just wait until then.

**Comment by bootstraponline** [comment]
Solved internally by building EarlGrey from source instead of a prebuilt framework via Carthage. 😢
