### ISSUE TITLE
Licensing not clear

### ISSUE THREAD

**Issue by hyandell** [google/EarlGrey#1513]
Hi EarlGrey folk,

Is the intent that the project is licensed under "Apache-2.0 OR CC-BY-4.0", at the choice of the user, or are there parts that are CC-BY-4.0 and other parts that are Apache-2.0?

It's a bit unusual to be CC-BY or Apache-2.0, so while both are permissive, I thought it would be good if things were a bit clearer. Happy to suggest a PR once I understand what the intent is :)

**Comment by tirodkar** [comment]
Hey @hyandell the images are under cc and the source is under apache. Thanks for pointing this. I've sent a PR to fix this which should be in soon.
