### ISSUE TITLE
Disable RichHTML Without-Bounce Test

### ISSUE THREAD

**Issue by XericZephyr** [google/EarlGrey#152]
Due to a known swipe resistance detection bug, the unit tests of `testComponentsOnLocallyLoadedRichHTMLWithoutBounce` and `testLongTableOnLocallyLoadedRichHTMLWithoutBounce` are temporarily disabled.

**Comment by bootstraponline** [comment]
I don't see these unit tests [anywhere in EarlGrey](https://github.com/google/EarlGrey/search?utf8=%E2%9C%93&q=testComponentsOnLocallyLoadedRichHTMLWithoutBounce). Did you report this issue to the wrong repository?

**Comment by khandpur** [comment]
sorry for the late reply. They are in my latest PR: 
https://github.com/google/EarlGrey/pull/178

**Comment by tirodkar** [comment]
Disabled in https://github.com/google/EarlGrey/pull/179
