### ISSUE TITLE
Need Ealgrey 1.x patch with Xcode12 iOS14 support as Earlgrey2 is not working for whiteBox testing

### ISSUE THREAD

**Issue by radhap** [google/EarlGrey#1526]
We were using Earlgrey1 for our app's UI tests mainly as it supported white box testing. As we wanted to move to Xcode12, iOS 14 support we hit https://github.com/google/EarlGrey/issues/1447 issue and we started to upgrade to Earlgrey2 with all the needed white box setup.

But now, we hit blocking issue https://github.com/google/EarlGrey/issues/1516 

Earlgrey2 seems to have some issues (including the cocoapods setup which we usually use for 3rd party libs) with whiteBox testing

So, would appreciate, if you can do a Ealgrey 1.x patch with Xcode12 iOS14 support.

**Comment by tirodkar** [comment]
@radhap what is your use case for white-box setup? You should be able to do it with the GREYRemoteClassInApp() macro generally. EarlGrey 1.0 has been deprecated for over a year now and doesn't have many of the updates 2.0 has.

We can continue the discussion on #1516.
