### ISSUE TITLE
Taking screenshots on every Action

### ISSUE THREAD

**Issue by githubist16** [google/EarlGrey#1547]
Is there a custom way to take screenshots on every earlgrey action or rather navigation. I am developing tests that would capture every page visited by scripts and was wondering if earlgrey had mechanisms similar to Selenium's WebDriverEventListener allowing me to capture screenshots after certain events

https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/events/WebDriverEventListener.html

Or really any guidance on this issue without having to manually screenshot at strategic points

**Comment by githubist16** [comment]
Added workaround in my test suite. This might still be an interesting ask for someone else out there, but implemented a solution on our test suite level above the EG level

**Comment by tirodkar** [comment]
You could add a grey_snapshot() call to your EG statement to do this as well.
