### ISSUE TITLE
Where the "ios13fixes" branch?

### ISSUE THREAD

**Issue by LeePepe** [google/EarlGrey#1559]
I am trying to get the chromium source code by `fetch`
But I have an error that `Command 'git -c core.deltaBaseCacheLimit=2g fetch origin ff524fb646253b0cbc05aa6d0b327b6b3ddd0385 --no-tags' returned non-zero exit status 128 in /Users/tianpli-mac/Desktop/Development/edge/src/ios/third_party/earl_grey/src`
I can not found this branch "ios13fixes".
What should I do?

**Comment by tirodkar** [comment]
Is this being pulled from the chromium open-source repo? I deleted over 3 pages of stale branches last week ios13fixes was one of them as it was last updated over 2 years back.

**Comment by LeePepe** [comment]
Sorry, I think that I'm in a bad branch.

**Comment by kvtb** [comment]
chromium source (of a bit outdated browsers, like chromium-86) has explicit dependency on commit `ff524fb646253b0cbc05aa6d0b327b6b3ddd0385` which disappeared from this repo

**Comment by tirodkar** [comment]
I see. Do you need it from the Chromium side at this point?

**Comment by kvtb** [comment]
> I see. Do you need it from the Chromium side at this point?

I do not know that is the point for the Chromium guys.
I am building chromium-86 at the moment and stuck with the issue.

Hopefully, the tarball at https://github.com/google/EarlGrey/archive/ff524fb646253b0cbc05aa6d0b327b6b3ddd0385.tar.gz is still here (although `git fetch` is already shows that the commit is gone)
