### ISSUE TITLE
EarlGrey 2 folder structure in setup guide is incorrect

### ISSUE THREAD

**Issue by adil-hussain-84** [google/EarlGrey#1565]
After running the following two commands as instructed by the [setup](https://github.com/google/EarlGrey/blob/earlgrey2/docs/setup.md) guide...

```
git clone -b earlgrey2 https://github.com/google/EarlGrey.git
sh Scripts/download_deps.sh
```

... the `eDistantObject` and `fishhook` folders are not top-level as described [here](https://github.com/google/EarlGrey/blob/earlgrey2/docs/setup.md#1-steps-to-add-earlgrey-20-to-your-tests-using-xcode) but nested within a `Submodules` folder.

I wonder whether this is linked to some of the issues related to `eDistantObject` which I've seen being reported? I haven't got past this step yet so it might not be a problem but thought I'd call it out before I forget.

**Comment by tirodkar** [comment]
Thanks for pointing this out. I'll update it. So, the key is the step mentioned where you have to run this from the `EarlGrey/` directory. After this, make sure both EarlGreyV2/** and eDistantObject/** are added to your search paths.
