### ISSUE TITLE
EarlGrey2 unable to setup with Cocoapods

### ISSUE THREAD

**Issue by fbaumgart** [google/EarlGrey#1575]
Hello, since EG1 is no longer supported I've been trying to migrate to EG2. Using instructions provided in README I have edited my podfile accordingly and was able to retrieve the most recent version.
I followed the steps provided in "setup for Swift" section and pasted the contents of EarlGrey.swift linked in readme to the file with the same name which was already created in my project (by Cocoapods I guess). I also created the header file but the contents provided in readme did not work so I used contents of EarlGreySwiftBridgingHeader-Pods.h file from the FunctionalTests example which didn't produce any errors. As setup said I attached the file to my test target. I made necessary changes to my test code to adapt to the new API, but I still get very ambiguous error in the console at the end of ui test target build: "ld: framework not found EarlGrey".
Can you please provide some steps to resolve the issue?

**Comment by tirodkar** [comment]
First check to confirm - this is a UI Test target? You should not get `ld: framework not found EarlGrey` - I think this is coming from an EG 1 dependency in your Xcode Project.

**Comment by fbaumgart** [comment]
Yes, this is UI test target. I will review my project again for the old dependency but XCode isn't giving me any clue where is it located nor throwing error in particular file.

**Comment by fbaumgart** [comment]
@tirodkar can I kindly ask you for assistance? Or maybe you can advise where I can seek for help with this issue?

**Comment by fbaumgart** [comment]
today I followed information from this page https://github.com/google/EarlGrey/blob/earlgrey2/docs/white-boxing-setup-guide.md
and after that I'm no longer able to build my Unit or UI tests - I get a message 'Cycle inside <test target name>; building could produce unreliable results'

**Comment by tirodkar** [comment]
Do you have a simple project I can repro this with? If you have a cycle, then I'm guessing the distant object bundle is being double linked or the app is being added as a dep into it and vice versa.

**Comment by fbaumgart** [comment]
@tirodkar I have tried to setup a simple project - here is my repo https://github.com/fbaumgart/ethereum-price-monitor/tree/earl_grey_debug

First problem is - the compiler cannot find the paths to files from the header file - I tried to add the paths I looked up in macOS Finder to the Header Search Paths in Build Settings and it worked only for the first file from the list, second couldn't be found. Can you advise what these paths should look like?

**Comment by tirodkar** [comment]
Did you try setting the search paths to be recursive for this?

**Comment by fbaumgart** [comment]
Yes, it did not work.

**Comment by tirodkar** [comment]
Change your Header to just contain `#import <EarlGreyTest/EarlGrey.h>`

https://github.com/google/EarlGrey/blob/earlgrey2/Demo/EarlGreyExample/EarlGreySwiftBridgingHeader-Pods.h

**Comment by fbaumgart** [comment]
Thanks, after change in the header the build is successful, but I am getting a crash as in the screenshot:
![Screenshot 2021-04-16 at 10 43 56](https://user-images.githubusercontent.com/25124401/114998185-fc502980-9ea0-11eb-9e6c-d5669ebc3fb2.png)
It crashes in regular XCUITest and on EarlGrey example too. Also I am not able to launch unit tests with this error:
![Screenshot 2021-04-16 at 10 47 27](https://user-images.githubusercontent.com/25124401/114998348-299cd780-9ea1-11eb-8790-f2888b10ce02.png)

**Comment by tirodkar** [comment]
In "Other Linker Flags" - of the UI Test target, you have $(inherited) which is passing `-framework AppFramework` since I believe !use_frameworks is on. Can you remove the $(inherited) and check?

**Comment by fbaumgart** [comment]
I removed $(inherited) as advised but I still get the same error.

**Comment by fbaumgart** [comment]
Due to the configuration problems I decided to stop using EG, closing the issue.

**Comment by tirodkar** [comment]
FWIW, I was actually able to get the sample project up and running - https://github.com/fbaumgart/ethereum-price-monitor/compare/earl_grey_debug...tirodkar:earl_grey_debug?expand=1

I had to uncomment a few things from the Podfile, change the $inherited as above by commenting out `inherit! :search_paths` and updating the Pods to the latest versions. Might be worth giving it a look.
