### ISSUE TITLE
EarlGrey2 sample project broken (Cocoapods)

### ISSUE THREAD

**Issue by whoyawn** [google/EarlGrey#1578]
Took the most recent files from Demo/EarlGreyExample, ran a pod install, attempted to run UI tests, and got these errors:

`EarlGreyExampleSwiftUITests.swift`
```
  func testTakeSnapshot() throws {
    let image: EDORemoteVariable<UIImage> = EDORemoteVariable() // ERROR, Cannot find type 'EDORemoteVariable' in scope
    EarlGrey.selectElement(with: grey_accessibilityID("TapMe")).perform(
      grey_snapshot(image)) // ERROR, Cannot find 'grey_snapshot' in scope
    XCTAssertNotNil(image.object, "fails to take a screenshot from app side.")
  }
```

Additionally the Podfile does not match that of this markdown file: https://github.com/google/EarlGrey/blob/earlgrey2/docs/cocoapods-setup.md

In these instructions, we are to use `pod 'eDistantObject', '0.9.0'`, but in the sample project, the version is at `eDistantObject (1.0.2)`

**Comment by tirodkar** [comment]
We would need to update the cocoapods-setup file. Apologies for that. If you synched to the latest, did the Pods setup work?

**Comment by whoyawn** [comment]
In a separate project, doing a `pod install` without the `pod 'eDistantObject'` line correctly installs 1.0.2.
