### ISSUE TITLE
EarlGrey supported reporting frameworks

### ISSUE THREAD

**Issue by ken4ward** [google/EarlGrey#1609]
This project is very brilliant, but I don't know if I'm the one missing this part, I have not seen where generating reports have been mentioned in the docs. are there reporting frameworks like [Allure Reports](https://docs.qameta.io/allure/) EarlGrey supports? Please, very important and urgent.

**Comment by tirodkar** [comment]
@ken4ward EarlGrey allows you to specify `FailureHandlers` and set / reset them in the main API. You can use this API to create your own failure handler and format the GREYError object propagated from the application as you'd wish. Calling -debugDescription on the GREYError object will provide you some formatted information.
