### ISSUE TITLE
Cannot find 'kGREYConfigKeyAnalyticsEnabled' in scope

### ISSUE THREAD

**Issue by ken4ward** [google/EarlGrey#1610]
I'm trying to set the path of where screenshots should be saved with this code snippet, but it's throwing this error as noted on the topic. Where does the class it's calling in the EarlGrey directory?

```
override func setUp() {
        let directory = FileManager.SearchPathDirectory.desktopDirectory
        let domainMask = FileManager.SearchPathDomainMask.allDomainsMask
        let paths = NSSearchPathForDirectoriesInDomains(directory, domainMask, true)
        let path = "\(paths[0])/FailedTests"
        // Disable analytics.
        GREYConfiguration.sharedInstance().setValue(path, forConfigKey: kGREYConfigKeyAnalyticsEnabled)
    }
```

**Comment by tirodkar** [comment]
`kGREYConfigKeyAnalyticsEnabled` no longer exists in EarlGrey as we do not collect any usage analytics. I think you have that key wrong.
