### ISSUE TITLE
grey_activeRunLoopMode unrecognized selector

### ISSUE THREAD

**Issue by Arcikbtw** [google/EarlGrey#1621]
Hi,

I'm facing some issues in connecting earlgray2 to my Swift application.

I followed the instruction from earlgrey2 with manual setup, but tests are crashing with the simplest example.

Here you can find the error:
`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication grey_activeRunLoopMode]: unrecognized selector sent to instance 0x7fb041404860'`

Additionally, I've tried to run tests in the provided test app, but it ended the same way. 
I see that the header with the missing symbol exists, it can be added to the bridging header and even call manually from the test, but the error is the same.

![image](https://user-images.githubusercontent.com/6945296/125260331-88d38200-e300-11eb-8fbd-8ca20a810bde.png)

Do you have any ideas how to fix it?

**Comment by AlbertWang0116** [comment]
Artur, are you using the EarlGrey.xcodeproj in your setup?
