### ISSUE TITLE
Is it possible to switch custom keyboard and tap keys on it?

### ISSUE THREAD

**Issue by liweijian** [google/EarlGrey#1625]
Suppose we are going to test custom keyboard via EarlGrey2, I believe that the first step would be install the custom keyboard , and add it by `General->Keyboard->Keyboards->Add New Keyboard...`

In order to test the custom keyboard, we may need another app(for example, [100 lines notes app](https://gist.github.com/jnewc/35692b2a5985c3c99e847ec56098a451#gistcomment-3730800)), and switch the keyboard by clicking the following **earth icon**:

<img src="https://user-images.githubusercontent.com/19320783/126778746-08dc3216-8b89-415b-ac45-e8a26e09918e.png" width=300>

Then the target keyboard here!

<img src="https://user-images.githubusercontent.com/19320783/126780045-fb323841-019e-49b4-accf-d06a1086465a.png" width=300>

My questions are:
1. How can I find the `.accessibility - identifier` of the **earth icon** ? In that case, we can change the keyboard by `EarlGrey.selectElement(with: grey_accessibilityID("EARTH_LOGO")).perform(grey_tap())`
2. How to tap specific keys in custom keyboard? Like `h`/`e`/`y` in this case.
3. How to tap the first candidate of the results? `Heyday` as above.

**Comment by liweijian** [comment]
After short investigation,  I believe that I had figure it out

For the **earth icon**, we could use `app.buttons["Next keyboard"].tap()`

For the specific keys, using `app.staticTexts["O"].tap()`

The last thing is picking the first candidate, `app.buttons["Heyday"].tap()` works in this case, but it seems that we may not easily tap the first element in the word list without knowing its content.

**Comment by tirodkar** [comment]
You can also use `[[EarlGrey selectElementWithMatcher:grey_accessibilityLabel(@"Next keyboard")] performAction:grey_tap()];` and just work fine as well. We don't want to actually allow Auto-Predicted text in EarlGrey tests as it removes control over typing, so your way works fine.

**Comment by liweijian** [comment]
@tirodkar Cool! Just wondering if maybe we could click the first candidates for whatever it shows? Basically we didn't intend to test the _Auto-Predicted text_ , but only wanna to make sure candidates were displayed.
