### ISSUE TITLE
Is there any example on doing screenshot in Swift api?

### ISSUE THREAD

**Issue by impvd** [google/EarlGrey#1626]
Google search yields this repo https://github.com/elpassion/EarlGreySnapshots , but it seems they don't maintain it anymore(The last commit was 4 years ago).

There're [some examples](https://github.com/google/EarlGrey/blob/3dea3131727ededff56d967d940aa80d962aed3a/Tests/FunctionalTests/Sources/FTRScreenshotTest.m) relate to screenshot, could anyone help to give some suggestion on migrating these Object-C examples to Swift?

For example(From [setup doc](https://github.com/google/EarlGrey/blob/earlgrey2/docs/setup.md)):

```swift
class MyFirstEarlGreyTest: XCTestCase {

  func testExample() {
    let application: XCUIApplication = XCUIApplication()
    application.launch()
    // HOW TO SCREENSHOT HERE
    EarlGrey.selectElement(with: grey_keyWindow())
      .perform(grey_tap())
  }
}
```

I had tried [perfecto's samples](https://help.perfecto.io/perfecto-help/content/perfecto/automation-testing/take_screenshots_with_xctest_methods.htm):

```swift
let confpath = GREYConfiguration.sharedInstance().value(forConfigKey: kGREYConfigKeyArtifactsDirLocation) as! String
var screenshot = GREYScreenshotUtil.takeScreenshotForAppStore()
var filename = String(describing: EarlGreySimpleIosAppForTestingTests.self) + "#" + #function + ".png"
GREYScreenshotUtil.saveImage(asPNG: screenshot, toFile: filename, inDirectory: confpath)
EarlGrey.select(elementWithMatcher: grey_text("EarlGrey Tests")).assert(grey_sufficientlyVisible())
```

Which got lots of errors:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/37371804/127580064-b596b70f-3da7-429f-ac8b-6e5bcd82e4cc.png">

**Comment by tirodkar** [comment]
Is this EarlGrey 1.0? That is not supported anymore. 

Here is a Snapshot Example for EarlGrey 2.0.

https://github.com/google/EarlGrey/blob/earlgrey2/Tests/Functional/Sources/Swift/SwiftTests.swift#L315
