### ISSUE TITLE
Is there any way to test Search from iOS's main screen?

### ISSUE THREAD

**Issue by impvd** [google/EarlGrey#1642]
Most of the tutorials I found about XCTest or EarlGrey were about doing UI testing inside the app.

I am curious if we could write a UI test case that would come across the Search of iOS's main screen, like type a word **watch** in it:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/37371804/133066400-e0307796-932f-4d21-8738-de27a0bf6c80.png">

And click the **Chrome** result from it:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/37371804/133066447-8f504184-abf7-4150-ad88-73b76c98fe64.png">

**Comment by tirodkar** [comment]
You can use the XCUITest API's to go there, swipe up and search in the spotlight bar. This isn't necessarily EarlGrey related.
