### ISSUE TITLE
Add Pinch Gesture For EarlGrey.

### ISSUE THREAD

**Issue by tirodkar** [google/EarlGrey#166]
Investigate and implement a pinch gesture update.

**Comment by sid-github** [comment]
EarlGrey 1.2.0 Adds this feature

**Comment by sid-github** [comment]
Just FYI the actions are called: `grey_pinchFastInDirection` and `grey_pinchSlowInDirection`
listed in [GREYActions.h](https://github.com/google/EarlGrey/blob/master/EarlGrey/Action/GREYActions.h).
