### ISSUE TITLE
AppFramework linking issue

### ISSUE THREAD

**Issue by ileon12** [google/EarlGrey#1676]
I am trying to install EarlGrey 2 to my project with CocoaPods. 

This is my Podfile:

--------------------------------

```
workspace 'TestProjectWorkspace.xcworkspace'
project 'TestProject/TestProject.xcodeproj/'
platform :ios, '15.0'
use_frameworks!

target 'TestProject' do
  pod 'EarlGreyApp'
end
target 'TestProjectUITests' do
  pod 'EarlGreyTest'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
```

--------------------------------

After successfully completing the installation, when I try to build the application I get the following error:

`ld: building for iOS, but linking in dylib file (/Users/{my_username}/{project_directory}/Pods/EarlGreyApp/EarlGreyApp/AppFramework.framework/AppFramework) built for iOS Simulator, file '/Users/{my_username}/{project_directory}/Pods/EarlGreyApp/EarlGreyApp/AppFramework.framework/AppFramework' for architecture arm64`

**Comment by tirodkar** [comment]
PTAL @ https://github.com/google/EarlGrey/issues/1647.
