### ISSUE TITLE
Fix warnings in Swift Tests

### ISSUE THREAD

**Issue by khandpur** [google/EarlGrey#171]
From https://travis-ci.org/google/EarlGrey/jobs/142102430:

Compiling FTRSwiftTests.swift
⚠️  /Users/travis/build/google/EarlGrey/Tests/FunctionalTests/Sources/FTRSwiftTests.swift:56:9: variable 'searchButtonMatcher' was never mutated; consider changing to 'let' constant
    var searchButtonMatcher: GREYMatcher = grey_accessibilityHint("Search")
    ~~~ ^
▸ Compiling EarlGrey.swift
▸ Compiling FTRSwiftTests.swift
⚠️  /Users/travis/build/google/EarlGrey/Tests/FunctionalTests/Sources/FTRSwiftTests.swift:56:9: variable 'searchButtonMatcher' was never mutated; consider changing to 'let' constant
    var searchButtonMatcher: GREYMatcher = grey_accessibilityHint("Search")

**Comment by axi0mX** [comment]
https://github.com/google/EarlGrey/pull/173
