### ISSUE TITLE
Add a Contrib project to test out experimental EarlGrey API's.

### ISSUE THREAD

**Issue by tirodkar** [google/EarlGrey#177]
To be located in the `Demo/` folder and should use the setup script to integrate with EarlGrey.

**Comment by khandpur** [comment]
Isn't this done?

I see that project here: https://github.com/google/EarlGrey/tree/master/Demo/EarlGreyContribs

**Comment by tirodkar** [comment]
This is completed in https://github.com/google/EarlGrey/pull/188. Closing this.
