### ISSUE TITLE
End to End testing of EarlGrey gem

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#183]
The EarlGrey gem is tested using Xcode project fixtures. This ensures that the Xcode project is correctly configured.

There are currently no E2E test to verify that the configured project actually runs. Once we have a working CI solution, it'd be valuable to assert that the final Xcode project successfully executes tests.

**Comment by sskhandp** [comment]
@tirodkar isn't this essentially covered by our travis tests now?

**Comment by tirodkar** [comment]
Yes it is. Since we do a rake install every time, we do check if the current gem works with the test project. Closing it.

@bootstraponline feel free to re-open this in case there might be cases we aren't covering.
