### ISSUE TITLE
Issue in running setup-earlgrey.sh

### ISSUE THREAD

**Issue by AshishGogna** [google/EarlGrey#20]
I tried running setup-earlgrey.sh several times.
But, it says - "There was an issue moving Fishhook as per the EarlGrey specification.".

What's wrong ?

**Comment by tirodkar** [comment]
@AshishGogna, could you show us your file structure for debugging in case there are any extra files? You could try cleaning the `EarlGrey/` directory of any generated files and try running the script again.

**Comment by AshishGogna** [comment]
This solved the issue !
Cloned the repo in another directory.
