### ISSUE TITLE
cocoapods 0.39 / xcodeproj conflict

### ISSUE THREAD

**Issue by gurgeous** [google/EarlGrey#214]
I tried to use EarlGrey with cocoapods 0.39. I think this is supported, but there's a conflict between xcodeproj versions. Pod install fails:

`Gem::LoadError - Unable to activate earlgrey-0.0.8, because xcodeproj-0.28.2 conflicts with xcodeproj (>= 1.0)`

https://rubygems.org/gems/cocoapods/versions/0.39.0
https://rubygems.org/gems/earlgrey/versions/0.0.8

Am I interpreting this correctly? Any suggestions?

**Comment by bootstraponline** [comment]
> I tried to use EarlGrey with cocoapods 0.39. I think this is supported,

It's not. The EarlGrey gem requires xcodeproj 1.0 or newer.

**Comment by tirodkar** [comment]
@gurgeous, CocoaPods has an internal dependency on xcodeproj which the earlgrey gem conflicts with. You can still use EarlGrey with CocoaPods, but you won't be able to use the gem for it.

We **highly** recommend that you update your CocoaPods version. In case you're blocked and cannot do so - take a look at our old EarlGrey install and release guide for CocoaPods where you'd have to manually copy the EarlGrey.swift and configure_earlgrey_pods file.

https://github.com/google/EarlGrey/blob/11a4f329df59e01426235561f9a1d7ff0c10c43e/docs/install-and-run.md

**Comment by gurgeous** [comment]
I will attempt to update to the latest cocoapods. Our app is complex and the upgrade we attempted several months ago was not a success.

We should probably revise the install page:

https://github.com/google/EarlGrey/blob/master/docs/install-and-run.md

which contains stale instructions for using 0.39. Thanks guys!

**Comment by khandpur** [comment]
Thanks for updating our instructions Adam!
