### ISSUE TITLE
setup fails to end

### ISSUE THREAD

**Issue by RomainQuidet** [google/EarlGrey#22]
Env: iOS 9.2, iPhone 5s simulator + Xcode 7.2.1
In my test setup, the line 
`[[[XCUIApplication alloc] init] launch];`
never returns.
If I remove it the tests run correctly. Is this line needed ?

**Comment by sid-github** [comment]
As noted in https://github.com/google/EarlGrey/blob/master/docs/install-and-run.md please use iOS **unit test** bundle instead of UI tests (that use XCUI* classes).

**Comment by RomainQuidet** [comment]
Makes sense, thanks.
