### ISSUE TITLE
configure_earlgrey - CommandLineArguments crash

### ISSUE THREAD

**Issue by gurgeous** [google/EarlGrey#221]
During `pod install` with cocoapods 1.0.1, see below. I believe this is because our xcscheme has `EnvironmentVariables` but not `CommandLineArguments`.

```
Generating Pods project
Checking and Updating HomeAway for EarlGrey.
Adding EarlGrey Framework Location as an Environment Variable
in the App Project's Test Target's Scheme Test Action.

[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `elements' for nil:NilClass

/gems/2.1.0/gems/earlgrey-0.0.8/lib/earlgrey/configure_earlgrey.rb:251:in `add_environment_variables_to_test_action_scheme'
/gems/2.1.0/gems/earlgrey-0.0.8/lib/earlgrey/configure_earlgrey.rb:153:in `modify_scheme_for_actions'
/gems/2.1.0/gems/earlgrey-0.0.8/lib/earlgrey/configure_earlgrey.rb:112:in `configure_for_earlgrey'
/gems/2.1.0/gems/earlgrey-0.0.8/lib/earlgrey/configure_earlgrey.rb:18:in `configure_for_earlgrey'
Podfile:78:in `block (2 levels) in from_ruby'
```

**Comment by bootstraponline** [comment]
Thanks for reporting this issue! It's a bug in the EarlGrey gem.

**Comment by tirodkar** [comment]
@gurgeous - to confirm, you don't have <CommandLineArguments> present anywhere in your xcscheme file?

**Comment by gurgeous** [comment]
My xcscheme file has `<EnvironmentVariables>` but no `<CommandLineArguments>`

**Comment by tirodkar** [comment]
Our [demo app schemes](https://github.com/google/EarlGrey/tree/master/Demo/EarlGreyExample/EarlGreyExample.xcodeproj/xcshareddata) do not have any CommandLineArguments either. Would you mind posting your scheme or something analogous to it? This seems like a case we aren't covering.

**Comment by gurgeous** [comment]
I cannot post my xcscheme, unfortunately. I diagnosed the bug by inspecting the code in the gem... Could be wrong, though. When I removed my `<EnvironmentVariables>` section I was able to complete the `pod install`.

**Comment by bootstraponline** [comment]
It'd be nice if you could post a redacted version of the xcscheme so we can reproduce & resolve the bug. The schemes in our test suite contain `<EnvironmentVariables>` and they work correctly.

**Comment by gurgeous** [comment]
When I read the code in your gem, it looks like this line will fail:

`launch_action_args.elements.each ...`

when the following conditions are true:

- EnvironmentVariables in launch action
-

**Comment by tirodkar** [comment]
Yes, we assume that if you've come to that step then you have both Environment Variables and Command Line Args present in your scheme. [Here](https://github.com/google/EarlGrey/blob/master/gem/lib/earlgrey/configure_earlgrey.rb#L212), we in fact add a temporary CommandLineArg call for it. This does actually seem like a legitimate issue. Please feel free to reopen this if you can provide us a redacted version of your scheme or so, or possibly modify one of our provided schemes to show the failure happening. Thanks!

**Comment by gurgeous** [comment]
I've had three serious install issues trying to get EarlGrey working with our app, so I'm moving on now. I might try again when there's broader adoption. Thanks guys, good luck!

**Comment by tirodkar** [comment]
@gurgeous - Thanks for bringing the issues to our attention. It would be great if you gave us your email id so we could invite you to join our [slack channel](https://googleoss.slack.com/messages/earlgrey). We're trying with every new iteration of EarlGrey to make the installation process smoother, and we'd love to help you step directly through any issues that you're facing.

I'm re-opening this issue since I'd like to test it out myself with different version of our scheme, to see if I can reproduce a similar error from my side.

**Comment by gurgeous** [comment]
sure - amd@gurge.com

**Comment by tirodkar** [comment]
Invite Sent! Thanks.

**Comment by Milesyan** [comment]
Seems the latest fix has some problem.
I checkout the last master and meets ```[!] An error occurred while processing the post-install hook of the Podfile.

undefined method `elements' for nil:NilClass

/Users/Miles/.rvm/gems/ruby-2.2.1/gems/earlgrey-0.0.9/lib/earlgrey/configure_earlgrey.rb:246:in `add_environment_variables_to_test_action_scheme'
/Users/Miles/.rvm/gems/ruby-2.2.1/gems/earlgrey-0.0.9/lib/earlgrey/configure_earlgrey.rb:154:in `modify_scheme_for_actions'
/Users/Miles/.rvm/gems/ruby-2.2.1/gems/earlgrey-0.0.9/lib/earlgrey/configure_earlgrey.rb:113:in `configure_for_earlgrey'
/Users/Miles/.rvm/gems/ruby-2.2.1/gems/earlgrey-0.0.9/lib/earlgrey/configure_earlgrey.rb:18:in `configure_for_earlgrey'
/Users/Miles/EarlGrey/EarlGrey/Demo/EarlGreyExample/Podfile:42:in `block (3 levels) in from_ruby'```

But if I checkout 4dd1953e94511b90e695ece4e905685ac07a1b04, the commit before fixing this bug, pod install works well

**Comment by tirodkar** [comment]
@Milesyan - this fix is not yet part of the `earlgrey gem`. Do you have environment variables present in the Launch Action of your Scheme? Could you copy the [configure earlgrey script](https://github.com/google/EarlGrey/blob/master/gem/lib/earlgrey/configure_earlgrey.rb) from head and see if the issue still persists?
