### ISSUE TITLE
method grey_pickerColumnSetToValue works while Userinteraction disabled

### ISSUE THREAD

**Issue by DiedeGu** [google/EarlGrey#241]
Dear reader, 

I was able to use the grey_pickerColumnSetToValue() method successfully on a UIPicker that I set to userInteractionEnabled to false with the Interface Builder. In other words, I was able to change the value of the UIPicker. I think this should not be the case but I am not that deep into acceptance testing and accessibility settings. 

If you want a example project I could set one up. 

Kind Regards, 

Diede

**Comment by tirodkar** [comment]
@DiedeGu, could you use `GREYElementHierarchy` or `grey_description` and print the details of the UIPicker?

**Comment by khandpur** [comment]
Wouldn't it be easier to add a test to our [existing picker view test](https://github.com/google/EarlGrey/blob/0481d29a250a26f7281bad2b5b2019a3060a8c82/Tests/FunctionalTests/Sources/FTRPickerViewInteractionTest.m) suite to demonstrate the unexpected behavior?

**Comment by DiedeGu** [comment]
Hi Guys!

Thanks for the advise, I extended the test with one for a disabled UIPicker. Now I have some questions concerning both the test and its fix. 

1. Is the test ok? 
I currently perform the set to value method and then assert if the disabled UIPicker kept the original value. Do you want the test to be like this or do you want to test if a error is given when you try this on a disabled UIPicker? 

2. What should the fix do? 
I also have a possible fix, which currently returns the set to value method with a success, without actually changing the value. This is closest to the real behavior for users. You can press the UIPicker as much as you want and it does not change and does not crash. 
I could also throw an error which is much more informative for the Developer but is not what will happen to a real user. 

Please let me know, then I'll provide a Pull Request.

**Comment by khandpur** [comment]
1. I would rather pass in an error in form of a constraint failure. GREYPickerAction has the following constraints:
- `grey_interactable()`
- `grey_not(grey_systemAlertViewShown())`
- `grey_kindOfClass([UIPickerView class])`
and I would add grey_userInteractionEnabled() to it after grey_interactable().
Then your test should pass in an error object (`performAction:error:`) assert that the error is correctly populated and then assert that the picker value isn't changed (like you already do).

2. The fix should be similar to what I described above.

Sure, send a PR our way...we'd be happy to look at it :)

**Comment by tirodkar** [comment]
I believe this was closed in https://github.com/google/EarlGrey/pull/251. @DiedeGu, feel free to re-open this in case it wasn't.
