### ISSUE TITLE
How to performactions with tap on the keyboard

### ISSUE THREAD

**Issue by jeff77731** [google/EarlGrey#248]
As title,

Is there a way to trigger the tap event on keyboard with "return" key?

**Comment by tirodkar** [comment]
Hey @jeff77731, EarlGrey has a type action that lets you perform any typing with the keyboard that you need. In the case of the return key you could perform a typing action like:
```
[[EarlGrey selectElementWithAction:grey_accessibilityLabel(@"SOME_TEXT_FIELD")]
      performAction:grey_typeText(@"\n")];
```
as in [this test](https://github.com/google/EarlGrey/tree/master/Tests/FunctionalTests/Sources/FTRKeyboardKeysTest.m#L238).

which will press the return key. You can also select the return key itself and tap it using an action such as:
```
[[EarlGrey selectElementWithMatcher:grey_accessibilityLabel(@"return")]
      performAction:grey_tap()];
```
as in the [test here](https://github.com/google/EarlGrey/tree/master/Tests/FunctionalTests/Sources/FTRKeyboardKeysTest.m#L130).

**Comment by tirodkar** [comment]
@jeff77731, closing this for now. Do reopen if there might be something more you'd like to add here.
