### ISSUE TITLE
can't find UITableViewCell

### ISSUE THREAD

**Issue by gurgeous** [google/EarlGrey#258]
I am trying to tap a UITableViewCell with accessibilityLabel "7116" but EarlGrey can't find it:

```objc
[[EarlGrey selectElementWithMatcher:grey_accessibilityLabel(@"7116")] performAction:grey_tap()];
```

Output below. If I replace that line with the following:

```objc
[[[EarlGrey selectElementWithMatcher:grey_kindOfClass(UITableViewCell.class)] atIndex:0] performAction:grey_tap()];
```

it works fine.

```
Exception: NoMatchingElementException
Reason: Action 'Tap' was not performed because no UI element matching (respondsToSelector(accessibilityIdentifier) && accessibilityID("7116")) was found.
...
<UITableViewCell; AX=N; AX.label='7116'; AX.frame={{0, 64}, {375, 44}}; AX.activationPoint={187, 86}; AX.traits='UIAccessibilityTraitButton'; AX.focused='N'; frame={{0, 0}, {375, 44}}; opaque; alpha=1; text='Austin'>
|--<UITableViewCellContentView; AX=N; AX.frame={{0, 64}, {341, 43}}; AX.activationPoint={170, 85}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 0}, {341, 43}}; opaque; alpha=1>
|  |--<UITableViewLabel; AX=Y; AX.label='Austin'; AX.frame={{16, 70}, {42, 18}}; AX.activationPoint={37, 79}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{16, 6}, {42, 18}}; opaque; alpha=1; UIE=N; text='Austin'>
|  |--<UITableViewLabel; AX=Y; AX.label='Texas'; AX.frame={{16, 88}, {32, 14}}; AX.activationPoint={32, 95}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{16, 24}, {32, 14}}; opaque; alpha=1; UIE=N; text='Texas'>
|--<UIButton; AX=Y; AX.label='More Info'; AX.frame={{351, 79}, {8, 13}}; AX.activationPoint={355, 85}; AX.traits='UIAccessibilityTraitButton,UIAccessibilityTraitNotEnabled'; AX.focused='N'; frame={{351, 15}, {8, 13}}; alpha=1; UIE=N>
|  |--<UIImageView; AX=N; AX.frame={{351, 79}, {8, 13}}; AX.activationPoint={355, 85}; AX.traits='UIAccessibilityTraitImage'; AX.focused='N'; frame={{0, 0}, {8, 13}}; alpha=1; UIE=N>
|--<_UITableViewCellSeparatorView; AX=N; AX.frame={{16, 107}, {359, 0}}; AX.activationPoint={195, 107}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{16, 43}, {359, 0}}; opaque; alpha=1>
...
```

Any suggestions? Thanks guys.

**Comment by gurgeous** [comment]
Oh, and I'm using 1.2.0.

**Comment by tirodkar** [comment]
@gurgeous, how many times is `AX.label='7116'` visible in your hierarchy? This might be a multiple matchers exception being incorrectly thrown as something else.

However, notice how `<UITableViewCell; AX=N` is present for that cell. EarlGrey needs the element to be accessible. Can you match on `Austin` or `Texas` as the accessibilityLabel instead?

**Comment by khandpur** [comment]
From the hierarchy:
```<UITableViewCell; AX=N; AX.label='7116'; AX.frame={{0, 64}, {375, 44}}; AX.activationPoint={187, 86}; AX.traits='UIAccessibilityTraitButton'; AX.focused='N'; frame={{0, 0}, {375, 44}}; opaque; alpha=1; text='Austin'>```

you can see that the accessibility label is set to 7116, not the identifier. You would need to set the identifier in your code where you dequeue the cell (i.e. in tableView:cellForRowAtIndexPath:) method. Let me know if that doesn't work.

Alternatively, you can set the cell's isAccessibilityElement property to YES and use the grey_accessibilityLabel(@"7116") to match that cell.

**Comment by tirodkar** [comment]
> how many times is AX.label='7116' visible in your hierarchy? This might be a multiple matchers exception being incorrectly thrown as something else.

Just noticed from @khandpur's comment that the second case used `grey_kindOfClass` rather than `grey_accessibilityIdentifier`. This isn't related to multiple matchers then.

**Comment by gurgeous** [comment]
Thanks for the tip - it works if I set`isAccessibilityElement=YES`. Can we improve the error message? There are several improvements that I can imagine:

- Don't mention tapping at all if the matcher can't find the element
- When using grey_accessibilityLabel, point the user at accessibilityLabel (not accessibilityIdentifier)
- Give the user a hint about isAccessibilityElement if the element is found but isn't marked as accessible. I had no idea what AX=N meant. :)

I know it seems silly, but this stuff becomes really important when you unleash EarlGrey on a team of fresh engineers.

**Comment by tirodkar** [comment]
Closing this for now. The Issues were tracked in another bug. Thanks @gurgeous
