### ISSUE TITLE
typeText fails if textfield has input accessory

### ISSUE THREAD

**Issue by foulkesjohn** [google/EarlGrey#270]
Details here: http://stackoverflow.com/questions/39295444/waiting-for-viewdidappear-call-on-uicompatibilityinputviewcontroller

**Comment by tirodkar** [comment]
@foulkesjohn, it would immensely help us if you could provide us a minimum possible Test project that contains this issue. Thanks a lot.

**Comment by tirodkar** [comment]
Alternatively, please add to our FunctionalTests project and see if you could please repro the issue.

**Comment by khandpur** [comment]
@tirodkar was able to repro this and is working on a fix.

**Comment by tirodkar** [comment]
Fixed in https://github.com/google/EarlGrey/pull/431
