### ISSUE TITLE
How to extension GREYMatchers?

### ISSUE THREAD

**Issue by jeff77731** [google/EarlGrey#285]
I want to extension GREYMatchers for customize my own matcher

	extension GREYMatchers {

		public func grey_btnEnable(enable: Bool) -> GREYMatcher! {
			let matches: MatchesBlock = { (element: AnyObject!) -> Bool in
				return (element as? UIButton)!.enabled == enable
			}

			let describe: DescribeToBlock = { (description: GREYDescription!) -> Void in
				description.appendText("test")
			}

			return GREYElementMatcherBlock(matchesBlock: matches, descriptionBlock: describe)
		}
	}

But it not work, I cannot find the function when use
EarlGrey().selectElementWithMatcher(grey_accessibilityID("test")).assertWithMatcher(grey_btnEnable(false))
What's wrong with it?

**Comment by tirodkar** [comment]
Remember that `grey_accessibilityID ()` etc. are c functions. You've created a swift method on GREYMatchers if I'm right. Instead, add it as a method in your file, akin to `grey_firstElement` [here](https://github.com/google/EarlGrey/blob/master/Tests/FunctionalTests/Sources/FTRSwiftTests.swift#L189).

**Comment by tirodkar** [comment]
@jeff77731, were you able to solve your issue with this? Feel free to reopen the issue in case it is still present.
