### ISSUE TITLE
configure_for_earlgrey fails if current directory doesn't contain the Podfile

### ISSUE THREAD

**Issue by ajsecord** [google/EarlGrey#287]
CocoaPods supports running `pod install` with a `--project_directory` option that should effectively act like

```sh
cd project_directory
pod install
```

When doing so with a CocoaPods project configured using the current EarlGrey installation instructions, using `--project_directory` causes `configure_for_earlgrey` to fail with the following error message:

```sh
Checking and Updating <MY_PROJECT> for EarlGrey.
[!] An error occurred while processing the post-install hook of the Podfile.

[Xcodeproj] Unable to open `<FULL_PATH_TO_WHERE_POD_INSTALL_WAS_RUN>/<MY_PROJECT>.xcodeproj` because it doesn't exist.

/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project.rb:99:in `open'
/Library/Ruby/Gems/2.0.0/gems/earlgrey-0.0.13/lib/earlgrey/configure_earlgrey.rb:91:in `set_defaults'
/Library/Ruby/Gems/2.0.0/gems/earlgrey-0.0.13/lib/earlgrey/configure_earlgrey.rb:110:in `configure_for_earlgrey'
/Library/Ruby/Gems/2.0.0/gems/earlgrey-0.0.13/lib/earlgrey/configure_earlgrey.rb:18:in `configure_for_earlgrey'
/Users/ajsecord/Source/Git/material-components-ios2/catalog/Podfile:65:in `block (2 levels) in from_ruby'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/podfile.rb:180:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.0.1/lib/cocoapods-core/podfile.rb:180:in `post_install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:823:in `run_podfile_post_install_hook'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:811:in `block in run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:810:in `run_podfile_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:172:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

Note that it's trying to open the .xcodeproj from the current directory, not the project directory. There's probably some CocoaPods variable that would give the correct directory.

Note: I'm sure I could hack the `configure_for_earlgrey` invocation to get this to work, but the bug is that the current install instructions and a supported CocoaPods usage pattern is in conflict.

**Comment by ajsecord** [comment]
This is CocoaPods version 1.0.1, by the way.

**Comment by tirodkar** [comment]
Hmm, since we use the path for finding the project [here](https://github.com/google/EarlGrey/blob/master/gem/lib/earlgrey/configure_earlgrey.rb#L73) Is this fixed if you pass the path to the project to the configure script instead of just the name? We'll get in support for this feature asap. Thanks.

**Comment by ajsecord** [comment]
The issue is that the Podfile should work when `pod install` is invoked both inside the directory and from somewhere else with `--project_directory`. If I understand your suggestion correctly, that would end up making it work for one option but no longer for the other. Some kind of variable set by CocoaPods is needed, I think. I spent some time looking for one, but my CocoaPods/Ruby fu is poor.

**Comment by tirodkar** [comment]
@ajsecord, you can directly pass in the project path with every single time you call the configure script for every pods target that you have. We'll try to add this as a flag to adding EarlGrey as well. Thanks.

**Comment by ajsecord** [comment]
@tirodkar Thanks for the idea, but I don't think that will work. How could my Podfile know in advance the right path? It needs to work both if `pod install` is called from the same directory as the Podfile and from some other directory but with the `--project-directory` flag.

**Comment by bootstraponline** [comment]
I debugged this and here's how to get the project directory.

```bash
$ pod install --project-directory=/tmp
> Pod::Config.instance.installation_root
=> #<Pathname:/tmp>
```
