### ISSUE TITLE
Can still tap while UIAlertView is shown

### ISSUE THREAD

**Issue by DiedeGu** [google/EarlGrey#288]
when my application throws an UIAlertView I am still able to let EarlGrey tap on a button, while I am not able to press this button, (it is not part of the UIAlertView) during an manual test.

**Comment by tirodkar** [comment]
EarlGrey cannot handle system dialogs [similar issue and workaround here](https://github.com/google/EarlGrey/issues/55). In fact, all touches to it go straight through, which is probably what you're seeing here.

Could you confirm if this was a system alert view?

**Comment by tirodkar** [comment]
@DiedeGu, any updates on this?

**Comment by DiedeGu** [comment]
@tirodkar yes, sorry, it is a system alert thank you for replying.
