### ISSUE TITLE
Idling Resources Philosophy

### ISSUE THREAD

**Issue by rotemmiz** [google/EarlGrey#296]
Hello there,

I am trying to understand the philosophy behind using multiple IdlingResources, it seems like Google made a great effort to create all kinds of sophisticated mechanisms to stick with this idea. 

The documentation addresses this by saying:

> "EarlGrey’s synchronization features help to ensure that the UI is in a steady state before actions are performed. This greatly increases test stability and makes tests highly repeatable."

Though it works great (in most cases), I am still not sure what makes it better than just observing changes in the UI, and waiting for an element to appear on screen. The implementation of these IdlingResources is much more complex than just waiting for the desired element.

Let's take [GREYUIWebViewIdlingResource](https://github.com/google/EarlGrey/blob/c1b55e6da04816c3739aef5658277495159b8ba7/EarlGrey/Synchronization/GREYUIWebViewIdlingResource.m) for example. The implementation does some pretty crazy stuff in there: injecting the RenderPassTrackerScript, iterating over the webview hierarchy... this is a pretty crazy [isIdleNow()](https://github.com/google/EarlGrey/blob/c1b55e6da04816c3739aef5658277495159b8ba7/EarlGrey/Synchronization/GREYUIWebViewIdlingResource.m#L102) function.

I know the philosophy has been derived from Espresso, but since the repo is not on github (what's up with that :/ ?), I am bringing the question up here.
I'd love to hear some of your insights, or be directed to a source where this is (or has been) discussed.

**Comment by bootstraponline** [comment]
There have been many presentations at GTAC about Espresso. Search for them on youtube.

**Comment by tirodkar** [comment]
I found this video on Idling Resources - https://www.youtube.com/watch?v=uCtzH0Rz5XU
We actually do want to make the Idling resources more event driven, so able to find changes in UI etc. Would you propose any better way to provide them by any chance?

You can get more info on Espresso here - https://google.github.io/android-testing-support-library/docs/espresso/. I believe they have their own communication channels to get in touch with them.

**Comment by tirodkar** [comment]
Closing this for now. @rotemmiz please do tell us if there was any more information that you needed.

**Comment by rotemmiz** [comment]
Thanks guys, it was helpful.
