### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#30]
It'd be nice to document how to use EarlGrey with [Carthage](https://github.com/Carthage/Carthage).

I read through [configure_earlgrey_pods](https://github.com/google/EarlGrey/blob/71b8374edd71ce3a2e5b8d7e5933112613bbabbe/Scripts/configure_earlgrey_pods.rb#L20) and my guess is that Carthage isn't supported at this time.

**Comment by tirodkar** [comment]
@bootstraponline, we have Carthage support in the roadmap and will add in in the upcoming releases. Thanks.

**Comment by bootstraponline** [comment]
It'd be nice to [share the EarlGrey scheme](https://github.com/Carthage/Carthage/tree/64cfbb9c6e82c2b7222b7bfa66a1544f0c95aec4#share-your-xcode-schemes). Currently it's possible to add EarlGrey to `Cartfile.private` and it'll pick up the 1.0.0 tag. 

> 
github "google/EarlGrey" ~> 1.0.0

Unfortunately Carthage is unable to build EarlGrey since the only shared scheme is for OCMock. [Example of sharing the scheme](https://github.com/derrh/EarlGrey/commit/1e0d76bd3aef01b1452b106d54d306b8b0ce7ef30).

**Comment by tirodkar** [comment]
@bootstraponline, would you take a look at https://github.com/google/EarlGrey/pull/65/files and check it that works? I'll send a PR out for Swift support as soon as this is in.

**Comment by bootstraponline** [comment]
thanks, I'll test it right now

**Comment by bootstraponline** [comment]
Fixed by https://github.com/google/EarlGrey/issues/65
