### ISSUE TITLE
xcpretty throwing issues with Travis Runs.

### ISSUE THREAD

**Issue by tirodkar** [google/EarlGrey#302]
``highlight_with_formatter': undefined method `include?' for nil:NilClass (NoMethodError)`

Reverting xcpretty to 0.2.2 for this.

Related issue: https://github.com/supermarin/xcpretty/issues/241

**Comment by supermarin** [comment]
xcpretty 0.2.4 fixed this

**Comment by tirodkar** [comment]
Thanks a ton for the fix @supermarin We'll revert it asap.

**Comment by khandpur** [comment]
Fixed in #306
