### ISSUE TITLE
EarlGreyExample fails to run on Xcode 8

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#309]
> Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by tirodkar** [comment]
If I'm right, this is the same issue as https://github.com/google/EarlGrey/issues/292.

**Comment by bootstraponline** [comment]
Yep, looks like it. Closing.
