### ISSUE TITLE
Killed by system

### ISSUE THREAD

**Issue by yufenglv** [google/EarlGrey#313]
The app will be killed , the log as follow:
<img width="515" alt="2016-10-19 5 48 29" src="https://cloud.githubusercontent.com/assets/1837609/19513941/611f5adc-9624-11e6-94b1-10d9de97d115.png">

Maybe EarlGrey stops and wakeups the thread too often in `- (void)grey_drainRunLoopInActiveModeForDrains:(NSUInteger)exitDrainCount`

![lalofg9cws0bn80dew_787_311](https://cloud.githubusercontent.com/assets/1837609/19514117/0a2549b6-9625-11e6-9189-b5ebe7852804.png)

**Comment by tirodkar** [comment]
Do you have any repro steps for this such as the test being run/the environment and any logs?

**Comment by khandpur** [comment]
According to the logs, wakeup's are `Triggered by thread: 268` GREYUIThreadExecutor and EarlGrey in general synchronizes with the UI / main thread; i.e. Thread 1. Have you rules out all other background threads?

**Comment by khandpur** [comment]
Closing this. Feel free to reopen if you run into this issue again.
