### ISSUE TITLE
Slow Scrolling Performance with macOS Sierra & Xcode 8

### ISSUE THREAD

**Issue by LeoNatan** [google/EarlGrey#317]
While working on [Detox](https://github.com/wix/detox), a testing suite for React Native applications, I've noticed the following issue, which at first puzzled me.

When running a test that requires scrolling to an edge (scroll to bottom, scroll to top), under macOS Sierra & Xcode 8.0, tests would fail due to timeout in my system. Running the same test on a different machine with OS X El Capitan & Xcode 7.3.1, the test succeeds. Looking at this, I first blamed the upgraded version of EarlGrey I was using compared to the other machine, however nothing in Earl Grey's code has changed regarding scrolling. 

[Video of the issue](https://vimeo.com/188150204)

I created a [demo project](https://github.com/LeoNatan/EarlGreyScrollPerformanceIssue) which demonstrates the issue.

I am not sure why this is happening, but we are seeing significant slowdowns with scrolling.

**Comment by tirodkar** [comment]
Thanks for bringing this to our attention @LeoNatan. @sid-github is working on a change https://github.com/google/EarlGrey/pull/318 that is currently related to this.

**Comment by LeoNatan** [comment]
@tirodkar Thanks for your response. What is puzzling is that the Sierra machine is actually newer and better than the other machine in that video. We are seeing some crazy results. Let me know if you need anything else from us.

**Comment by sid-github** [comment]
EarlGrey currently uses the screen refresh rate of the simulator to deliver the touches so when FPS falls so does the rate at which touches are injected, with the change that @tirodkar mentioned you must at least see the tests wrapping up faster, please let us know if thats not the case.

**Comment by LeoNatan** [comment]
I understand that, thanks. I was just wondering why the FPS is lower on the new system. Is this something you have also seen in your testing? Is the simulator subsystem slower on 10.12? If so, I will open a bug report with Apple as well.

**Comment by khandpur** [comment]
Hi @LeoNatan, could you give it another try? We recently updated the touch injection mechanism in https://github.com/google/EarlGrey/pull/318 and it was part of the 1.5.0 release.

**Comment by LeoNatan** [comment]
Hey
Will test the new version soon. 

Thanks

**Comment by khandpur** [comment]
>Is this something you have also seen in your testing?

I have encountered it before on remote test runs but I was unable to repro them locally.

>Is the simulator subsystem slower on 10.12?

My guess would be NO but I haven't upgraded to sierra yet (still on el capitan) and running EarlGrey scroll tests on Xcode 8.2 (in el capitan) I didn't experience any slowness in scrolling

**Comment by LeoNatan** [comment]
@tirodkar @sid-github @khandpur Thanks guys, seems to scroll much faster. Closing the issue.
