### ISSUE TITLE
Tests are working on simulators, but crashes instantly while trying to run on real devices.

### ISSUE THREAD

**Issue by drptbl** [google/EarlGrey#321]
Hey,

Like in title. I'm able to run tests without issues on simulators (iOS 9 and 10), but while trying to run them on real devices - I'm getting a crash as soon as main application which should be tested is opened on mobile screen.

That's the error I'm getting while trying to run on iPad with iOS 9:
![screen shot 2016-10-26 at 14 19 40](https://cloud.githubusercontent.com/assets/8177587/19725964/dc5aeea0-9b88-11e6-92a7-4450ab8f4f5f.png)

That's the error I'm getting while trying to run on iPad with iOS 10:
![screen shot 2016-10-26 at 14 24 09](https://cloud.githubusercontent.com/assets/8177587/19725966/dffb7520-9b88-11e6-994b-9306302b0a7e.png)

Can you please advice me how to solve this / what to look for?

Cheers.

**Comment by khandpur** [comment]
That's because dyld is probably complaining that it cannot find EarlGrey.framework. As per the instructions, please double check the following:
 - Have you added `DYLD_INSERT_LIBRARIES` to the scheme?
 - Is the EarlGrey.framework path under DYLD_INSERT_LIBRARIES valid?
 - Is there a copy on build phase script that is inserting EarlGrey.framework into the .app bundle?

**Comment by drptbl** [comment]
I've did whole setup again and it looks that I'm still having same issue..
```
dyld: Library not loaded: @rpath/EarlGrey.framework/EarlGrey
  Referenced from: /var/containers/Bundle/Application/771745C8-0070-4879-A2CB-6E4A78955FB7/AppName.app/AppName
  Reason: image not found
Message from debugger: Terminated due to signal 6
```
I've tried fixing it with your suggestions and what I've found in FAQ but nothing helped.

From the other side:
All my built frameworks has *.framework file + *.dSYM file. EarlGrey has no *.dSYM file. Maybe that's the cause?

**Comment by khandpur** [comment]
`@rpath/EarlGrey.framework/EarlGrey` should be `@executable_path/EarlGrey.framework/EarlGrey` as per this [screenshot](https://github.com/google/EarlGrey/blob/master/docs/images/image07.png)

**Comment by drptbl** [comment]
`@executable_path/EarlGrey.framework/EarlGrey` is parsed as `@rpath/EarlGrey.framework/EarlGrey` in XCode console. Doesn't ask me why because I have no idea.

![screen shot 2016-10-26 at 16 03 56](https://cloud.githubusercontent.com/assets/8177587/19729147/3d42e6f2-9b96-11e6-95e4-71a3c513fa10.png)

**Comment by khandpur** [comment]
Well that's very interesting. I've never encountered that issue before.
Is your App linking to EarlGrey.framework by other means (directly or indirectly). You should be able to check this under `Build Phases > Link Binaries With Libraries` of your app target.

**Comment by drptbl** [comment]
Yes my App is linking to `EarlGrey.framework`.
![screen shot 2016-10-26 at 16 12 40](https://cloud.githubusercontent.com/assets/8177587/19729378/1801cd3a-9b97-11e6-99ee-671163320b7e.png)

**Comment by khandpur** [comment]
remove that and try again.

**Comment by drptbl** [comment]
@khandpur 

Haha - it works now. I had to remove `EarlGrey.framework` from `Link Binary With Libraries`.

Thanks for help again!

**Comment by khandpur** [comment]
would be great if you want to add it to our FAQs :)

**Comment by satadip1994** [comment]
I had the same issue after removing EarlGrey.framework from the Link Binary with Libraries also the same is happening.

**Comment by tirodkar** [comment]
Did it work on removing the framework as @drptbl mentioned?

**Comment by satadip1994** [comment]
No it didn't work as per @drptbl mentioned. Anyone else faced the issue?
