### ISSUE TITLE
Interaction cannot continue because the desired element was not found

### ISSUE THREAD

**Issue by ixizi** [google/EarlGrey#342]
I want to search a element of a cell on a tableView.
and got a error:
`Error Domain=com.google.earlgrey.ElementInteractionErrorDomain Code=0 "Interaction cannot continue because the desired element was not found." UserInfo={NSLocalizedDescription=Interaction cannot continue because the desired element was not found.}`
my code:
`
[[EarlGrey selectElementWithMatcher:grey_allOf(grey_text(Name), nil)] usingSearchAction:grey_scrollInDirection(kGREYDirectionDown, 50) onElementWithMatcher:grey_accessibilityID(@"WMCCityListView.tableView")];
`

**Comment by khandpur** [comment]
Is that the complete statement? Normally such statements are chained with `performAction:` or `performAssertion:` call. Something like:

`[[[EarlGrey selectElementWithMatcher:grey_allOf(grey_text(Name), nil)] usingSearchAction:grey_scrollInDirection(kGREYDirectionDown, 50) onElementWithMatcher:grey_accessibilityID(@"WMCCityListView.tableView")] performAction:grey_tap()];
`

**Comment by ixizi** [comment]
@khandpur  it not works with `Action 'Tap' was not performed because no UI element matching` if there has too many cells on the tableview. but if no many cells and it works.

**Comment by tirodkar** [comment]
@ixizi How long does the interaction take and how many cells are we talking about? Did increasing the scroll amount help?

We have some scrolling tests in our FunctionalTests project that have 50 rows. You could increase that number and tell us in case there's a failure.

**Comment by ixizi** [comment]
@tirodkar  about thousands of cells and suspend (not scroll complete) if scroll amount set up 2000 or less.   if I set up a huge number it can scroll complete, but still not found the element and maybe I should adjust the matcher.

**Comment by tirodkar** [comment]
Do you see any "timed out" info in the error? Scrolling through thousands of cells can take a bit. How about this, try breaking the searching into smaller amounts, first try for cell 100, then 200 and so on?

**Comment by ixizi** [comment]
@tirodkar I fixed this with this code
`[[[EarlGrey selectElementWithMatcher:grey_text(realName)] usingSearchAction:grey_scrollInDirection(kGREYDirectionDown, 200) onElementWithMatcher:grey_kindOfClass([UITableView class])] performAction:grey_tap()];`

thanks for your help.
