### ISSUE TITLE
In Xcode 8.1 it is showing "error: make directory //EarlGrey.framework: Permission denied" while using with XCUITests

### ISSUE THREAD

**Issue by ankushkushwaha** [google/EarlGrey#348]
I have tried to install the framework from both i.e. Pods and Carthage but getting same error.

Xcode: 8.1
Mac OS: El Capitan 10.11.6
Target: UITests (To implement UI automation for app)
language: Objective C

**Comment by tirodkar** [comment]
Hey @ankushkushwaha, as is written in the README [here](https://github.com/google/EarlGrey#earlgrey), EarlGrey is currently an XCTest based solution. We're working on providing XCUITest support in the coming quarters. Can you please try after moving the tests to an XCTest target?

**Comment by ankushkushwaha** [comment]
Oh ok.
