### ISSUE TITLE
Update Podfile Ruby to auto install missing Gem

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#349]
See Fastlane's [install_gem_if_needed](https://github.com/fastlane/fastlane/blob/7908e2af585ce859312972bc2bd9e361f4229b86/fastlane/lib/fastlane/fastlane_require.rb#L4)

```ruby
begin
  require 'earlgrey'
rescue LoadError
  require 'rubygems/command_manager'
  Gem::CommandManager.instance[:install].install_gem('earlgrey', Gem::Requirement.default)
  require 'earlgrey'
end
```

This will auto install the EarlGrey gem instead of erroring when the dependency is missing.

**Comment by tirodkar** [comment]
Fixed in https://github.com/google/EarlGrey/pull/352
