### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#364]
[React Native](https://facebook.github.io/react-native/) is growing in popularity as it allows code sharing between Android/iOS/Web. It'd be nice if EarlGrey could support this use case since the output is native views.

**Comment by bootstraponline** [comment]
I made [a small react-native app](https://github.com/bootstraponline/react_native_automation), added a button with test ids, and then authored an EarlGrey test. It worked!

```html
<Button
  onPress={()=>{}}
  title="automation"
  testID="automation_button_id"
  accessibilityLabel="automation_button_label"
/>
```

```swift
EarlGrey.select(elementWithMatcher: grey_accessibilityLabel("automation_button_label"))
.assert(grey_sufficientlyVisible());
```

**Comment by tirodkar** [comment]
That's pretty cool. Were you able to find things that EarlGrey was not able to do by any chance?

**Comment by bootstraponline** [comment]
I'm about to go on vacation, I'll continue the investigation in January. If I run into any issues, I'll let you know.

I'm very interested to see how the upcoming EarlGrey WebView API works with react native webviews.

**Comment by bootstraponline** [comment]
I updated my [react native example](https://github.com/bootstraponline/react_native_automation). [testImage](https://github.com/bootstraponline/react_native_automation/blob/8e81edfde17dabfbc2876252b7b54220e4e89e53/button/ios/buttonTests/buttonTestEarlGrey.swift#L10) is failing to find an element by accessibility label.

React native always generates `AX=N` elements even though the `AX.id` and `AX.label` is set.

> [buttonTests.EarlGreyExampleSwiftTests testImage] : Assertion 'assertWithMatcher: matcherForSufficientlyVisible(>=0.750000)' was not performed because no UI element matching ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) && accessibilityLabel("automation_image_label")) was found.


> <RCTImageView:0x7fd30a9020d0; AX=N; AX.id='automation_image_id'; AX.label='automation_image_label'; AX.frame={{133, 319}, {148, 136}}; AX.activationPoint={207, 387}; AX.traits='UIAccessibilityTraitImage'; AX.focused='N'; frame={{133, 319}, {148, 136}}; alpha=1>


```swift
EarlGrey.select(elementWithMatcher: grey_accessibilityLabel("automation_image_label"))
.assert(grey_sufficientlyVisible());
```

**Comment by bootstraponline** [comment]
I'll submit a PR with a FAQ entry. The fix to match on label is to set the react native `accessibility: true` property.

> https://github.com/bootstraponline/react_native_automation/commit/f2286ee6a9c40260a6f52693a004999712456df6
> https://facebook.github.io/react-native/docs/accessibility.html

**Comment by bootstraponline** [comment]
https://github.com/wix/detox is interesting.
