### ISSUE TITLE
crash at untrackState method

### ISSUE THREAD

**Issue by heemoe** [google/EarlGrey#368]
![Imgur](http://i.imgur.com/HmHE0Ta.jpg)
![Imgur](http://i.imgur.com/F7SUa7L.png)
xcode 8.2
earlgrey 1.6

it happened many times and not in the same test.
this issues also in xcode 8.1 and earlgrey1.5.3.
all the tests spend about 3 hours to complete.（this test about 30 minutes.）
but if re-run the tests maybe it will be pass.

**Comment by tirodkar** [comment]
This seems like EG is waiting for a tracked objected to get untracked. Are there any console logs generated? You should be able to see what EG is waiting on there. It would also be great if you could please give us an idea of what you're testing over here for the error to be seen. Is it the same ViewController? Are there any animations / network requests etc. happening?

**Comment by ixizi** [comment]
there is another call stack.
![Imgur](http://i.imgur.com/e0rwbur.png)

it looks like this controller is dead when it is being requested.
but there is no issue running `xcodebuild test` command under the terminal .

**Comment by khandpur** [comment]
Hi @heemoe, is this still an issue with latest release (1.7.0) of EarlGrey?

**Comment by heemoe** [comment]
@khandpur After a few days I'll try this new version

**Comment by heemoe** [comment]
Fixed, thank for your help.
