### ISSUE TITLE
Pod copies incompatible EarlGrey.swift

### ISSUE THREAD

**Issue by mattdeckard** [google/EarlGrey#374]
Following the instructions in https://github.com/google/EarlGrey/blob/master/docs/install-and-run.md for CocoaPods, pod will install the 1.5.3 version of EarlGrey. Adding the `{swift: true}` option to `configure_for_earlgrey`, it seems to copy the `master` version of `EarlGrey.swift` which references a constant that did not exist in 1.5.3 (kGREYFailureHandlerKey) leading to build errors.

**Comment by tirodkar** [comment]
The `EarlGrey.swift` file that's copied into your project should come from the EarlGrey gem, for which you can specify the version. Is there another way by which you're copying EarlGrey.swift over?

**Comment by mattdeckard** [comment]
Oh that probably explains it. I just did `sudo gem install earlgrey` without specifying version.

**Comment by tirodkar** [comment]
Closing this. @mattdeckard, please re-open this if the issue persists.
