### ISSUE TITLE
Why can I only write a use case for each interface in my project? Just write the second will be error

### ISSUE THREAD

**Issue by Zhumeng223** [google/EarlGrey#433]
Why can I only write a use case for each interface in my project? Just write the second will be error

**Comment by tirodkar** [comment]
@Zhumeng223, could you illustrate with an example what is the issue that you're facing? It would be great if we could repro the issue from our side.

**Comment by tirodkar** [comment]
@Zhumeng223 feel free to re-open this along with the repro steps. Thanks!

**Comment by heemoe** [comment]
@Zhumeng223  你用中文具体描述下问题吧。测试方法名必须以test开头哦。
