### ISSUE TITLE
if UI Element is disable,how waiting for the element is enable then tap it?

### ISSUE THREAD

**Issue by vki** [google/EarlGrey#438]
the test case 
the button1 defualt is disable, wait some resouce download finished;
the button1 set enable when the resouce download finished.

so
how writer  this UI test case

**Comment by tirodkar** [comment]
What type of resource are you planning to download? If it is a network request, then EarlGrey automatically tracks with it. If you wish to enable the button, then you'd need to write a `GREYElementMatcherBlock`.

**Comment by khandpur** [comment]
IIUC, the button should be enabled after resource is downloaded so I don't think a custom GREYElementMatcher block is required here at all.

@vki EarlGrey synchronizes with network activity so it should implicitly wait for the download to finish and in the next runloop pass (after download finishes) schedule the test interaction. You shouldn't have to add any polling or sleep methods to wait for the button to become enabled.

**Comment by vki** [comment]
@khandpur but use performAction:grey_tap() is action Tap failed

**Comment by khandpur** [comment]
Do you have some logs and explain what you see when the test runs? Does it tap too early?

**Comment by vki** [comment]
@khandpur tks try clean ,build , test;   is work.
