### ISSUE TITLE
Carthage install isn't doing the complete setup

### ISSUE THREAD

**Issue by khandpur** [google/EarlGrey#442]
An EarlGrey user ran into a problem with Carthage installation. They had to follow steps outlined here to fix their issue:
https://github.com/google/EarlGrey/blob/master/docs/install-and-run.md#final-test-configuration-

It seems like the gem isn't automating everything outlined in the Final Test Configuration.

The specific problem was that they weren't able to run tests on devices because they kept getting `dyld: warning: could not load inserted library '@executable_path/EarlGrey.framework/EarlGrey' because image not found`. Manually making modification suggested in Final Test Configuration fixed it for them.

**Comment by tirodkar** [comment]
Did doing `earlgrey install -T TestTargetName` solve the issue?

**Comment by AVandelay** [comment]
The command I used was `earlgrey install --carthage --swift-version=2.3 --scheme=MyApp --target=MyAppUITests`. I was able to run UI tests on the simulator, but wasn't able to until Step 3 in the Final Test Configuration for the manual install process was done
