### ISSUE TITLE
How can I get the element which is on the window

### ISSUE THREAD

**Issue by jeff77731** [google/EarlGrey#443]
I have a view added by window

self.window.addsubView(view)

And there is a button in the view

I used this code to find the button

EarlGrey.select(elementWithMatcher: grey_accessibilityID("BTN_ID")).perform(grey_tap())

But there is no use

How can I get the button?

**Comment by khandpur** [comment]
Interesting...
Does your custom window appear in the hierarchy that's printed on failure and can you provide us with the full logs (excluding sensitive information)?

**Comment by jeff77731** [comment]
Hi

attachment is my log file

I add a viewController's view in the root window in the appDelegate

window.addSubView(viewController.view)

and there is a button in the view

But I can't get the button from "grey_accessibilityID("ACCID_END_VOIP_BTN")"

B.R.
Jeff

2017-03-06 16:15 GMT+08:00 Sundeep <notifications@github.com>:

**Comment by tirodkar** [comment]
@jeff77731 I don't think the email attachment is sent for a Github comment. Feel free to send it to us directly or drop it as a file here.

**Comment by jeff77731** [comment]
Hi

Here is the log file

2017-03-06 18:13 GMT+08:00 Aditya Atul Tirodkar <notifications@github.com>:

**Comment by jeff77731** [comment]
Hi 

Here is the log file

[log.txt](https://github.com/google/EarlGrey/files/823191/log.txt)

**Comment by jeff77731** [comment]
I found that I have an animation animate once per 0.5 seconds

So I got these error message

I can't find my element because the IdlingResources are busy

Complete Error: Error Domain=com.google.earlgrey.ElementInteractionErrorDomain Code=3 "Failed to perform action within 30 seconds." UserInfo={NSLocalizedDescription=Failed to perform action within 30 seconds., NSUnderlyingError=0x60800064a9e0 {Error Domain=com.google.earlgrey.GREYUIThreadExecutorErrorDomain Code=0 "Failed to execute block because the following IdlingResources are busy: ['performSelector changeCallingDotColor on Chatroom.VoIPViewController']
Busy resource description:
  performSelector changeCallingDotColor on Chatroom.VoIPViewController : Delayed performSelector caused the App to be in busy state for 1 seconds." UserInfo={NSLocalizedDescription=Failed to execute block because the following IdlingResources are busy: ['performSelector changeCallingDotColor on Chatroom.VoIPViewController']
Busy resource description:
  performSelector changeCallingDotColor on Chatroom.VoIPViewController : Delayed performSelector caused the App to be in busy state for 1 seconds.}}}

How can I execute my test in this case?

**Comment by khandpur** [comment]
@jeff77731 were you able to resolve your issue?

**Comment by jeff77731** [comment]
Yes, thank you very much
