### ISSUE TITLE
Capturing the text value of an element

### ISSUE THREAD

**Issue by joemantey** [google/EarlGrey#456]
This function in the FAQ for getting the string value of aN element no longer works in Swift 3. When trying to use the method, you encounter to small issues before hitting the real one
1. `inout`'s are not composed in the example the way they are in the example in Swift 3 
2. The method itself has changed in EarlGrey (small change, the compiler takes care of that for you)
3. After the fixing those minor issues you hit an error **"escaping closure can only capture inout parameters explicitly by value"**.  This is due to a swift 3 change and seems reasonable given the explanation [here](https://github.com/apple/swift-evolution/blob/master/proposals/0035-limit-inout-capture.md) 

From the [EarlGrey FAQ](https://github.com/google/EarlGrey/blob/master/docs/faq.md)
> The same technique works for extracting element attributes into variables. Here's an example of storing an element's text attribute.
> 
>    Example Usage:
> ```
>    var textValue:String = "" 
>    domainField.performAction(grey_typeText("hello.there"))
>        .performAction(grey_getText(&textValue))
> 
>  
> func grey_getText(inout text: String) -> GREYActionBlock {
>   return GREYActionBlock.actionWithName("get text",
>     constraints: grey_respondsToSelector(Selector("text")),
>     performBlock: { element, errorOrNil -> Bool in
>       text = element.text
>       return true
>     })
> }
> ```
> 

**Given one can't use inouts the same way in Swift 3, how can the text value of an element be retrieved?**

**Comment by tirodkar** [comment]
You're right, with the new syntax, we won't be able to pass in the inout parameter. We could change this to either an Objective-C method or find another way to capture the variable. Thanks for bringing this to our attention.

**Comment by tirodkar** [comment]
Unfortunately, it seems like you can't send a value type like a String as a param to the GREYActionBlock and modify it. The user would have to add a sample class object or so to do so.

**Comment by bootstraponline** [comment]
I thought I already fixed this? Here's the code we've been using:

```
// Must use wrapper class to force pass by reference in block.
// inout params won't work. http://stackoverflow.com/a/28252105
open class Element {
  var text = ""
}

/*
 *  Example Usage:
 *
 *  let element = Element()
 *
 *  domainField.performAction(grey_replaceText("hello.there"))
 *             .performAction(grey_getText(element))
 *
 *  GREYAssertTrue(element.text != "", reason: "get text failed")
 */
public func grey_getText(_ elementCopy: Element) -> GREYActionBlock {
  return GREYActionBlock.action(withName: "get text", constraints: grey_respondsToSelector(#selector(getter: UILabel.text))) { element, errorOrNil -> Bool in
        let elementObject = element as? NSObject
        let text = elementObject?.perform(#selector(getter: UILabel.text), with: nil)?.takeRetainedValue() as? String
        
        elementCopy.text = text ?? ""
        return true
    }
}

```

**Comment by khandpur** [comment]
thats exactly what we did a few minutes ago to make it work. should be in faq

**Comment by bootstraponline** [comment]
I fixed this last year and updated the FAQ. What happened?

- https://github.com/google/EarlGrey/pull/139

**Comment by bootstraponline** [comment]
oh, maybe it was never merged. new PR incoming.

**Comment by khandpur** [comment]
Ah you're right...I think this was a bad merge conflict on our end :(
sorry abt that.
