### ISSUE TITLE
Unable to Pod Install in the demo project

### ISSUE THREAD

**Issue by Simon-Kaz** [google/EarlGrey#46]
When I'm trying to run 'pod install' the following error pops up

[!] Invalid `Podfile` file: undefined method `project' for #<Pod::Podfile:0x007fe73c1918f8>. Updating CocoaPods might fix the issue.

I've tried this on multiple combinations of Cocoapods (using both stable and latest --pre) and Ruby, nothing seems to work.

**Comment by tirodkar** [comment]
Hi @Simon-Kaz, could you use `gem list cocoapods` and confirm the version of CocoaPods that you are using? Our Demo Project uses the new [1.0.0.beta syntax](http://blog.cocoapods.org/CocoaPods-1.0/) and should give a similar error if run with the stable version. Do you see different errors on running with different CocoaPods versions?

**Comment by dgallagher-venmo** [comment]
I was getting a similar error using Cocoapods 0.39. Upgrading to the latest 1.x beta of Cocoapods fixed things for me: `gem install cocoapods --pre`

**Comment by tirodkar** [comment]
@Simon-Kaz, are you still seeing this issue?

**Comment by Simon-Kaz** [comment]
Seems to work with the latest beta. Can the steps to install/guide be updated with that?

**Comment by tirodkar** [comment]
Updated the docs. Closing this for now.
