### ISSUE TITLE
Improve earlgrey gem to set up the project easily

### ISSUE THREAD

**Issue by wuhao5** [google/EarlGrey#466]
Proposing the following improvements in the earlgrey gem:

1. remove post_install, earlgrey.pod would automatically set up the target:
```ruby
target "ExampleTests" do
  pod 'EarlGrey'
end

# remove post_install
```
This will add the copy script and modify the schemes for the target "ExampleTests" only when it is a unit test bundle.

2. config xcscheme files per target
It would apply required changes to all the schemes that include the given target; currently, it targets only the given test target; sometimes, the app target can contain the test target as well.

3. copy EarlGrey.swift when the test target has a swift source code or `swift_version` is defined in podfile:
```ruby
target "ExampleTests" do
  pod 'EarlGrey'
  swift_version = '3.0'
end
```
Note if the project has `SWIFT_VERSION` or `Use Legacy Swift Language Version` defined, it will also include the swift file

**Comment by tirodkar** [comment]
How would the `the app target can contain the test target`? As in we have a target that consolidates multiple targets? We should make it clear not to have that.
