### ISSUE TITLE
Interacting with SFSafariViewController

### ISSUE THREAD

**Issue by petaren** [google/EarlGrey#499]
It would be great if there was a way to interact with a `SFSafariViewController` with EarlGrey. Since it's SFSafariViewController` when signing in using different OAuth 2 providers.

**Comment by AVandelay** [comment]
This might be addressed with this:
https://github.com/google/EarlGrey/issues/63

XCUITest is able to interact with third party authentication without having to change the code in any way

**Comment by khandpur** [comment]
@wuhao5 (adding you as you ran the actual experiment)

AFAIK, XCUITest won't help us with SFSafariViewController. We ran some experiments but we weren't able to get it to work.

**Comment by AVandelay** [comment]
For our app, the recorder wasn't able to pick up anything, but normal XCUI code was able to at least tap on `buttons[]`, `textFields[]`, and `staticTexts[]` with my quick experiment

**Comment by khandpur** [comment]
I just tried it again. And I do see that it is able to print a debugDescription of the elements and tap on some links however the recorder does not work as you mentioned.

**Comment by isnifer** [comment]
Appium is using WDA that uses XCUITest that successfully interacts with SFSafariViewController

**Comment by tirodkar** [comment]
@isnifer yes we've tested it out as well and found that we were able to interact with it using XCUITest.

**Comment by isnifer** [comment]
@tirodkar so, is there any estimate for this feature or not?

**Comment by tirodkar** [comment]
Not going to work on this in the coming few weeks at least. Feel free to send a PR, I'd love to help guide you along if needed.

**Comment by khandpur** [comment]
EarlGrey 2 is released and is able to do this!
https://github.com/google/EarlGrey/tree/earlgrey2
