### ISSUE TITLE
Is it possible to tap at point without Label 

### ISSUE THREAD

**Issue by vinodvpatil** [google/EarlGrey#501]
Is there any way i can tap/swipe using coordinates without getting label or elements?

**Comment by khandpur** [comment]
You can use a matcher that selects the window instead of a specific element or label and do a swipe or tap using `grey_tapAtPoint` or `grey_swipeSlowInDirectionWithStartPoint` or `grey_swipeFastInDirectionWithStartPoint`

**Comment by vinodvpatil** [comment]
@khandpur Thank you it worked for me, but what i was trying was a test case to tap on any of the icon on home screen and launch application. I was trying to achieve the same with following code:
 ```
- (void)testLaunchApp {

  [[XCUIDevice sharedDevice] pressButton:XCUIDeviceButtonHome];

  [[EarlGrey selectElementWithMatcher:grey_keyWindow()]

      performAction:grey_tapAtPoint(CGPointMake(95.0, 179.0))];
}
```

But it goes to home screen but does not tap on specified coordinate!!

**Comment by khandpur** [comment]
Oh..that's not possible because EarlGrey runs as the same process as the app so when you background the app, EarlGrey is "backgrounded" with it.

**Comment by vinodvpatil** [comment]
Oh Ok thank you for your time!!
