### ISSUE TITLE
Support for idling resources

### ISSUE THREAD

**Issue by dbarden** [google/EarlGrey#505]
Hi,

In our app, we have a few classes that could use custom Idling Resources to synchronise some events.

More specifically, what we have are:
- OpenGL rendered views (a map that animates the changes in location)
- a SDK that is an ObjC wrapper on top of C++ code (hence network calls are performed in C++ and don't get tracked)

Then our Espresso guys told us about the Idling Resources. And I created a couple. And they seem to work beautifully.

Problem is, since `GREYUIThreadExecutor+Internal.h` is, well, internal, I couldn't find a way to register the resource other than copying the file to our project. Which is not nice.

Could you please throw a few words on why registering an idling resource isn't public? We have a few situations where they would be pretty useful.

**Comment by khandpur** [comment]
Hi Daniel, thanks for the thorough email!

Yes, we intended not to expose `GREYUIThreadExecutor+Internal.h` until we made the idling resources `event-based`. Currently they `poll` the isIdle method as you may have noticed when you were creating the idling resources. Event-based gives us better control of when we schedule things to run on the runloop and will help alleviate the constant load on the CPU when the app isn't idle. Feel free to use `GREYUIThreadExecutor+Internal.h` to register custom idling resources but please know that when we do convert them over to event-based, you'd have to make some changes to your resource to support the new way.

Also see https://github.com/google/EarlGrey/issues/275

**Comment by dbarden** [comment]
Thanks for the clarification. That makes sense.

I'll keep an eye on that issue.
