### ISSUE TITLE
could not execute support code to read Objective-C class data in the process

### ISSUE THREAD

**Issue by HdNate** [google/EarlGrey#509]
iOS8.1   iPhone4s  throw a warning :
could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

**Comment by khandpur** [comment]
Is it device or simulator and what's the xcode version?

**Comment by HdNate** [comment]
it is device, the version of Xcode is 8.3.2

**Comment by HdNate** [comment]
the target EarlGreyFunctionalTests provided by EarlGrey also throw the issue when running on a device    of iOS 8.1.3

**Comment by khandpur** [comment]
We've never encountered this. You may enable NSZombie and try to diagnose it further as suggested on here:
https://stackoverflow.com/questions/38149650/warning-could-not-load-any-objective-c-class-information-in-swift-realm
