### ISSUE TITLE
Scrolling element into view with 'using(searchAction: )' method fails in swift

### ISSUE THREAD

**Issue by sushantchoudhary** [google/EarlGrey#513]
**I am trying to scroll a UITableView to find a UIKit element and make it interactabale using** 
 
`                EarlGrey.select(elementWithMatcher:grey_accessibilityID("fieldissuetype"))
                    .using(searchAction: grey_scrollInDirection(GREYDirection.down, 300),
                           onElementWithMatcher: grey_kindOfClass(UITableView.self))
                    .perform(grey_tap())  `
**but it doesn't scroll the table view and fails with error saying,**

`Exception Name: ConstraintFailedException
Exception Reason: Cannot perform action due to constraint(s) failure.
Exception with Action: {
  "Action Name" : "Tap",
  "Element Description" : "<JIRA.StandardFieldCell:0x7ff4b318ea00; AX=N; AX.id='fieldissuetype'; AX.frame={{0, 856}, {375, 85}}; AX.activationPoint={187.5, 898.5}; AX.traits='UIAccessibilityTraitNone'; AX.focused='N'; frame={{0, 792}, {375, 85}}; opaque; hidden; alpha=1; text=''>",
  "Failed Constraint(s)" : "interactable",
  "All Constraint(s)" : "(!(isSystemAlertViewShown) && ((respondsToSelector(isAccessibilityElement) && isAccessibilityElement) || kindOfClass('UIView')) && (enabled && !(((kindOfClass('UIView') || respondsToSelector(accessibilityContainer)) && ancestorThatMatches(!(enabled))))) && interactable)",
  "Recovery Suggestion" : "Adjust element properties so that it matches the failed constraint(s)."
}
`

**However, it works using steps in an imperative way**

`   EarlGrey .select(elementWithMatcher: grey_kindOfClass(UITableView.self)).perform(grey_scrollInDirection(.down, 300))
EarlGrey.select(elementWithMatcher: grey_accessibilityID("fieldissuetype")).perform(grey_tap())
`
**Is there something I am missing from the implementation point of view?**
**Environment**: Xcode 8.3.2, Swift version 3.1

**Comment by tirodkar** [comment]
Sushant, could you change your test to be:

```
EarlGrey.select(elementWithMatcher:grey_accessibilityID("fieldissuetype")) .using(searchAction: grey_scrollInDirection(GREYDirection.down, 300), onElementWithMatcher: grey_kindOfClass(UITableView.self)) .assert(grey_sufficientlyVisible())
```

?

And then do - 

```
EarlGrey.select(elementWithMatcher: grey_accessibilityID("fieldissuetype")).perform(grey_tap())
```

**Comment by tirodkar** [comment]
Any update @sushantchoudhary ?

**Comment by sushantchoudhary** [comment]
Hey @tirodkar , apologies for the delay. Suggested update did the trick and I was able to scroll the UITableView. Thanks a lot for the input.

**Comment by shyambhat** [comment]
Hi @tirodkar. I have the exact same issue and doing what you suggested hasn't fixed the issue for me. Do you have more ideas? Thanks.

**Comment by tirodkar** [comment]
@shyambhat, what exactly is the error that you're seeing? Feel free to open up a new Issue with the error details inside.
