### ISSUE TITLE
EarlGreyExampleSwiftTests broken in Xcode 7.3

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#53]
Do the `EarlGreyExampleSwiftTests` run correctly for you in Xcode 7.3? I have followed the readme and only the Objective C tests run correctly. Swift just has lots of errors.

<img width="407" alt="earlgrey_swift_demo" src="https://cloud.githubusercontent.com/assets/1173057/13966184/a172fbee-f047-11e5-93cb-cdbd9c4d50da.png">

**Comment by tirodkar** [comment]
@bootstraponline, thanks for bringing this to our attention. As per our investigation - the warnings mentioned in https://github.com/google/EarlGrey/issues/52 can be removed by following the suggestions - turning `__FILE__` to `#file`, `__LINE__` to `#line` and `Selector` to `#selector`.

For the build breakages, in [GREYActions](https://github.com/google/EarlGrey/blob/58fac8380f10db17fa71e39a2ea278a5138f28ec/EarlGrey/Action/GREYActions.h) and [GREYMatchers](https://github.com/google/EarlGrey/blob/4f39f5e22f23280f0fa51d8f65397e04fc80dc17/EarlGrey/Matcher/GREYMatchers.h), we were able to remove them by moving the `@end` from after the c-function definitions at the very end of the file, to right before where we define `#if !(GREY_DISABLE_SHORTHAND)`. Essentially, we need to move the C-functions outside the interface definition. Similarly with the `typedef` in [GREYElementMatcherBlock](https://github.com/google/EarlGrey/blob/fd7c83c30973e1978a5976334e12163ab8ebbfe6/EarlGrey/Matcher/GREYElementMatcherBlock.h). Please do test these out and tell us if you still see these issues.

We're planning to send in a Pull Request for these and add them to the next release framework for CocoaPods.

**Comment by bootstraponline** [comment]
Thanks for the quick response! I will try the fixes tomorrow and let you know how it goes.

**Comment by bootstraponline** [comment]
I confirm that the recommended fixes resolve the build problems. The swift tests are now passing.

<img width="320" alt="ios_tests_fixed" src="https://cloud.githubusercontent.com/assets/1173057/14022750/9ee1482e-f1b7-11e5-9093-ee618ef95bde.png">

**Comment by tirodkar** [comment]
Awesome. We'll send a fix for this along with some tests before closing this issue. Thanks for confirming this @bootstraponline.

**Comment by tirodkar** [comment]
Fixed in https://github.com/google/EarlGrey/pull/67.
