### ISSUE TITLE
Visibility issues

### ISSUE THREAD

**Issue by fernyb** [google/EarlGrey#534]
I'm trying to find an element that is displayed but doesn't meet the 75% visibility matcher.
Why is this auto added? I'd like to use 0.30 in some cases.

Where would I look to see where it's appending the matcher.

Thanks

**Comment by tirodkar** [comment]
Are you use the activation point will be available in the element with 0.3 visibility? TTBOMK, we don't check for sufficientlyVisible() when performing an action such as a tap. Could you show us what is the statement that you are trying to run?

**Comment by fernyb** [comment]
I'm looking for a cell containing some text within the cell and need to be sure its at minimum visible 20%.
So I came up with this

```ObjectiveC
id element = [CustomMatcher matcherTableViewCellContainsRegex:@"Burbank|Glendale|Sylmar|Pasadena|San Marino|North Hollywood"];
id matcher = grey_allOf([CustomMatcher matcherWithClassName:@"BusinessTableCell"], grey_minimumVisiblePercent(0.20), element, nil);

[[EarlGrey selectElementWithMatcher:matcher] assertWithMatcher:grey_minimumVisiblePercent(0.20)];
```

when it fails I notice the "Element Matcher" in the exception it contains "matcherForSufficientlyVisible(>=0.750000)"
which I didn't specify in the matcher, which I suspect is being added automatically?

```Exception
Exception with Assertion: {
  "Assertion Criteria" : "assertWithMatcher:matcherForMinimumVisiblePercent(>=0.200000)",
  "Element Matcher" : "((matcherWithClassName:BusinessTableCell) && matcherForMinimumVisiblePercent(>=0.200000) && (Table View Cell Contains Regex "Burbank|Glendale|Sylmar|Pasadena|San Marino|North Hollywood" && matcherForSufficientlyVisible(>=0.750000)))",
  "Recovery Suggestion" : "Check if element exists in the UI, modify assert criteria, or adjust the matcher"
}
```

**Comment by tirodkar** [comment]
I don't think any of these statements do a gre_sufficientlyVisible() check. Could you post `matcherTableViewCellContainsRegex` please?

**Comment by khandpur** [comment]
Yup I suspect that `matcherTableViewCellContainsRegex` is a compound matcher that's including grey_sufficientlyVisible().

**Comment by fernyb** [comment]
Dang you guys were correct, I didn't see it earlier. matcherTableViewCellContainsRegex does have grey_sufficentlyVisible().
