### ISSUE TITLE
synchronization question

### ISSUE THREAD

**Issue by cryingDream94** [google/EarlGrey#54]
How does synchronization work，such as how to judge UI loading completed?

**Comment by bootstraponline** [comment]
https://github.com/google/EarlGrey/blob/master/docs/features.md#synchronization

**Comment by tirodkar** [comment]
@cryingDream94, EarlGrey has various hooks in the app under test and tries to monitor the state of the app by which it is able to synchronize and check if actions such as UI loads are completed.

Feel free to start further discussions such as this on our [Google Group](https://groups.google.com/forum/#!forum/earlgrey-discuss). Thanks!

**Comment by cryingDream94** [comment]
@tirodkar  thank you！！O(∩_∩)O~~
