### ISSUE TITLE
How to confirm system alert like allow notification

### ISSUE THREAD

**Issue by 346285234** [google/EarlGrey#55]
If the app is installed at the first time, need to allow notification, how can I confirm it? Is someone encountered?

![thumb_img_0233_1024](https://cloud.githubusercontent.com/assets/3840794/14006487/b67bd058-f1a8-11e5-8db4-74e1d7656e41.jpg)

**Comment by bootstraponline** [comment]
https://github.com/google/EarlGrey/blob/master/docs/known-issues.md

**Comment by 346285234** [comment]
Thank you for your reply.
So EarlGrey cannot confirm the notification alert now, but what are the other means? As I am new to UI Test, can you give me some suggestions? Thanks.

**Comment by tirodkar** [comment]
@346285234, you should typically be mocking notifications and other data requests in order to prevent the dialogs from coming up. You could also accept the notification manually and re-run your tests. We experimented with using the private UIAutomation framework for this and saw we could achieve this with it. For example, for pressing the left alert button.

```
@interface SystemAlert : NSObject
- (void)tapLeftButton;
- (void)tapRightButton;
@end

@interface SystemAlert (ForMethodCompletionOnly)
+ (id)localTarget;
- (id)frontMostApp;
- (id)alert;
- (id)buttons;
@end

@implementation SystemAlert

+ (void)load {
  dlopen([@"/Developer/Library/PrivateFrameworks/UIAutomation.framework/UIAutomation" fileSystemRepresentation], RTLD_LOCAL);
}

- (void)tapLeftButton {
  id localTarget = [NSClassFromString(@"UIATarget") localTarget];
  id app = [localTarget frontMostApp];
  id alert = [app alert];
  id button = [[alert buttons] objectAtIndex:0];
  [button tap];
}

@end
```

**Comment by 346285234** [comment]
Thank you for your help. I'll have a try.

**Comment by tirodkar** [comment]
@346285234, were you able to find a solution for your issue?

**Comment by axi0mX** [comment]
@tirodkar @346285234's screenshot is not from an iOS simulator, so the code snippet above won't work (as far as I know) unless his iOS device is jailbroken, he adds entitlement com.apple.private.hid.client.event-dispatch to his app and uses fake code signing.

**Comment by tirodkar** [comment]
@346285234, were you able to test the solution out?

**Comment by bootstraponline** [comment]
thoughts on integrating with Facebook's [WebDriverAgentLib](https://github.com/facebook/WebDriverAgent/tree/master/WebDriverAgentLib) which provides alert methods, among other useful methods?

**Comment by khandpur** [comment]
Briefly looked at the implementation. It's using XCUITest APIs. Doesn't that boil down to https://github.com/google/EarlGrey/issues/63 ?

**Comment by bootstraponline** [comment]
> Briefly looked at the implementation. It's using XCUITest APIs. Doesn't that boil down to #63 ?

Kind of, the different is they reimplemented a bunch of the APIs that are broken in XCUITest and have additional features.

**Comment by bootstraponline** [comment]
I just got the Facebook lib working with EarlGrey and I think it's quite powerful.

- Built WebDriverAgentLib.framework for release
- Added to Link Binary with Libraries
- Updated bridging header:

```
#import <EarlGrey/EarlGrey.h>

#import <WebDriverAgentLib/WebDriverAgentLib.h>
#import <WebDriverAgentLib/XCUIApplication.h>
```

- Now I have full access to all the XCUITest APIs, including the Facebook versions (which are almost always better). Including the ability to deal with alerts.

```
let alert = FBAlert(application: XCUIApplication.init(privateWithPath: nil, 
                                                             bundleID: "my.app.bundle"))
alert.isPresent()
```

This is all within the unit testing target, no need for a multi-process model.

**Comment by AishSundar** [comment]
I am hitting the same issue where I am unable to automate interacting with SystemAlerts on a real device. It complains saying UIAutomation isn't enabled even though I have enabled it in settings. Looks like I need a jailbroken device to be able to change the setting.

**Comment by bootstraponline** [comment]
I ended up using [TCC.db modifications](https://github.com/calabash/run_loop/pull/391) to prevent system alerts from showing up on simulators.

**Comment by khandpur** [comment]
neat. does that work for all types of system alerts?

**Comment by bootstraponline** [comment]
I think it works for all of them? These are the ones calabash added:

```ruby
{
      :calendar => "kTCCServiceCalendar",
      :camera => "kTCCServiceCamera",
      :contacts => "kTCCServiceAddressBook",
      :microphone => "kTCCServiceMicrophone",
      :motion => "kTCCServiceMotion",
      :photos => "kTCCServicePhotos",
      :reminders => "kTCCServiceReminders",
      :twitter => "kTCCServiceTwitter"
}
```

Updating to include new services is easy.

I also figured out how to [auto configure the simulator keyboard](https://github.com/bootstraponline/run_loop/commit/984bb22474cf9fa4518d42883568bb5ef7d2a27e) to use the Facebook recommendations.

**Comment by AishSundar** [comment]
Thanks. But as you specified this also works only on a simulator. Any idea
of how to get this working on a real device (not jailbroken)?

On Wed, Jul 13, 2016 at 12:24 PM, bootstraponline <notifications@github.com>
wrote:

> I think it works for all of them? These are the ones calabash added:
>
> {
>       :calendar => "kTCCServiceCalendar",
>       :camera => "kTCCServiceCamera",
>       :contacts => "kTCCServiceAddressBook",
>       :microphone => "kTCCServiceMicrophone",
>       :motion => "kTCCServiceMotion",
>       :photos => "kTCCServicePhotos",
>       :reminders => "kTCCServiceReminders",
>       :twitter => "kTCCServiceTwitter"
> }
>
> Updating to include new services is easy.
>
> I also figured out how to auto configure the simulator keyboard
> <https://github.com/bootstraponline/run_loop/commit/984bb22474cf9fa4518d42883568bb5ef7d2a27e>
> to use the Facebook recommendations.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/EarlGrey/issues/55#issuecomment-232460120>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ATSuNSV0cCTMP1znHmsr5MsVgvbMrpspks5qVTt2gaJpZM4H3pTM>
> .
>



-- 
*Aishwarya Sundar*

**Comment by bootstraponline** [comment]
I'd expect WebDriverAgentLib to work on real non-jailbroken devices. I haven't verified that though.

**Comment by AishSundar** [comment]
It didnt not work the last time I tried to get this going on a device. So
please let me know if you are successful.

On Wed, Jul 13, 2016 at 2:13 PM, bootstraponline <notifications@github.com>
wrote:

> I'd expect WebDriverAgentLib to work on real non-jailbroken devices. I
> haven't verified that though.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/EarlGrey/issues/55#issuecomment-232488652>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ATSuNYhFxcudxDS-Zojv-yUUhwkAB3qGks5qVVUMgaJpZM4H3pTM>
> .
>



-- 
*Aishwarya Sundar*

**Comment by bootstraponline** [comment]
I only test on simulators since physical devices don't scale. If WebDriverAgentLib isn't working on physical devices then you might want to open an issue on their repo since [Facebook tests on physical devices.](https://techcrunch.com/2016/07/13/facebook-lifts-the-veil-on-its-mobile-device-lab/)

**Comment by ArielSD** [comment]
@tirodkar Which private UIAutomation framework?

**Comment by tirodkar** [comment]
@ArielSD Yes the same. It is still available in Xcode. You'd need to import the headers as is shown in the comment here.

https://github.com/google/EarlGrey/issues/55#issuecomment-200630012

I'd prefer waiting on this feature though, since we plan to have it as part of EarlGrey's next major release version, which should support XCUITest.

**Comment by ashisht99x** [comment]
### @bootstraponline I tried integrating WebDriverAgentLib into my project. But control never returns from 2nd line of code.
EarlGrey.select(elementWithMatcher:grey_accessibilityID("continue_as_guest")).perform(grey_tap())
let alert = FBAlert(application: XCUIApplication.init(privateWithPath: nil,bundleID: "com.myapp.dev"))
if alert.isPresent() {
       print("**** alert present ****")
 } else {
         print("**** alert not present ***")
}

The test completes but none of the print statements get executed. Did you also face such issue ?

**Comment by bootstraponline** [comment]
WebDriverAgentLib has changed quite a bit since last year. It wouldn't surprise me if this no longer works. Each Xcode release seems to break things. I recommend posting an issue [to their tracker](https://github.com/facebook/WebDriverAgent) and asking if this is a supported use case or not.

`UIAutomation.framework` should still work. And as @tirodkar mentioned, EG 2.0 should support this use case.

**Comment by tirodkar** [comment]
Also, this might seem a little hacky but in iOS 10+, you need to have "Privacy - Locations Usage Description" in your Info Plist or so added to be able to throw up System Dialogs. You could remove these keys for your test rig and see what the result is.

**Comment by bootstraponline** [comment]
https://github.com/wix/AppleSimulatorUtils looks interesting.

**Comment by vbutzke** [comment]
Has anyone found a consistent solution for this? Requiring someone to click on the button every time the resources are reloaded to execute tests as well as modifying production code to do so do not sound as a very good solution for automated testing... I know those are workarounds but still... This just makes UI testing kind of impossible if you're trying to follow best practices and building a consistent app where testing should not influence the core architecture. I'll keep my research but isn't there any other known solution for this?

**Comment by vbutzke** [comment]
I found a solution for automated UI testing using Appium:
https://discuss.appium.io/t/ios-alerts-handle-system-alerts-in-ios-simulator/5816/2
If it may help anyone.

**Comment by khandpur** [comment]
@vbutzke Happy that you found a solution. Sounds like what you're looking for is a pure black-box testing framework. A white-box framework like EarlGrey gives the test author more control over the AUT by running inside app under test so we usually advise using fakes (or mocks in certain cases) and encourage designing the app with testability in mind.

Just as a quick heads up -- we've already added support for handling system dialogs in EarlGrey 2.0 (based off of XCUITest) which is being developed internally until we've alpha tested it next month.

**Comment by specc** [comment]
hi @khandpur 

is handling system dialogs supported on the master branch now?

**Comment by bootstraponline** [comment]
> is handling system dialogs supported on the master branch now?

Not yet, will be in 2.0 (estimated for Q1 2018).

**Comment by specc** [comment]
@bootstraponline i see. Any work around for the moment? I see that there is a XCUITest's addUIInterruptionMonitor(withDescription:handler:)
https://developer.apple.com/documentation/xctest/xctestcase/1496273-adduiinterruptionmonitor

**Comment by khandpur** [comment]
As @bootstraponline we're planning to open source EarlGrey 2.0 very soon. In the mean time you could work around the system dialog issue either through mocking or accepting it manually on the device which you should only need to do once.

**Comment by esusslin** [comment]
Any progress with this?  Looking for a robust solution to dismissing UIAlerts for notification requests for all EarlGrey tests - any help is appreciated!

**Comment by bootstraponline** [comment]
I don't think there will be a great solution until EarlGrey 2 is released.

**Comment by khandpur** [comment]
EarlGrey 2 is released!
https://github.com/google/EarlGrey/tree/earlgrey2
