### ISSUE TITLE
Xcode build fails

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#58]
Related to #30, xcode-build fails because the signing is set to **Don't Code Sign**

```
$ xcodebuild -project EarlGrey.xcodeproj -configuration Release -target EarlGrey CONFIGURATION_BUILD_DIR=../..

=== BUILD TARGET EarlGrey OF PROJECT EarlGrey WITH CONFIGURATION Release ===

Check dependencies
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.3'

** BUILD FAILED **
```

How should people be making builds of EarlGrey? I think the setting should be set to automatic.

- `Project (EarlGrey) → Code Signing → Code Signing Identity → Automatic ...`

**Comment by tirodkar** [comment]
@bootstraponline, it would be preferable to explicitly have users code sign with their own certs. We could add a note to state this.

**Comment by bootstraponline** [comment]
> @bootstraponline, it would be preferable to explicitly have users code sign with their own certs. We could add a note to state this.

Doesn't that break Carthage because Carthage will use a [project's settings when building frameworks](https://github.com/Carthage/Carthage/issues/281)?

**Comment by bootstraponline** [comment]
Also `xcodebuild` will still fail even after code signing because the setup shell script isn't [run automatically as a PBXShellScriptBuildPhase](https://github.com/derrh/EarlGrey/commit/1e0d76bd3aef01b1452b106d54d306b8b0ce7ef3#diff-b54088b086e7c220a90849be8618a31cR859). The script is smart enough to not download already existing files. Is there a reason it's not run as part of a standard xcodebuild?

**Comment by tirodkar** [comment]
@bootstraponline, those are good points. We'll send a Pull Request to add in these changes. Thanks a lot.

**Comment by bootstraponline** [comment]
Is there a timeframe for this fix? Would it help if I submitted a pull request? We'd really like to start using EarlGrey with Swift 2.2 & Carthage.

**Comment by bootstraponline** [comment]
Fixed by https://github.com/google/EarlGrey/issues/65
