### ISSUE TITLE
Missing Swift 3.2 and Swift 4.0 Support 

### ISSUE THREAD

**Issue by mettieDie** [google/EarlGrey#580]
I updated my Project to Swift 4.0. Know CocoaPods crashed because EarlGrey doesn't support Swift 4.0

**Comment by cipherCOM** [comment]
Same on my side. `pod install` doesn't work anymore due to missing swift bundles.

**Comment by tirodkar** [comment]
I haven't looked into adding Swift 4.0 support as of now. Can you possibly point to what we would need to do for this?

**Comment by wuhao5** [comment]
did you see the error message like this: `Bundled swift missing`?

**Comment by mettieDie** [comment]
Yes exactly this error Message. The Folders for Swift 3.2 and Swift 4.0 are Missing.I Have made a Pull Request with a Fix.

**Comment by khandpur** [comment]
@mettieDie Do you plan on getting the comments in the PR resolved anytime this week? We could send another PR to solve this bug as it is preventing people from running `pod install`

**Comment by MaxJZimmermann** [comment]
@khandpur  +1 Would be great!

**Comment by mettieDie** [comment]
I think it's better to send another PR Request. I have my last exam end of the week and no time to do it. sorry.

**Comment by khandpur** [comment]
Sure, no worries @mettieDie. We will take care of this.

All the best for your last exam!

**Comment by khandpur** [comment]
Should be fixed in #591
