### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by bzarzoza** [google/EarlGrey#6]
build_universal_static_framework.sh is missing

**Comment by tirodkar** [comment]
Brandon, does this break your project? It's because an extra file is being added in the Scripts/ group of EarlGrey.xcodeproj. You could remove this Group and the error should be gone.

**Comment by bzarzoza** [comment]
Yes, it does break (non-cocoapod) integration.

**Comment by tirodkar** [comment]
@bzarzoza, we removed the script references from the project, could you confirm if you still see the issue?

**Comment by bzarzoza** [comment]
Looks good. It would be cool to see the script, too.

**Comment by tirodkar** [comment]
It was just a simple script that we were using before embedded framework were supported. Closing this for now. Do tell us if you require any more info.
