### ISSUE TITLE
No Element found if I set accessibilityId in the storyboard for iPhone 5s iOS 8.3

### ISSUE THREAD

**Issue by 346285234** [google/EarlGrey#62]
Hi,  I set the accessibilityId of a button in the storyboard, it seems in iPhone 6P it is ok, but for iPhone 5s, it was crashed.

Reproduce steps:
Device: iPhone 5s
Version: iOS 8.3
Condition: set a button accessibilityIdentifer in the storyboard.
Result: button tap event crash with the error "no element found".

**Comment by tirodkar** [comment]
Hey @346285234, could you show us the grey_description of the button so that we could get a better idea of the element itself? Also, you could try searching for the element by it's title using `grey_buttonTitle`.

**Comment by khandpur** [comment]
Hello Paul, is this still a blocker for you? Please let us know so we can triage this issue correctly.

**Comment by khandpur** [comment]
Closing this for now. Feel free to reopen it if you encounter this again.
