### ISSUE TITLE
constraint Failed Exception

### ISSUE THREAD

**Issue by anfahamid6** [google/EarlGrey#622]
My earlgrey test are working fine on iPhone simulator 6s plus but i run same test on iphone6 it throws constraintFailedException

**Comment by khandpur** [comment]
I replied to your post here: https://groups.google.com/forum/#!topic/earlgrey-discuss/1kNzYb8JdYU

Could you share the exception stack trace with us?

**Comment by anfahamid6** [comment]
Below is full exception trace

Exception Details: [

  {

    "Description" : "Cannot perform action due to constraint(s) failure.",

    "Error Domain" : "com.google.earlgrey.ElementInteractionErrorDomain",

    "Error Code" : "1",

    "File Name" : "GREYBaseAction.m",

    "Function Name" : "-[GREYBaseAction satisfiesConstraintsForElement:error:]",

    "Line" : "66",

    "TestCase Class" : "GalaxyTests.UITests",

    "TestCase Method" : "testExample"

  }

]



Bundle ID: com.bqe.Galaxy



Stack Trace: (

	0   EarlGrey                            0x000000010ea43371 -[GREYDefaultFailureHandler handleException:details:] + 1985

	1   EarlGrey                            0x000000010ea2f90b -[GREYElementInteraction grey_handleFailureOfAction:actionError:userProvidedOutError:] + 9611

	2   EarlGrey                            0x000000010ea2a899 __46-[GREYElementInteraction performAction:error:]_block_invoke + 2105

	3   EarlGrey                            0x000000010ea65c34 __59-[GREYUIThreadExecutor executeSyncWithTimeout:block:error:]_block_invoke + 68

	4   EarlGrey                            0x000000010ea61484 __77-[GREYRunLoopSpinner grey_drainRunLoopInActiveModeAndCheckCondition:forTime:]_block_invoke + 468

	5   EarlGrey                            0x000000010ea62354 __89-[GREYRunLoopSpinner grey_setupObserverInMode:withBeforeSourcesBlock:beforeWaitingBlock:]_block_invoke + 180

	6   CoreFoundation                      0x000000010dd69717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23

	7   CoreFoundation                      0x000000010dd69687 __CFRunLoopDoObservers + 391

	8   CoreFoundation                      0x000000010dd4e5e3 __CFRunLoopRun + 883

	9   CoreFoundation                      0x000000010dd4e016 CFRunLoopRunSpecific + 406

	10  EarlGrey                            0x000000010ea60f4c -[GREYRunLoopSpinner grey_drainRunLoopInActiveModeAndCheckCondition:forTime:] + 636

	11  EarlGrey                            0x000000010ea608ac -[GREYRunLoopSpinner spinWithStopConditionBlock:] + 908

	12  EarlGrey                            0x000000010ea65364 -[GREYUIThreadExecutor executeSyncWithTimeout:block:error:] + 1412

	13  EarlGrey                            0x000000010ea29426 -[GREYElementInteraction performAction:error:] + 2294

	14  EarlGrey                            0x000000010ea28ade -[GREYElementInteraction performAction:] + 62

	15  GalaxyTests                         0x0000000127a5bd4e _TFC11GalaxyTests7UITests11testExamplefT_T_ + 638

	16  GalaxyTests                         0x0000000127a660f2 _TToFC11GalaxyTests7UITests11testExamplefT_T_ + 34

	17  CoreFoundation                      0x000000010dd4bc6c __invoking___ + 140

	18  CoreFoundation                      0x000000010dd4bb40 -[NSInvocation invoke] + 320

	19  EarlGrey                            0x000000010ea1cab0 -[GREYTestCaseInvocation invoke] + 112

	20  XCTest                              0x0000000110e5d8e2 __24-[XCTestCase invokeTest]_block_invoke_2 + 491

	21  XCTest                              0x0000000110e9bf62 -[XCTestContext performInScope:] + 190

	22  XCTest                              0x0000000110e5d6e4 -[XCTestCase invokeTest] + 254

	23  EarlGrey                            0x000000010ea09181 -[XCTestCase(GREYAdditions) grey_invokeTest] + 1585

	24  XCTest                              0x0000000110e5dfb2 -[XCTestCase performTest:] + 565

	25  XCTest                              0x0000000110e5b078 __27-[XCTestSuite performTest:]_block_invoke + 300

	26  XCTest                              0x0000000110e5ac68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29

	27  XCTest                              0x0000000110e5ae4e -[XCTestSuite performTest:] + 214

	28  XCTest                              0x0000000110e5b078 __27-[XCTestSuite performTest:]_block_invoke + 300

	29  XCTest                              0x0000000110e5ac68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29

	30  XCTest                              0x0000000110e5ae4e -[XCTestSuite performTest:] + 214

	31  XCTest                              0x0000000110e5b078 __27-[XCTestSuite performTest:]_block_invoke + 300

	32  XCTest                              0x0000000110e5ac68 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 29

	33  XCTest                              0x0000000110e5ae4e -[XCTestSuite performTest:] + 214

	34  XCTest                              0x0000000110ea7a86 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40

	35  XCTest                              0x0000000110e69f27 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 574

	36  XCTest                              0x0000000110ea7925 -[XCTTestRunSession runTestsAndReturnError:] + 281

	37  XCTest                              0x0000000110e45a50 -[XCTestDriver runTestsAndReturnError:] + 254

	38  XCTest                              0x0000000110e9f86e _XCTestMain + 559

	39  CoreFoundation                      0x000000010dd69b5c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12

	40  CoreFoundation                      0x000000010dd4ee54 __CFRunLoopDoBlocks + 356

	41  CoreFoundation                      0x000000010dd4e5ee __CFRunLoopRun + 894

	42  CoreFoundation                      0x000000010dd4e016 CFRunLoopRunSpecific + 406

	43  GraphicsServices                    0x0000000114b13a24 GSEventRunModal + 62

	44  UIKit                               0x000000010f5df134 UIApplicationMain + 159

	45  Core                                0x000000010bab7e17 main + 55

	46  libdyld.dylib                       0x0000000112e3665d start + 1

)

**Comment by anfahamid6** [comment]
Any update on this issue

**Comment by khandpur** [comment]
@anfahamid6 Please join slack: https://googleoss.slack.com/messages/earlgrey
we need more info to debug this because it's not apparent why the element isn't visible to earlgrey even though the screenshot you shared shows it completely visible.

**Comment by anfahamid6** [comment]
please send me invitation on below email
anfahamid6@gmail.com

**Comment by khandpur** [comment]
There were lots of duplicate matches but due to using atIndex to pick a random non-interactable element, the constraint failed. The fix was to select only the interactable element by combining the matcher with grey_interactable:

`grey_allOfMatchers([grey_accessibilityID(“userNameTextField”), grey_interactable()])`
