### ISSUE TITLE
Support XC UI Testing

### ISSUE THREAD

**Issue by khandpur** [google/EarlGrey#63]
Integrate EarlGrey with XC UI Testing. Please follow this issue for progress updates.

**Comment by bootstraponline** [comment]
FYI Facebook has done a lot of interesting work with XC UI Testing in [WebDriverAgent](https://github.com/facebook/WebDriverAgent) by reimplementing broken APIs (like typing text) using private APIs.

**Comment by khandpur** [comment]
Will take a look over the weekend. Thanks for sharing that info @bootstraponline

**Comment by axi0mX** [comment]
Pull request in progress: https://github.com/google/EarlGrey/pull/66

**Comment by khandpur** [comment]
With EarlGrey 2 open sourced, we can finally close this bug!
https://github.com/google/EarlGrey/tree/earlgrey2
