### ISSUE TITLE
Does EarlGrey provide iframe support?

### ISSUE THREAD

**Issue by SMJ93** [google/EarlGrey#635]
Is there any support for iframes?

EarlGrey looks looks like a great solution for iOS testing, but we use an iframe in the app for payments. Can we interact with the iframe using EarlGrey?

**Comment by tirodkar** [comment]
@SMJ93 You can take a look at out [FTRLocalWebViewTest](https://github.com/google/EarlGrey/blob/master/Tests/FunctionalTests/Sources/FTRLocalUIWebViewTest.m) in case the iFrames are in a local UIWebView whose hierarchy is visible to EarlGrey. If the iFrame is in an out of process component, such as a WebView whose UI hierarchy is not visible to EarlGrey, then we won't be able to do so.

**Comment by SMJ93** [comment]
Thanks @tirodkar
