### ISSUE TITLE
Jenkins Command to Run EarlGrey tests

### ISSUE THREAD

**Issue by skycamefalling** [google/EarlGrey#64]
I was wondering what the command is to run the EarlGrey UI tests in Jenkins?

Is it the same as this?
 "-sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' test" 

I use that command for XCUITest. 

I am evaluating frameworks for my work and we need it to run in Jenkins.

Thanks!

**Comment by khandpur** [comment]
Hello,

If you use xcodebuild, the command is fairly standard. Here's one from one of our Travis runs:
`xcodebuild -project <your_project> -scheme <your_scheme> -sdk "iphonesimulator9.2" -destination "OS=8.1,name=iPhone 5" -configuration Debug ONLY_ACTIVE_ARCH=NO test`

**Comment by skycamefalling** [comment]
Perfect! Thanks!
