### ISSUE TITLE
EarlGreyExample Swift tests compile error on Xcode 9.0.1

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#650]
Repro steps:
1. `git clone git@github.com:google/EarlGrey.git`
0. `cd EarlGrey/Demo/EarlGreyExample/`
0. `pod install`
0. `open EarlGreyExample.xcworkspace/`
0. Run the `testBasicSelectionAndAction`

Error:
![earlgrey_example_2](https://user-images.githubusercontent.com/1173057/31903405-fb10510c-b7f5-11e7-87ce-09c4599ae6b1.png)

I'm seeing this error on a mac using `Xcode 9.0.1`. It doesn't reproduce on other machines. Any idea what's wrong?

**Comment by bootstraponline** [comment]
![earlgrey_example](https://user-images.githubusercontent.com/1173057/31903977-e201937c-b7f7-11e7-83f3-a2d7f6250866.png)

**Comment by tirodkar** [comment]
I recall the error with `kGREYFailureHandlerKey` from issues where EarlGrey was not correctly linked to the target where EarlGrey.swift was present. Can you check if this is the case of if EarlGrey.swift might be replicated in the wrong target?

**Comment by bootstraponline** [comment]
I'll check.

**Comment by bootstraponline** [comment]
I reinstalled Ruby with no luck. Same error. The xcode `EarlGrey.swift` and `EarlGrey.framework` look correct to me. Any other ideas?

<img width="949" alt="earglrey_debug_1" src="https://user-images.githubusercontent.com/1173057/31909481-4a117f44-b808-11e7-923c-c30af557b025.png">
<img width="699" alt="earlgrey_debug_2" src="https://user-images.githubusercontent.com/1173057/31909485-4b2d8738-b808-11e7-972b-dcb1090b9a7e.png">

**Comment by bootstraponline** [comment]
Here's the project. Run `testBasicSelectionAndAction` in the `EarlGreyExampleSwiftTests` target. Repros for me using the zip.

https://drive.google.com/file/d/0Bw73FArizy7GMzdwQnVuU0tZckk/view?usp=sharing

**Comment by bootstraponline** [comment]
I think this is the problem:

```
PODS:
  - EarlGrey (1.4.0)

DEPENDENCIES:
  - EarlGrey

SPEC CHECKSUMS:
  EarlGrey: 763d04569f96d910cf17e4fe5aa0d3842e07c0b4

PODFILE CHECKSUM: 4f1edf85a049aa56199371dd64d07fbc9f8258e1

COCOAPODS: 1.3.1
```

v1.4.0 of EarlGrey. Fixed in https://github.com/google/EarlGrey/pull/651
