### ISSUE TITLE
Waiting for viewDidAppear: call on the view controller.

### ISSUE THREAD

**Issue by bartzet** [google/EarlGrey#656]
Please find the log file below: 
[earlgrey.log](https://github.com/google/EarlGrey/files/1441904/earlgrey.log)

I'm having a problem that framework is not able to find the accessibility element on view controler and throws timeout giving the output in the logs. 

One of the messages in the log is this one:
`GREYAppStateTracker" : "Waiting for viewDidAppear: call on the view controller. Please ensure that this view controller and its subclasses call through to their super's implementation.
Waiting for UIView's draw/layout pass to complete. A draw/layout pass normally completes in the next runloop drain.`

I have checked and view controller class uses super.viewDidLoad().

I have found the way to make the test pass by adding
`        GREYConfiguration.sharedInstance().setValue(false, forConfigKey: kGREYConfigKeySynchronizationEnabled)` to the setUp method but I read it's not recommended with EarlGrey as it disables Synchronization.

but when I set this to `true` tests are failing. 

Any ideas what might be the issue?

Thanks,
Bart

**Comment by khandpur** [comment]
You checked viewDidLoad but did you also check that it calls super’s viewDidAppear

**Comment by bartzet** [comment]
Fixed!  `super.viewDidLoad(animated)` wasn't being called in `func viewDidLoad`
