### ISSUE TITLE
Import EarlGrey Problem in Swift 4

### ISSUE THREAD

**Issue by tharhtet** [google/EarlGrey#666]
I imported the EarlGrey according to documentation. But I got "No Such Module 'EarlGrey'", if you don't mind, Could you plz check my EarlGrey configuration. Thanks a lot.

[EarlGreyTesting.zip](https://github.com/google/EarlGrey/files/1529948/EarlGreyTesting.zip)

**Comment by bellebethcooper** [comment]
@tharhtet Not sure if this will help, but I recently had the same issue in Swift 4 with Quick and Nimble. I found that I could get rid of the error by selecting the Quick target and building it, then doing the same with Nimble, then selecting my app target again and building. Hope that might help!

**Comment by mark-anders** [comment]
I know this has been close, but @bellebethcooper , does EarlGrey work for you with Nimble?  It crashed for me.

**Comment by bellebethcooper** [comment]
@mark-anders I think that's unrelated to this specific issue, but no, I can't make EarlGrey work with Quick/Nimble. I think it might be because they both subclass XCTest, so you can't run one inside the other, but I'm not sure.

**Comment by mark-anders** [comment]
Ah, just checking. I had thought I might get it to work since I'm only using Nimble with XCTest, but it crashes. I had thought from your description that you had it working.

**Comment by bellebethcooper** [comment]
@mark-anders Probably too late to be useful, but I found recently in Swift Quick/Nimble tests that disabling EarlGrey analytics at the start of the Quick `spec` function let me combine EarlGrey with Quick/Nimble without crashing.

**Comment by tirodkar** [comment]
@bellebethcooper what was the crash you were seeing? The module warning should prevent you from using EarlGrey at all, so it's odd that the analytics flip would fix the problem.

**Comment by mark-anders** [comment]
@bellebethcooper - Thank you!  However, it seems like the bug I was running in to got fixed. Maybe in the upgrade to EarlGrey 1.13 or Nimble 7.1.x.

@tirodkar - the crash for me is fixed. But what was happening was that even linking with EarlGrey & Nimble would cause all tests to crash.

I'm now able to link and use both together with analytics enabled (or disabled).

@bellebethcooper - Thanks for bringing this up. I had stopped using Nimble all together, but would love to move back to it. I stopped using Quick a long time ago as it doesn't work for my style of testing.

**Comment by bellebethcooper** [comment]
@tirodkar I was getting an exception that occurred while building Quick's example groups. The error message was that I couldn't use "describe" inside an "it" block, which I wasn't doing. Removing any use of EarlGrey in my "it" block also removed the exception but I was able to use EarlGrey in my "it" blocks and add the analytics disabling line of code at the start of my Quick `spec` function and run the tests without any exceptions.

**Comment by bellebethcooper** [comment]
@tirodkar Sorry, to be more clear: I don't have the module warning anymore at all. I was just replying specifically about using EarlGrey with Quick/Nimble because it came up in the comments here. Sorry to be off-topic!
