### ISSUE TITLE
Module 'EarlGrey' has no member named 'selectElement'

### ISSUE THREAD

**Issue by ScottORLY** [google/EarlGrey#669]
Test doesn't compile with the following error: 

`Module 'EarlGrey' has no member named 'selectElement'`

Using Xcode 9.2, Swift 3.2/4.0, iOS 10 deployment target.

**Comment by tirodkar** [comment]
Are you able to find the EarlGrey.swift file in your project?

**Comment by amyjian** [comment]
I have the same problem. I could not find EarlGreys.swift in my project. This is what i have in podfile 
target 'UITests' do
    use_frameworks! # Required for Swift Test Targets only
    inherit! :search_paths # Required for not double-linking libraries in the app and test targets.
    pod 'EarlGrey'
end
could you advise what is wrong with this one ? Thanks

**Comment by Ad1991** [comment]
I have the same issue and I do not see EarlGrey.swift file in project navigator. For now, I have created a property based on the macro in Objective-C and using it.

**Comment by akshaypakanati** [comment]
I'm also facing the same issue, did anyone find the solution?

**Comment by saim80** [comment]
According to this setup guide, https://github.com/google/EarlGrey/blob/master/docs/install-and-run.md, Github installation requires manual download of that missing file, EarlGrey.swift. For cocoapods, it was supposed to be automatically set up (I guess??), but it only supports Swift 3.0 and 2.2. So, Swift 4 environment will fail to download that file anyway.

I successfully compiled the demo test by:
1. `pod install` at the demo/example directory.
2. Manually downloading EarlGrey.swift and put it into the correct location. (See the Github section of the setup guide above to find out where to download the file from.)
3. Make the minimum changes in the downloaded file due to compile errors in EarlGrey.swift
    - __assert () -> assert()

I hope this helps.

**Comment by Ad1991** [comment]
@saim80 I have installed EarlGrey via CocoaPods and I am using swift 3.0. So, I should not be required to download the file explicitly.

**Comment by saim80** [comment]
@Ad1991 Hmm, I see. I think `earlgrey_gem.yml`'s `add_swift:true` setting is meant for downloading proper Swift version file. I'm just making educated guesses here. I think something seems to be definitely off. Anyway, downloading and installing the file manually definitely helped me to run the demo tests.

**Comment by bootstraponline** [comment]
cocoapods or using the earlgrey gem directly for carthage should result in EarlGrey.swift being downloaded automatically.

**Comment by bootstraponline** [comment]
> think earlgrey_gem.yml's add_swift:true setting is meant for downloading proper Swift version file.

`add_swift:true` is the default, `earlgrey_gem.yml` is only required to opt-out of the swift file being created.

**Comment by saim80** [comment]
@bootstraponline  yup. that's the scenario. It simply didn't happen to me when I tried it using the current master branch.

**Comment by tirodkar** [comment]
Are all the users facing the problem explicitly passing `add_swift:true`? Does anyone have a simple repro case they can show with our test app? Also, please do mention what gem and cocoapod version you're using.

**Comment by NeverwinterMoon** [comment]
I haven't tried using the EarlGrey test app, but I did follow the instruction to add EarlGrey to my existing project and am experiencing the same issue with Xcode 9.2 and Swift 4.

**Comment by tirodkar** [comment]
We haven't added Swift 4 support to EarlGrey.swift yet. On converting the file, do you still see the problem?

**Comment by saim80** [comment]
@tirodkar As I noted above, there is a compatibility issue with EarlGrey.Swift when Swift 4 is used. I had to manually edit the file to make it right. Please find the post I made earlier with a link to a screenshot that shows the changes.

**Comment by szymon-kazmierczak** [comment]
I ran into the same issue as above - EarlGrey.swift file was not created when I ran pod install. xcode 9.3.1, swift (3.3 and 4.1).

What solved the issue for me was to run the gem again with the following command

```
earlgrey install -t EarlGreyExampleSwiftTests --swift --no-carthage
```

**Comment by satadip1994** [comment]
If the installation is done by cocoapods, the way to get the earlgrey.swift file is  by putting the code in Pod file as:

target 'targetName' do
pod 'EarlGrey', '~> 1.15'
end

After that do pod update in terminal in the project directory. Hope this solves your problem.
