### ISSUE TITLE
Launch arguments ?

### ISSUE THREAD

**Issue by Bastosss77** [google/EarlGrey#670]
Hi guys, can you tell me if is there a way to pass launch arguments during test like we can do with XCTest ?

` XCUIApplication *app = [[XCUIApplication alloc] init]; `
`[app setLaunchArguments:@[@"something"]]; `

Something like that 🤔

**Comment by khandpur** [comment]
Using schemes you can. It's described at length here: http://nshipster.com/launch-arguments-and-environment-variables/
