### ISSUE TITLE
Carthage 0.15.2 Failed to read file or folder at..

### ISSUE THREAD

**Issue by ninjazoete** [google/EarlGrey#68]
I am having trouble using EarlGrey with Carthage. I managed to build it with carthage by specifying master branch as source but then when I try to run it I get " Failed to read file or folder at"
which I found similar to issue https://github.com/Carthage/Carthage/issues/1096

I was looking at EarlGrey-Info.plist and did not find  `CFBundlePackageType ` property with FMWK value instead there is APPL.

Should we create another .plist for the xcscheme for Carthage or can we just change APPL to FMWK?

**Comment by bootstraponline** [comment]
APPL is [not a supported package type by Carthage](https://github.com/Carthage/Carthage/blob/63ed2b95783cd01d9b2a47414ecf8d25308fc840/Source/CarthageKit/Xcode.swift#L447) so I'm guessing we'd have to change to FMWK.

**Comment by palusik86** [comment]
+1

**Comment by bootstraponline** [comment]
Even without Carthage, I think APPL is wrong because EarlGrey is not an app.

> CFBundlePackageType (String - iOS, OS X) identifies the type of the bundle and is analogous to the Mac OS 9 file type code. The value for this key consists of a four-letter code. The type code for apps is APPL; for frameworks, it is FMWK; for loadable bundles, it is BNDL. For loadable bundles, you can also choose a type code that is more specific than BNDL if you wan
>
> https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-111321

**Comment by ninjazoete** [comment]
True, I have forked EarlGrey and commited FMWK to my master - will now try to build my tests with it. I will let you know today if it is all fine.

**Comment by rav013** [comment]
+1

**Comment by ninjazoete** [comment]
I created a pull request. Carthage works fine now. I am not sure why second file was also included into the merge. If it is my overlook just let me know.

**Comment by khandpur** [comment]
You sign the CLA and you're good to go :) Thank you for doing this!

**Comment by khandpur** [comment]
Closing this as the PR has been merged =)

Thank you once again!
