### ISSUE TITLE
TimeoutException from UITextField

### ISSUE THREAD

**Issue by yoon-boom** [google/EarlGrey#682]
Hi, I am trying to test out some EarlGrey basic futures but it kept getting me failing from checking input text after `UITextField` perform `grey_typeText` action. App has one view controller with two UITextFields. I would like to check what configuration setting that I missed. While it launches sample app, finds UITextField abd enters text correctly, however, test hangs at the checking `assertWithMatcher:grey_text(@"my@email.com")`. Testing the same code through EarlGrey's FunctionalTestRig target works just fine but no luck on my sample app. Does anybody have suggestion?

**XCode Ver**: 9.2
**Simulator**: iPad 11.2
**EarlGrey from CocoaPods**: 1.12.1
**Any animation or timer or network queue used**: Not at all. Just Pure RootViewController with two UITextFields.
**Import**:
```ObjC
#import <EarlGrey/EarlGrey.h>
#import <EarlGrey/GREYKeyboard.h>
// XCTestCase Category swizzles in +load method, since +load method loads at the runtime no need to import.
//#import <EarlGrey/XCTestCase+GREYAdditions.h>
```
**Code**:
```ObjC
- (void)testATest {
    // yes I set accessibility identifier properly.
    [[[EarlGrey selectElementWithMatcher:grey_accessibilityID(@"TypingUserName")] performAction:grey_typeText(@"my@email.com")] assertWithMatcher:grey_text(@"my@email.com")];
}
```

**Error**:
```ObjC
error: -[MySampleEarlGreyTests testATest] : Exception: TimeoutException

Exception Name: TimeoutException
Exception Reason: Timed out while waiting to perform assertion.
Exception with Assertion: {
  "Assertion Criteria" : "assertWithMatcher:((kindOfClass('UILabel') || kindOfClass('UITextField') || kindOfClass('UITextView')) && hasText('my@email.com'))",
  "Element Matcher" : "(respondsToSelector(accessibilityIdentifier) && accessibilityID('TypingUserName'))"
}

Exception Details: Error Trace: [
  {
    "Description" : "Failed to execute block because idling resources below are busy.",
    "Description Glossary" :     {
      "GREYAppStateTracker" : "Waiting for CAAnimations to finish. Continuous animations may never finish and must be stopped explicitly. Animations attached to hidden view may still be running in the background.
Waiting for gesture recognizer to detect or fail an ongoing gesture.
Waiting for UIView's draw/layout pass to complete. A draw/layout pass normally completes in the next runloop drain.

```

**Comment by tirodkar** [comment]
We've seen issues with typing on an iPad before. We have a fix for this that we will have in the next release. The current CocoaPods release is planned for early next week.

**Comment by yoon-boom** [comment]
@tirodkar Hmm. Any idea FunctionalTestRig target, same code works find on iPad Air simulator?

**Comment by tirodkar** [comment]
FunctionalTests run the code from head while the CocoaPods requires a release to be done to pick up the latest changes. That's why there's the difference in the behaviors.

**Comment by bootstraponline** [comment]
Try replace text instead of type text.

**Comment by yoon-boom** [comment]
@tirodkar I figured. Maybe I need to manually adopt project target and do the test then.
@bootstraponline Yes. it works, as well as just `greySetText` work around works too without keyboard animation.

**Comment by yoon-boom** [comment]
@tirodkar After manually drag upcoming EarlGrey.proj from `master` branch, it works with no problem. I will close this issue when fix release comes cocoapods. Thanks.

**Comment by tirodkar** [comment]
@nguyenhuy does using the source from the XcodeProj fix your issue as well?

**Comment by nguyenhuy** [comment]
Actually https://github.com/google/EarlGrey/commit/02bb30573c4d836760db1960f013b3d168c9934d fixes our issue. Thanks.

**Comment by yoon-boom** [comment]
Looks like I don't have this issue as of `EarlGrey (1.13.0)`. Closing ticket.
