### ISSUE TITLE
How to get page source of displayed screen like appium

### ISSUE THREAD

**Issue by navnathkarche** [google/EarlGrey#698]
How to get page source of displayed screen like appium

- Can I get page source for only displayed view on screen

**Comment by bootstraponline** [comment]
![image](https://user-images.githubusercontent.com/1173057/38741639-5596504c-3f08-11e8-8b88-eb721fde365a.png)
- https://github.com/google/EarlGrey/blob/master/docs/faq.md

**Comment by bootstraponline** [comment]
I think you'd have to write a custom method if you want to filter out the invisible elements.

**Comment by navnathkarche** [comment]
Thanks, @bootstraponline I have added custom method to do this.

Closing this issue as currently there is no way to handle this using EarlGrey.

**Comment by bootstraponline** [comment]
Consider posting your custom method, it may be useful to others. 😄 

I'm hoping that EarlGrey gets better tooling in this area. If we had a websocket that'd enable an inspector tool similar to uiautomatorviewer or appium desktop.

**Comment by navnathkarche** [comment]
Ohhh, I really happy to post this method but the method is not written on the iOS side. 

I have captured string hierarchy using `GreyElementHierarchy` and dump it into the file. And added a ruby script to apply the filter for visible elements. As this is our requirement.

**Comment by bootstraponline** [comment]
I think a lot of iOS teams are using Ruby with Fastlane & Cocoapods, might still be useful.

**Comment by navnathkarche** [comment]
`I'm hoping that EarlGrey gets better tooling in this area. If we had a websocket that'd enable an inspector tool similar to uiautomatorviewer or appium desktop.`
@bootstraponline  can you please elaborate this or share any link if you have how to integrate.

**Comment by bootstraponline** [comment]
Checkout how the WebDriverAgent inspector works:
- https://github.com/facebook/WebDriverAgent/tree/master/Inspector

This doesn't exist today in EarlGrey, however I'm hoping to persuade the team eventually. 🙂
