### ISSUE TITLE
EarlGrey's builds broken for over two years

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#699]
I graphed all [2,125 builds](https://github.com/cmdcolin/travigraphjs) of the EarlGrey repo on Travis CI.

![image](https://user-images.githubusercontent.com/1173057/38774577-5104f5a0-403a-11e8-8972-fd6ef7d0e83b.png)

EarlGrey released to the public in [Feburary 2016](https://testing.googleblog.com/2016/02/earlgrey-ios-functional-ui-testing.html). EarlGrey is still not stable two years later.

What is the plan for providing a stable public CI for EarlGrey? 

I'm happy to help evaluate solutions.

**Comment by tirodkar** [comment]
Thanks for the graph @bootstraponline. We are aware of the failing tests (mostly related to webview support). The core EarlGrey tests have been stable on Travis though, with any issues surfaced being genuine bugs we had to fix, so we are getting some good signals from the CI tool.

We are looking for better CI tools as well. We'll definitely send a wider message out / comment on this issue as soon as we have any tentative solutions to test.

**Comment by bootstraponline** [comment]
The builds are passing now on bitrise. 😄
