### ISSUE TITLE
How is it going with EarlGrey 2.0

### ISSUE THREAD

**Issue by tabynbayev** [google/EarlGrey#721]
According to the roadmap we already are expected to have EarlGrey 2.0 ready to use. Could you provide some information how it's going with 2.0 version?

**Comment by tirodkar** [comment]
We're currently working on the open-sourcing. We'll send a larger update on the [Google Group](https://groups.google.com/forum/#!forum/earlgrey-discuss) once the release is ready. We'd be happy to provide more information on any particular feature you're looking for.

**Comment by tabynbayev** [comment]
1) Is it going to be black box testing? Does it mean that it will omit features based on a source code exposing?
2) Is there any deadline for release?

**Comment by tirodkar** [comment]
1. EarlGrey 2.0 will not be black boxed. Calling app methods won't be as straightforward as in EarlGrey 1.0, but we're trying to ensure the best experience possible.

2. We'll let you know as soon as we push the new release out.

**Comment by tabynbayev** [comment]
Well, EarlGrey 2.0 will be built upon XCUITest, right?
Does it make sense now to begin covering our iOS Apps with EarlGrey? Or its API will be significantly change after 2.0 release?

**Comment by werediver** [comment]
`XCUITest` is quite restrictive. It can only run in a separate process (trying to run it in the main app context leads to a deadlock; running in a background thread is not supported either), it does not provide direct access to `UIView` and/or `UIViewController` objects (only via `XCUIElement` representation).

It's a perfect match for black box testing, but EarlGrey at the moment _does not enforce_ black-boxing the system under test, thus moving to `XCUITest` would be a huge conceptual move; but also a complete rewrite of the testing API implementation.

To me it seems unlikely for EarlGrey 2.0 to be built on top of `XCUITest`. But what is the official answer?

**Comment by tirodkar** [comment]
@tabynbayev We'll release the source with a sample project soon and you should be able to estimate the change required for your test suites. 

@werediver We're aware of the multi-process nature of XCUITest. While it make white-boxing a bit more tedious, it does allow EarlGrey out of process interactions. Stay tuned for more details.

**Comment by tabynbayev** [comment]
Thank you! You are awesome, guys =)

**Comment by tirodkar** [comment]
BTW - EG 2 is available [here](https://github.com/google/EarlGrey/tree/earlgrey2)
