### ISSUE TITLE
The Json file EarlGray.podspec.json is invalid

### ISSUE THREAD

**Issue by ob** [google/EarlGrey#727]
```
$ /export/apps/python/3.7/bin/python3
Python 3.7.0b3 (default, Mar 30 2018, 11:14:32) 
[Clang 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> with open('EarlGrey.podspec.json', 'r') as f:
...     j = json.load(f)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/export/apps/python/3.7/lib/python3.7/json/__init__.py", line 300, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/export/apps/python/3.7/lib/python3.7/json/__init__.py", line 355, in loads
    return _default_decoder.decode(s)
  File "/export/apps/python/3.7/lib/python3.7/json/decoder.py", line 340, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/export/apps/python/3.7/lib/python3.7/json/decoder.py", line 358, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> 
```

If I remove the comments and try that again:

```
$ /export/apps/python/3.7/bin/python3
Python 3.7.0b3 (default, Mar 30 2018, 11:14:32) 
[Clang 7.3.0 (clang-703.0.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> with open('EarlGrey.podspec.json', 'r') as f:
...     j = json.load(f)
... 
>>> 
```

AFAIK, Json files can't have comments, and the top part of the file is full of comments.

**Comment by tirodkar** [comment]
Hey @ob what command did you run to see this? We didn't see this during our last pod lints.

**Comment by ob** [comment]
Sorry, I messed up the original description. I just updated it. I'm reading the file with Python 3's standard json library.

**Comment by tirodkar** [comment]
I see. We do need license info for our Podspec, and it seems like the CocoaPods lints are fine with this. Is this blocking you in any way?

**Comment by bootstraponline** [comment]
Probably it's better to not have comments in JSON since technically that's not valid JSON.

- https://jsonlint.com/

**Comment by ob** [comment]
It's making an automated system for importing Pods break. The system is written in Python, which doesn't support comments in JSON files. I checked with Ruby and Ruby's `json` library is fine with comments. I suspect that's why you didn't see it. FWIW, [RFC 8259](https://tools.ietf.org/html/rfc8259) doesn't seem to allow for comments. 

It seems the standard practice is to add a key with the license info...

**Comment by tirodkar** [comment]
We already have a license key. I'll check if we can get it removed.

**Comment by ob** [comment]
@tirodkar is it possible to remote the comments?

**Comment by tirodkar** [comment]
Yeah, I removed the comments. I'll send a PR soon.

**Comment by ob** [comment]
I just checked and this is fixed on master. Thanks!
