### ISSUE TITLE
EarlGrey.framework location in the App Bundle

### ISSUE THREAD

**Issue by umutuzgur** [google/EarlGrey#734]
Hi there,

I was wondering why EarlGrey.framework is put right in the Main Bundle folder. This is a bit abnormal because Apple expects .frameworks extensions to be in Frameworks folder for codesigning. This can be also seen in the technical note below in table 2-5.

https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1

The content I'm referencing here is basically this section:

`(Required) Contains the application’s standalone executable code. Typically, this directory contains only one binary file with your application’s main entry point and statically linked code. However, you may put other standalone executables (such as command-line tools) in this directory as well.`

I would be really happy if someone could explain me that. Thanks a lot

**Comment by tirodkar** [comment]
We just need it to be injected into the app bundle and then use DYLD_INSERT_LIBRARIES to inject it into the app. Feel free to send a PR to change the paths, I don't think there should be any issues with it.

**Comment by khandpur** [comment]
It's been that way from the beginning before embedded frameworks were officially supported by Apple. Are you running into issues with codesigning it because it's not under Frameworks folder? And is it due to cocoapods?

If you decide to change it, you'd have to change it in multiple locations thoughout our xcode projects, cocoapods, etc.

**Comment by umutuzgur** [comment]
It haven't had a problem with codesigning. My concern is more towards resigning. Resigning services might fail resigning EarlGrey tests due to the framework being in the App Bundle Folder. This is not a problem with XCode since the extra frameworks to be copied and to be signed are specified in the settings and due to that, XCode knows what extra to sign. However, I don't think this would work with fastlane for example.

If you follow this line, you will see that they expect the frameworks to be in the framework folder
https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh#L540 

Thank you for your answers btw

**Comment by khandpur** [comment]
Understood. Since we're preparing open sourcing for EarlGrey 2.0, we'll address it there and leave it the way it is for EarlGrey 1.0
