### ISSUE TITLE
Xcode 10 + Carthage: Earlgrey not building.

### ISSUE THREAD

**Issue by jazz-mobility** [google/EarlGrey#748]
HI,

I am trying to add Earlgrey using Carthage but it is not able to build. See error below.

`*** Building scheme "EarlGrey" in EarlGrey.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/j.singh/Desktop/Source_Code/Foodora_Git/mob-b2c-ios/Carthage/Checkouts/EarlGrey/EarlGrey.xcodeproj -scheme EarlGrey -configuration Release -derivedDataPath /Users/j.singh/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A254a/EarlGrey/1.15.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/kx/vmm2sn395s92tt_tm4l5vdyndh0b3t/T/EarlGrey SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/j.singh/Desktop/Source_Code/Foodora_Git/mob-b2c-ios/Carthage/Checkouts/EarlGrey)`

Xcode - Version 10.0 (10A254a)
Earlgrey - 1.15.0
Carthage - 0.30.1

`carthage bootstrap --platform iOS --no-use-binaries` and `carthage update --platform iOS --no-use-binaries` always fails.
But running `carthage build --platform iOS --no-use-binaries` after above command works.

I can't use it as a solution for CI :(

**Comment by st3fan** [comment]
@jazz-mobility did turning off the new build system work?

**Comment by tirodkar** [comment]
From https://github.com/google/EarlGrey/issues/740, it looks like turning off the new build system fixes the issue termporarily. It looks like the build system doesn't pick up the installation scripts for Fishhook and OCHamcrest immediately.

**Comment by st3fan** [comment]
Here is a change I made in my local fork to get things building in CI ...

https://github.com/st3fan/EarlGrey/commit/ce90f3ffabfb9cfcda73bcbcdd8844c47fede04e

**Comment by PawelPalkaPerform** [comment]
Will be there fix for this soon?

**Comment by tirodkar** [comment]
@PawelPalkaPerform, does @st3fan's change work for you?

**Comment by ethanjdiamond** [comment]
@st3fan's change worked for me. Can you merge it into the main project?

**Comment by PawelPalkaPerform** [comment]
Yes please.

**Comment by drzajwo** [comment]
I had this problem and fixed it by checking if provisioning profile/team/signing cert is properly set in App/General

**Comment by thedevme** [comment]
Is there a solution for this? Having trouble getting this to work keeps failing on install.

**Comment by jazz-mobility** [comment]
Sorry for the late response guys, I end up using Earlgrey from pods as My project is still using pods and Carthage both.
