### ISSUE TITLE
EarlGrey 2.0 Helper Bundle (Swift) can't find XCTest.h

### ISSUE THREAD

**Issue by jn000** [google/EarlGrey#759]
I set up EarlGrey 2.0 according to [setup.md](https://github.com/google/EarlGrey/blob/earlgrey2/docs/setup.md).

[In Helper Bundle Section](https://github.com/google/EarlGrey/blob/earlgrey2/docs/swift-white-boxing.md), I added Bridging-Header for Helper Bundle, then I got compile error.
Error message is `'XCTest/XCTest.h' file not found` in XCTestCase+GREYSystemAlertHandler.h.

How can i resolve this issue.

I tried to find what is different to [FunctionalTests HostDOCategoriesSwift](https://github.com/google/EarlGrey/tree/earlgrey2/Tests/FunctionalTests) with my bundle.

* Build Settings
  * Always Embed Swift Standard Libraries
    * FunctionalTests is `Yes`
  * Enable Bitcode
    * FunctionalTests is `No`

I fix these, but i can't resolve the issue...

**Comment by tirodkar** [comment]
You should not link TestLib to the Helper Bundle. Only have a weak dependency on the AppFramework. Expose the Headers for the TestLib to that target.

**Comment by zeero** [comment]
@tirodkar 
Thank you for your reply.

I don't link TestLib in Helper Bundle. My configuration at Build Phase is below.

<img width="1406" alt="2018-10-05 10 44 17" src="https://user-images.githubusercontent.com/105469/46511897-4b5a8400-c88c-11e8-8d90-05631ea82d6e.png">

> Expose the Headers for the TestLib to that target.

How can i configure that?

My Build Setting configuration for Helper Bundle is below.

User Header Search Path ('EarlGrey' directory is downloaded git repository.)
<img width="961" alt="2018-10-05 10 45 39" src="https://user-images.githubusercontent.com/105469/46512065-0d119480-c88d-11e8-8ca5-c25a67a9e651.png">

Bridging Header
<img width="701" alt="2018-10-05 10 46 00" src="https://user-images.githubusercontent.com/105469/46512122-44804100-c88d-11e8-8ea8-9d92c660e21a.png">

**Comment by jn000** [comment]
@tirodkar 
Thank you for your reply.

I don't link TestLib in Helper Bundle. My configuration at Build Phase is below.

<img width="1406" alt="2018-10-05 10 44 17" src="https://user-images.githubusercontent.com/105469/46511897-4b5a8400-c88c-11e8-8d90-05631ea82d6e.png">

> Expose the Headers for the TestLib to that target.

How can i configure that?

My Build Setting configuration for Helper Bundle is below.

User Header Search Path ('EarlGrey' directory is downloaded git repository.)
<img width="961" alt="2018-10-05 10 45 39" src="https://user-images.githubusercontent.com/105469/46512065-0d119480-c88d-11e8-8ca5-c25a67a9e651.png">

Bridging Header
<img width="701" alt="2018-10-05 10 46 00" src="https://user-images.githubusercontent.com/105469/46512122-44804100-c88d-11e8-8ea8-9d92c660e21a.png">

**Comment by tirodkar** [comment]
I'm surprised the XCTest import is failing here. Hmm, this is being copied correctly to only the tests right?

**Comment by tirodkar** [comment]
I think I know what the issue is. I'm guessing that you're handling an alert in your Helper Bundle.

The Helper Bundle is an app side component. There is no `XCTest` at all within that component. The correct solution here would be to move the System Handler code to your test side. It should build just fine after.

**Comment by jingyul** [comment]
@tirodkar Not directly, the error is pointing to TestLib/AlertHandling as you mentioned. It's not from my source code. But I don't know how this dependency was created.

**Comment by tirodkar** [comment]
Is it in the bridging header? Try removing it from there.

**Comment by jingyul** [comment]
No, this is what is in the bridging header:

**Comment by jingyul** [comment]
#import "AppFramework/Action/GREYAction.h"
#import "AppFramework/Action/GREYActionBlock.h"
#import "AppFramework/Action/GREYActions.h"
#import "AppFramework/Matcher/GREYElementMatcherBlock.h"
#import "CommonLib/DistantObject/GREYHostApplicationDistantObject.h"
#import "CommonLib/Matcher/GREYMatcher.h"
#import "TestLib/AlertHandling/XCTestCase+GREYSystemAlertHandler.h"
#import "TestLib/EarlGreyImpl/EarlGrey.h"

**Comment by tirodkar** [comment]
Remove `#import "TestLib/AlertHandling/XCTestCase+GREYSystemAlertHandler.h"`
I'm sending a PR to update this.

**Comment by jingyul** [comment]
I did. But still get the same error, but this time it is from TestLib/EarlGreyImp/EarlGrey.h

**Comment by tirodkar** [comment]
Remove all TestLib imports from your Helper Bundle.

**Comment by jingyul** [comment]
Build Success! Thanks @tirodkar

**Comment by tirodkar** [comment]
Clarification added https://github.com/google/EarlGrey/pull/763. Feel free to comment if there's something that's unclear.

**Comment by jingyul** [comment]
Wait, more questions, now the individual build on the helper bundles is good. But when run a UITest test case, it says that BuildEarlGreyHelperBundles:Failed on top of the XCode window. There is no more details. No red dot.

**Comment by tirodkar** [comment]
Can you ping me on Slack and we can continue this there?

**Comment by jingyul** [comment]
ok, thanks!

**Comment by jn000** [comment]
@tirodkar 
thank you so much your kind support.
i build successfully.

my bridging header for helper bundle is below.

```
#import "AppFramework/Action/GREYAction.h"
#import "AppFramework/Action/GREYActionBlock.h"
#import "AppFramework/Action/GREYActions.h"
#import "AppFramework/Matcher/GREYElementMatcherBlock.h"
#import "CommonLib/DistantObject/GREYHostApplicationDistantObject.h"
#import "CommonLib/Matcher/GREYMatcher.h"
```

i close this issue.
