### ISSUE TITLE
EarlGrey 1.15 - Unable to use forked version in my own project, license missing when running pod update

### ISSUE THREAD

**Issue by szymon-kazmierczak** [google/EarlGrey#768]
I'm trying to use the forked version of this project to test a few changes that I introduced.

After cloning the project and making changes, I made sure the project compiles.

Since my personal project uses Cocoapods, I added my fork with the following line in the podfile.
```pod 'EarlGrey', :path => '~/code/EarlGrey', :commit => '9d519e7aaa3022199a1fb1264be7e927bcd4cd44'```

After running the pod update/pod install, I got an error stating that the license is missing. 

```
[!] A license was specified in podspec `EarlGrey` but the file does not exist - ~/code/EarlGrey/EarlGrey/LICENSE

[!] Unable to read the license file `EarlGrey/LICENSE` for the spec `EarlGrey (1.15.0)`

[!] Unable to read the license file `EarlGrey/LICENSE` for the spec `EarlGrey (1.15.0)`
```

Am I missing some steps in the process? should I release my own version of EG first? (1.16? )

**Comment by tirodkar** [comment]
Is this evinced by a custom flag for pods that you're using? I've seen this in `pod lib lint` in the past, but it hasn't been a blocker.

**Comment by szymon-kazmierczak** [comment]
I wouldn't know, I'm not super familiar with pods :(

My goal is to fork earlgrey 1.x and use that within my project to verify that the changes I made are valid - what would be the steps to achieve that? The license could indeed be just a warning and not a blocker.

**Comment by tirodkar** [comment]
The warnings have been present since we initially released as we were zipping up the pod with a LICENSE file inside. We could mitigate this issue as we release EarlGrey 2.0 to pods. I'd suggest going ahead with the release for now.
