### ISSUE TITLE
Build Failed -  Semantic Issue

### ISSUE THREAD

**Issue by vhala-fk** [google/EarlGrey#77]
The EarlGrey project is not building. [Xcode ver 6.4(6E35b)]
Steps:
1. Clones EarlGrey repo.
2. Ran 'setup-earlgrey.sh'.
3. Opened EarlGrey.xcodeproj and tried building the project.

Error:
GREYTapAction.m - Semantic Issue Method override for the designated initializer of the superclass '-initWithName:constraints:' not found

![image](https://cloud.githubusercontent.com/assets/11550824/14879465/098f3cd0-0d47-11e6-9d79-a7ee3861ae38.png)

**Comment by bootstraponline** [comment]
Use Xcode 7.3.

**Comment by vhala-fk** [comment]
thanks will upgrade my OS and try.

**Comment by vhala-fk** [comment]
Yes, works in the latest Xcode version. 
Thanks, closing.
