### ISSUE TITLE
could not load inserted library '@executable_path/EarlGrey.framework/EarlGrey'

### ISSUE THREAD

**Issue by drzajwo** [google/EarlGrey#785]
Hi,
I'm about to start using EarlGrey for the first time, because writing tests in XCUI doesn't fit me cuz app under tests is hybrid web app.
I've spended whole day trying to run framework in my project.

Env:
Xcode 10.1
EarlGrey 1.15.0

Firstly, I was trying to run tests by previously imported EarlGrey by Carthage, had an error like in title, so i decided to add it in 3rd way using project from github.
I made all required steps from [GitHub installation instruction](https://github.com/google/EarlGrey/blob/master/docs/install-and-run.md#github-installation) except point 2 of step 4, because I wasn't able to build project with error "Invalid configuration: sets both USES_XCTRUNNER and TEST_HOST"
Actual Build Phases section looks like this:
<img width="1100" alt="screen shot 2019-01-09 at 13 10 45" src="https://user-images.githubusercontent.com/15889364/50898613-02c4e080-1410-11e9-9ef2-8094d24cac2b.png">
App is building properly and while trying to run on real device i'm getting:
`dyld: warning: could not load inserted library '@executable_path/EarlGrey.framework/EarlGrey' into hardened process because image not found
2019-01-09 12:56:38.127066+0100 MobileClientTests-Runner[446:36250] Running tests...
2019-01-09 12:56:38.181274+0100 MobileClientTests-Runner[446:36250] The bundle “MobileClientTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2019-01-09 12:56:38.181382+0100 MobileClientTests-Runner[446:36250] (dlopen_preflight(/var/containers/Bundle/Application/5DC709F4-53A9-4FAD-ABEA-8B219C22CF70/MobileClientTests-Runner.app/PlugIns/MobileClientTests.xctest/MobileClientTests): Library not loaded: @rpath/EarlGrey.framework/EarlGrey
  Referenced from: /var/containers/Bundle/Application/5DC709F4-53A9-4FAD-ABEA-8B219C22CF70/MobileClientTests-Runner.app/PlugIns/MobileClientTests.xctest/MobileClientTests
  Reason: image not found)`
I've checked and EarlGrey.framework is present in myapp.app (which is "Mobile Client.app")

I was researching internet and issues attached to this project and didn't found suitable solution... Any ideas?

**Comment by tirodkar** [comment]
EarlGrey 1.0 does not support XCUITest. Please look at EarlGrey 2.0 for UI Test support.

https://github.com/google/EarlGrey/tree/earlgrey2

**Comment by drzajwo** [comment]
Thanks for very quick response, will check it now and give feedback.

**Comment by drzajwo** [comment]
Well, it seems to work fine using [this setup instruction](https://github.com/google/EarlGrey/blob/earlgrey2/docs/setup.md) ;) Thank you for your help @tirodkar, have a nice day!

**Comment by IcyW** [comment]
> this setup instruction

Maybe it is awkward.. I don't know where can I find the `libTestLib.a`?

>  add libTestLib.a into the "Link Binary With Libraries" section.
