### ISSUE TITLE
EarlGrey 2.0 | EDOClientService should have failed at connection time

### ISSUE THREAD

**Issue by ElliottHeath** [google/EarlGrey#786]
I've only seen this once so far, but based on the error message, this is an EG bug.

<details> <summary>EDOClientService.m:158: failed: caught "NSInternalInconsistencyException", "Retry creating channel failed. This failure should happen at connection time instead of reaching here.</summary>

> Test Suite 'SettingsTest' started at 2019-01-09 15:14:21.376
Test Case '-[XyzUITests.SettingsTest testFeedbackButtonTakesUserToFeedbackPage]' started.
    t =     0.01s Start Test at 2019-01-09 15:14:21.382
    t =     0.03s Set Up
    t =     0.03s     Open com.company.ZyXo
    t =     0.04s         Launch com.company.ZyXo
    t =     0.05s             Terminate com.company.ZyXo:45710
2019-01-09 15:14:21.580538-0800 XyzUITests-Runner[45519:303090] The channel (0x600002ab2ac0) with port 59375 is closed
    t =     5.50s             Wait for com.company.ZyXo to idle
2019-01-09 15:14:38.645318-0800 XyzUITests-Runner[45519:305680] The edo channel <EDOSocketChannel: 0x600002ac7e80> is broken.
2019-01-09 15:14:48.651082-0800 XyzUITests-Runner[45519:305681] The edo channel <EDOSocketChannel: 0x600002ac2200> is broken.
2019-01-09 15:14:48.651680-0800 XyzUITests-Runner[45519:302459] *** Assertion failure in +[EDOClientService sendRequest:port:], /Users/Elliott/workspace/AlexaAutoLabsiOS/src/AlexaAutoLabsiOS/EarlGrey/eDistantObject/Service/Sources/EDOClientService.m:159
    t =    27.48s     Assertion Failure: EDOClientService.m:158: failed: caught "NSInternalInconsistencyException", "Retry creating channel failed. This failure should happen at connection time instead of reaching here."
(
	0   CoreFoundation                      0x000000010c9e91bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010bf87735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c9e8f42 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010b98a877 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   XyzUITests               0x00000001245e32db +[EDOClientService sendRequest:port:] + 2267
	5   XyzUITests               0x00000001245e1dc1 +[EDOClientService classObjectWithName:port:] + 145
	6   XyzUITests               0x00000001245b32a3 +[GREYMatchers forwardingTargetForSelector:] + 147
	7   CoreFoundation                      0x000000010c9eda02 ___forwarding___ + 210
	8   CoreFoundation                      0x000000010c9efda8 _CF_forwarding_prep_0 + 120
	9   XyzUITests               0x00000001245b7a3f grey_accessibilityID + 63
	10  XyzUITests               0x000000012459a971 $S21XyzUITests21CommonEGVerificationsC22canFindAccessibilityId07visibleJ0SbSS_tFZ + 65
	11  XyzUITests               0x00000001245aec5f $S21XyzUITests15ScreenDetectionC010getCurrentE0AA0E0OyFZ + 95
	12  XyzUITests               0x00000001245ad89a $S21XyzUITests11ScreenGraphC014searchNodesForE033_1FDEED5A128BDCA1A973BCEFE0888E64LL07desiredE011currentPathSayAA0eR0VSgGAA0E0O_AItF + 346
	13  XyzUITests               0x00000001245ad274 $S21XyzUITests11ScreenGraphC010navigateToE007desiredE0SbAA0E0O_tF + 84
	14  XyzUITests               0x00000001245a3b41 $S21XyzUITests12SettingsTestC5setUpyyF + 177
	15  XyzUITests               0x00000001245a3be4 $S21XyzUITests12SettingsTestC5setUpyyFTo + 36
	16  XyzUITests               0x00000001245b762e -[XCTestCase(GREYTest) grey_setUp] + 94
	17  XCTest                              0x000000010b844c74 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
	18  XCTest                              0x000000010b844b91 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
	19  XCTest                              0x000000010b7ecf61 __24-[XCTestCase invokeTest]_block_invoke_3 + 89
	20  XCTest                              0x000000010b854d77 -[XCTContext _runActivityNamed:type:block:] + 245
	21  XCTest                              0x000000010b7f57d6 -[XCTestCase startActivityWithTitle:type:block:] + 218
	22  XCTest                              0x000000010b7f59b3 -[XCTestCase startActivityWithTitle:block:] + 60
	23  XCTest                              0x000000010b7ecadf __24-[XCTestCase invokeTest]_block_invoke + 342
	24  XCTest                              0x000000010b84ab7e -[XCUITestContext performInScope:] + 248
	25  XCTest                              0x000000010b7ec8ce -[XCTestCase testContextPerformInScope:] + 98
	26  XCTest                              0x000000010b7ec97c -[XCTestCase invokeTest] + 137
	27  XyzUITests               0x00000001245b7116 -[XCTestCase(GREYTest) grey_invokeTest] + 1526
	28  XCTest                              0x000000010b7ee4b7 __26-[XCTestCase performTest:]_block_invoke_2 + 43
	29  XCTest                              0x000000010b844c74 -[XCTestCase(Failures) performFailableBlock:testCaseRun:shouldInterruptTest:] + 57
	30  XCTest                              0x000000010b844b91 -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 96
	31  XCTest                              0x000000010b7ee3ce __26-[XCTestCase performTest:]_block_invoke.330 + 88
	32  XCTest                              0x000000010b85544b +[XCTContext runInContextForTestCase:block:] + 225
	33  XCTest                              0x000000010b7edafd -[XCTestCase performTest:] + 675
	34  XCTest                              0x000000010b8311a2 -[XCTest runTest] + 57
	35  XCTest                              0x000000010b7e8ccb __27-[XCTestSuite performTest:]_block_invoke + 365
	36  XCTest                              0x000000010b7e84a3 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	37  XCTest                              0x000000010b7e8766 -[XCTestSuite performTest:] + 296
	38  XCTest                              0x000000010b8311a2 -[XCTest runTest] + 57
	39  XCTest                              0x000000010b7e8ccb __27-[XCTestSuite performTest:]_block_invoke + 365
	40  XCTest                              0x000000010b7e84a3 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	41  XCTest                              0x000000010b7e8766 -[XCTestSuite performTest:] + 296
	42  XCTest                              0x000000010b8311a2 -[XCTest runTest] + 57
	43  XCTest                              0x000000010b7e8ccb __27-[XCTestSuite performTest:]_block_invoke + 365
	44  XCTest                              0x000000010b7e84a3 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	45  XCTest                              0x000000010b7e8766 -[XCTestSuite performTest:] + 296
	46  XCTest                              0x000000010b8311a2 -[XCTest runTest] + 57
	47  XCTest                              0x000000010b860e86 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 171
	48  XCTest                              0x000000010b860fa7 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke.80 + 68
	49  XCTest                              0x000000010b800bc1 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 585
	50  XCTest                              0x000000010b860bfa -[XCTTestRunSession runTestsAndReturnError:] + 623
	51  XCTest                              0x000000010b7cd6b6 -[XCTestDriver runTestsAndReturnError:] + 422
	52  XCTest                              0x000000010b8519cd _XCTestMain + 1478
	53  XyzUITests-Runner        0x000000010b4ec02d -[_XCTRunnerAppDelegate applicationWillResignActive:] + 0
	54  XyzUITests-Runner        0x000000010b4ebf2b _XCTRunnerRunTests + 0
	55  CoreFoundation                      0x000000010c94e62c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	56  CoreFoundation                      0x000000010c94dde0 __CFRunLoopDoBlocks + 336
	57  CoreFoundation                      0x000000010c948654 __CFRunLoopRun + 1284
	58  CoreFoundation                      0x000000010c947e11 CFRunLoopRunSpecific + 625
	59  GraphicsServices                    0x00000001150731dd GSEventRunModal + 62
	60  UIKitCore                           0x000000010eb2f81d UIApplicationMain + 140
	61  XyzUITests-Runner        0x000000010b4ec1f5 main + 183
	62  libdyld.dylib                       0x0000000111585575 start + 1
	63  ???                                 0x0000000000000005 0x0 + 5
)
    t =    27.50s Tear Down
Test Case '-[XyzUITests.SettingsTest testFeedbackButtonTakesUserToFeedbackPage]' failed (27.497 seconds).

</details>

Customer impact: 
This bug can cause tests to not be run and report false positives.  It's worth noting that the test that ran after this failure ran fine and passed.

**Comment by tirodkar** [comment]
This usually means that there is an app crash. You'd need to look at the logs for more info.
