### ISSUE TITLE
Does EarlGrey assertions are not returning a Boolean value?

### ISSUE THREAD

**Issue by satadip1994** [google/EarlGrey#792]
As assertions mostly return a boolean value, but it seems with earlGrey it is not the case, is there any way to do it?

**Comment by satadip1994** [comment]
Hi @tirodkar,
Actually when we are putting an if clause to a statement like:
`let s = EarlGrey.selectElement(with: grey_accessibilityID(price))
          if  s.assert(grey_notNil()) == true`

But it throws an error like "Binary operator '==' cannot be applied to operands of type 'GREYInteraction' and 'Bool'"

**Comment by BalaganesanXLR8** [comment]
Hi @tirodkar, 
Our issue is that when we identify an element with accessibilityID and if the element is having a specific value then we want to execute a part of code or else it continues the normal flow.

**Comment by tirodkar** [comment]
@BalaganesanXLR8 I spoke to @satadip1994 offline. Is this still an issue?

**Comment by satadip1994** [comment]
No this got resolved thanks @tirodkar.

**Comment by adamhowardprice** [comment]
@satadip1994 Can you describe how you wrote your code to achieve this? I have a similar question.
