### ISSUE TITLE
Does EarlGrey.selectElement has any timeout condition ?

### ISSUE THREAD

**Issue by jainhitesh3** [google/EarlGrey#795]
I am searching for a way to wait for some time before asserting for any value for my test case. 
So is there any way to do this  ?
Eg :  after calling ' EarlGrey.selectElement(with: grey_accessibilityID("Some value") ' i can wait for some time and then perform appropriate assertion ?

**Comment by tirodkar** [comment]
You can use GREYCondition in order to have an explicit wait for something EG might not be tracking by itself.

https://github.com/google/EarlGrey/blob/earlgrey2/TestLib/Condition/GREYCondition.h

**Comment by jainhitesh3** [comment]
Will there be any difference between GREYCondition (explicit wait) and sleep() ? 

If yes then can you please suggest how to define
"EarlGrey.selectElement(with: grey_accessibilityID("Some value")" 
as condition to wait for it to complete or exit after specified time ? 


What i'm trying as of now is : 

let element = EarlGrey.selectElement(with: grey_accessibilityID("Some value")
sleep(5)
element.assert(MY_ASSERTION)

**Comment by jainhitesh3** [comment]
Created method using GREYCondition, which fulfils my request. So closing this issue.

    func waitfor(time: Double) {
        let _ = GREYCondition(name: "Wait for UICollectionView to populate", block: {
            return false
        }).wait(withTimeout: time)
    }

**Comment by khandpur** [comment]
fwiw, sleep does not drain the runloop whereas greycondition does so it's still flushing out ui changes.
