### ISSUE TITLE
Does Earlgrey has contains or similar method for assertion ?

### ISSUE THREAD

**Issue by jainhitesh3** [google/EarlGrey#797]
I have a scenario where i need to check if the particular element contains a string. It can be exact match (grey_text() method) or it can be substring.

Eg : 
EarlGrey.selectElement(with: grey_accessibilityID("someID")).assert(grey_text("dummy"))

suppose for above case the selected element has text : "This is some dummy value"

above assertion will fail since it is not an exact match. But i want it to pass since it contains "dummy" text in it.

**Comment by tirodkar** [comment]
You can create this with a custom matcher, for eg. in 2.0 - 

```objc
+ (id<GREYMatcher>)matcherForContainsSubstring:(NSString *)substring {
  GREYMatchesBlock matches = ^BOOL(id element) {
    UIView *view = (UIView *)element;
    if (view.accessibilityLabel.length
        && [view.accessibilityLabel rangeOfString:substring].location != NSNotFound) {
      return YES;
    } else if ([element respondsToSelector:@selector(text)] &&
               [self grey_checkElementText:[element text] containsSubstring:substring]) {
      return YES;
    } else {
      return NO;
    }
  };
  GREYDescribeToBlock describe = ^void(id<GREYDescription> description) {
    NSString *desc = [NSString stringWithFormat:@"containsSubstring(\"%@\")", substring];
    [description appendText:desc];
  };
  return [[GREYElementMatcherBlock alloc] initWithMatchesBlock:matches
                                              descriptionBlock:describe];
}

+ (BOOL)grey_checkElementText:(NSString *)text containsSubstring:(NSString *)substring {
  return text.length && [text rangeOfString:substring].location != NSNotFound;
}
```

**Comment by jainhitesh3** [comment]
I was able to achieve my goal using this method : 
This lets me get the text from label and then i can use string contains method to test it.

Method for getting text from label
/* function body
open class Element {
    var text = ""
}

public func grey_getText(_ elementCopy: Element) -> GREYActionBlock {
    return GREYActionBlock.action(withName: "get text", constraints: grey_respondsToSelector(#selector(getter: UILabel.text))) { element, errorOrNil -> Bool in
        let elementObject = element as? NSObject
        let text = elementObject?.perform(#selector(getter: UILabel.text), with: nil)?.takeRetainedValue() as? String
        
        elementCopy.text = text ?? ""
        return true
    }
}
*/

method call

let element = Element()
  EarlGrey.selectElement(with: grey_accessibilityID(“ID”)).perform(grey_getText(element))


Hence closing this issue.
