### ISSUE TITLE
TravisTests target in earlgrey2 branch fails to compile

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#799]
![image](https://user-images.githubusercontent.com/1173057/53254875-57f04500-3692-11e9-880f-97b3318bb747.png)

- ad70b511da47793e27e77c1a69c7895e8403be45

**Comment by tirodkar** [comment]
Closing this since it's an eDO related bug / target.

**Comment by bootstraponline** [comment]
eDO is passing on Xcode 10.2 though.
https://app.bitrise.io/build/7ca0a4271fdf654e
