### ISSUE TITLE
Swizzling Method(s) not found while swizzling class CAAnimationWeakDelegateProxy.

### ISSUE THREAD

**Issue by GavinCando** [google/EarlGrey#802]
when i scroll up in a scroll view. Earlgrey displays the following errors. and app crashed. please help

Swizzling Method(s) not found while swizzling class EXCAAnimationWeakDelegateProxy.
Fatal failure: Cannot swizzle greyswizzled_animationDidStart: in /Users/gavincui/Documents/objectiveCWorkspace/ExampleWorkSpace/EarlGrey-master/EarlGrey/Delegate/GREYCAAnimationDelegate.m:182

**Comment by tirodkar** [comment]
Are you setting the delegate to something that doesn't conform to CAAnimationDelegate?

**Comment by GavinCando** [comment]
i found the reason of my issues.
Because earlgrey does not currently support nsproxy

![image](https://user-images.githubusercontent.com/1930976/54104361-8009d300-440a-11e9-8afc-41e703c9d41c.png)

**Comment by GavinCando** [comment]
> Are you setting the delegate to something that doesn't conform to CAAnimationDelegate?

thx for your help
