### ISSUE TITLE
EarlGrey is frequently crashing internally during edo_createChannelWithPort while very early in the first test

### ISSUE THREAD

**Issue by ElliottHeath** [google/EarlGrey#805]
![Screen Shot 2019-03-18 at 11 53 44 AM](https://user-images.githubusercontent.com/44884169/54556667-97027500-4976-11e9-8d21-e5b52d2862b1.png)
![Screen Shot 2019-03-18 at 11 59 45 AM](https://user-images.githubusercontent.com/44884169/54556668-97027500-4976-11e9-952a-4a2a43b1e993.png)

I believe this crash is caused from the recent update to EG, which creates the EDOHostService lazily.
Xcode reports: Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1b8e18f14) on line 155 of EDOChannelPool.m

**Comment by tirodkar** [comment]
Did your app launch?

**Comment by ElliottHeath** [comment]
Using EG to interact with the device isn't supported if the app isn't launched? (ie. interact with system to modify OS settings before the app is launched, then launching app, then running tests)

I've run the test a few times since, but haven't seen this failure again. I think you're correct that I wasn't launching.  I'll reopen/ create a new ticket if I get more data that shows this doesn't appear to be the case. I'll close this ticket out as this doesn't appear to be a real issue.
