### ISSUE TITLE
Struggling to send a Dictionary in Swift down EDO layer

### ISSUE THREAD

**Issue by charlesbensonsonos** [google/EarlGrey#807]
I should move this to the EDO project but starting here in case its an implementation detail.

Seeing an issue trying to pass a dictionary from Swift of any type: [String:String] Dictionary<String, String>, NSDictionary down the EDO layer to the host app.
If I pass an Array down of [String] this seems to be work fine.

Receiving exception:
```
19.93s Assertion Failure: EDOObject+Invocation.m:95: failed: caught "NSInternalInconsistencyException", "Not supported
```
Which seems to indicate the object cannot be translated.

Test method
```
    func testEDODict() {
        var testProtocol: DictTestProtocol {
            return unsafeBitCast(
                GREYHostApplicationDistantObject.sharedInstance,
                to: DictTestProtocol .self)
        }
        let dict:[String:String] = ["TestKey": "TestValue", "ATestKey": "ATestValue"]
        testProtocol.testEDODict(data: dict) // Exception here
    }
```

Protocol
```
@objc
protocol DictTestProtocol {
    func testEDODict(data: [String:String]) -> Void
}
```

Implementation
```
extension GREYHostApplicationDistantObject: DictTestProtocol {
    func testEDODict(data: [String:String]) -> Void {
        for key in data {
            print(key)
        }
    }
}
```

**Comment by charlesbensonsonos** [comment]
Resolution:

Add this to your swift bridging header for both the test and edo bundle:
```
#import "Service/Sources/NSObject+EDOValueObject.h"
```

Convert the dict to a NSObject type (NSDictionary) and use the NSObject extention from EDOValueObject "passByValue". 
```
data: (dict as NSDictionary).passByValue
```

Your test method should now look like this:
```
    func testEDODict() {
        var testProtocol: DictTestProtocol {
            return unsafeBitCast(
                GREYHostApplicationDistantObject.sharedInstance,
                to: DictTestProtocol .self)
        }
        let dict:[String:String] = ["TestKey": "TestValue", "ATestKey": "ATestValue"]
        testProtocol.testEDODict(data: (dict as NSDictionary).passByValue)
    }
```

The protocol should now use NSDictionary:
```
@objc
protocol DictTestProtocol {
    func testEDODict(data: [String:String]) -> Void
}
```


The implementation can then re-cast as needed:
```
extension GREYHostApplicationDistantObject: DictTestProtocol {
    func testEDODict(data: NSDictionary) -> Void {
        for (key, value) in (data as! [String:String]) {
            print(key)
        }
    }
}
```


Note: The same holds true passing back a dictionary up. It must be a NSDictionary and not a Swift Dictionary, and you must use passByValue.

For more details, this is documented for Objective-C here: https://github.com/google/eDistantObject/blob/master/docs/detail.md

**Comment by wuhao5** [comment]
out of curiosity: will this work?

```swift
let dict:[NSString:NSString] = [].
testProtocol.testEDODict(data: (dict as NSDictionary))
```
