### ISSUE TITLE
EarlGrey 2 fails on Xcode 10.2

### ISSUE THREAD

**Issue by bootstraponline** [google/EarlGrey#812]
>  error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'HostDOCategoriesSwift')
>
> https://app.bitrise.io/build/52f2bac3c8f34a40

I just updated the bitrise job to Xcode 10.2. The build is failing. I'm reverting back to 10.1.

**Comment by tirodkar** [comment]
Yeah, let's update the Swift tests to use the latest ABI. Was the code signing issue gone with Xcode 10.2 now?

**Comment by bootstraponline** [comment]
I think so, either way we need to solve Swift first.

**Comment by bootstraponline** [comment]
I think this is fixed. Bitrise is passing now.
