### ISSUE TITLE
.usingSearch doesn't seem to scroll at all

### ISSUE THREAD

**Issue by bellebethcooper** [google/EarlGrey#815]
Hello,

First off, thanks for making `EarlGrey`! I find it super useful, and use it a lot.

I'm having trouble getting `.selectElement.usingSearch` to work for my Swift iOS unit tests. As far as I can tell from watching my tests run in the simulator, and from seeing failures in my assertions after calling it, this function doesn't seem to be scrolling at all.

I've attached a simple example project I created to show the problem I'm running into. I'm using Swift 4, Xcode 10.1 and Cocoapods, and followed [these instructions](https://github.com/google/EarlGrey/issues/669#issuecomment-375409719) to get EarlGrey to compile with my example project.

The example has one view controller. Inside it is a scroll view, and a vertical stack view, which holds 9 smaller views, each with a different label inside it. I've written a single test using `EarlGrey` that uses almost the exact same code as the `testTableCellOutOfScreen` test in [this `EarlGrey` example tests file](https://github.com/google/EarlGrey/blob/91c27bb8a15e723df974f620f7f576a30a6a7484/Demo/EarlGreyExample/EarlGreyExampleSwiftTests/EarlGreyExampleSwiftTests.swift), only I'm asserting for visibility rather than tapping.

Here's the code for my failing test:

```swift
func testEarlGreyScroll_findsLastView() {
        let controller = ViewController()
        let _ = controller.view
        EarlGrey.selectElement(with: grey_accessibilityID("Test view 9"))
            .usingSearch(grey_scrollInDirection(.down, 350),
                         onElementWith: grey_accessibilityID("scroller"))
        .assert(grey_sufficientlyVisible())
    }
```

And the error I'm seeing:

```
Exception: AssertionFailedException

Exception Name: AssertionFailedException
Exception Reason: An assertion failed.
Exception with Assertion: {
  "Assertion Criteria":  "assertWithMatcher:matcherForSufficientlyVisible(>=0.750000)",
  "Element Matcher":  "(respondsToSelector(accessibilityIdentifier) && accessibilityID('Test view 9'))"
}

Exception Details: Error Trace: [
  {
    "Description":  "Assertion with matcher [M] failed: UI element [E] failed to match the following matcher(s): [S]",
    "Description Glossary":    {
      "M":  "matcherForSufficientlyVisible(>=0.750000)",
      "E":  "<UILabel:0x7fe459e19cf0; AX=Y; AX.id='Test view 9'; AX.label='Test view 9'; AX.frame={{0, 2080}, {375, 40}}; AX.activationPoint={187.5, 2100}; AX.traits='UIAccessibilityTraitStaticText'; AX.focused='N'; frame={{0, 0}, {375, 40}}; opaque; alpha=1; UIE=N; text='Test view 9'>",
      "S":  "matcherForSufficientlyVisible(>=0.750000)"
    },
    "Error Domain":  "com.google.earlgrey.ElementInteractionErrorDomain",
    "Error Code":  "3",
    "File Name":  "GREYAssertions.m",
    "Function Name":  "+[GREYAssertions grey_createAssertionWithMatcher:]_block_invoke",
    "Line":  "75",
    "TestCase Class":  "SenchaTestTests.SenchaTestTests",
    "TestCase Method":  "testEarlGreyScroll_findsLastView"
  }
]

```

The view is listed in the UI hierarchy, but it's clearly off-screen. And as I said, I'm also watching the test run on the simulator and not seeing the screen scroll at all. I've also tried using different amounts for this line: `.usingSearch(grey_scrollInDirection(.down, 350)` with no luck.

It's entirely possible I'm doing something wrong, but I can't figure out what, so any advice would be appreciated! Thanks again for making `EarlGrey`, as even without this feature I'm finding it really useful.

[SenchaTest.zip](https://github.com/google/EarlGrey/files/3032329/SenchaTest.zip)

**Comment by khandpur** [comment]
add sufficiently visible to grey_accessibilityID("Test view 9") so it essentially reads:

an element with accessibility ID Test View 9 that's also visible.

**Comment by bellebethcooper** [comment]
@khandpur When I do that, I get the same test failure error and I still don't see the simulator scrolling at all. Just to confirm, this is what I changed the test to:

```swift
    func testEarlGreyScroll_findsLastView() {
        let controller = ViewController()
        let _ = controller.view
        EarlGrey.selectElement(with: grey_accessibilityID("Test view 9"))
            .assert(grey_sufficientlyVisible())
            .usingSearch(grey_scrollInDirection(.down, 350),
                         onElementWith: grey_accessibilityID("scroller"))
    }
```

And I also tried this, in case I misunderstood what you meant:

```swift
    func testEarlGreyScroll_findsLastView() {
        let controller = ViewController()
        let _ = controller.view
        EarlGrey.selectElement(with: grey_accessibilityID("Test view 9"))
            .assert(grey_sufficientlyVisible())
            .usingSearch(grey_scrollInDirection(.down, 350),
                         onElementWith: grey_accessibilityID("scroller"))
          .assert(grey_sufficientlyVisible())
    }
```

**Comment by khandpur** [comment]
What you just isn't semantically different than what you had previously. You can combine matchers together using grey_allOf. Try with this selection matcher:
grey_allOf(grey_accessibilityID("Test view 9"), grey_sufficientlyVisible()).

**Comment by bellebethcooper** [comment]
@khandpur Sorry about that. I usually use `EarlGrey` with a wrapper, so I'd forgotten how to combine matchers. When I changed the test to the following, it passed:

```swift
EarlGrey.selectElement(with: grey_allOf([grey_accessibilityID("Test view 9"), grey_sufficientlyVisible()]))
            .usingSearch(grey_scrollInDirection(.down, 350),
                         onElementWith: grey_accessibilityID("scroller"))
```

Thank you! My only confusion now is that when I watch the test run in the simulator I don't see it scroll at all. When I use `swipeFastInDirection` I can see the simulator swipe/scroll. Are you able to explain what's happening when I use `.usingSeach` and why I can't see it scroll in the simulator?

Thanks for your help!

**Comment by khandpur** [comment]
It could be that the element on which scroll action is being applied to i.e. grey_accessibilityID("scroller"), is not sufficiently visible. The scroll logic tries to find a large-enough area on which it can apply the scroll. To find that area it uses the visibility checker's rectEnclosingVisibleAreaOfElement

**Comment by bellebethcooper** [comment]
Hmm okay. The "scroller" is a `UIScrollView` that takes up the whole screen, so I'm not sure that's it. But anyway, the problem is solved, so thanks for your help.
