### ISSUE TITLE
selectElement usingSearch passes when it shouldn't

### ISSUE THREAD

**Issue by bellebethcooper** [google/EarlGrey#819]
When using `selectElement` with `.usingSearch` in Swift, all of my tests are passing, even when the matchers I've passed to `selectElement` are totally bogus and should fail. I've attached an example project replicating the issue below. Here are two tests from my example project, which has just one view controller with 9 coloured views in a `UIScrollView`:

```swift
func testEarlGreyScroll_findsLastView() {
    let controller = ViewController()
    let _ = controller.view
    EarlGrey.selectElement(with: grey_allOf([grey_accessibilityID("Test view 9"), grey_sufficientlyVisible()]))
        .usingSearch(grey_scrollInDirection(.down, 350),
                     onElementWith: grey_accessibilityID("scroller"))
}
    
func testEarlGreyScroll_failsWhenLookingForAViewThatDoesntExist() {
    let controller = ViewController()
    let _ = controller.view
    EarlGrey.selectElement(with: grey_allOf([grey_accessibilityID("Test view 10"), grey_sufficientlyVisible()]))
        .usingSearch(grey_scrollInDirection(.down, 350),
                     onElementWith: grey_accessibilityID("scroller"))
}
```

There is no view with the accessibility ID of "Test view 10", but there is one with the ID of "Test view 9", yet both these tests pass. I can change the accessibility ID matcher in the second test to look for anything, like "blahblahblah" and it still passes. I can also use `grey_text` instead of an accessibility ID, give it a random string to look for that doesn't exist anywhere, and the test will still pass.

I'm sure I'm doing something wrong, but I can't figure out what. TIA for any pointers!

Edited to add: this will pass no matter what string I use:

`EarlGrey.selectElement(with: grey_text("nonsense"))`

but if I do this, the test will fail, as it should, saying there's no matching element:

`EarlGrey.selectElement(with: grey_text("nonsense")).assert(grey_sufficientlyVisible())`

[EarlGreyTest.zip](https://github.com/google/EarlGrey/files/3078852/EarlGreyTest.zip)

**Comment by khandpur** [comment]
EarGrey's selectElement API if not followed by an assert or performAction call is essentially a no-op.

This doc describes the API behavior in detail: https://github.com/google/EarlGrey/blob/master/docs/api.md

**Comment by bellebethcooper** [comment]
I thought `grey_sufficientlyVisible` was an assert. Am I wrong, or does it not work that way when used as part of the selection? 

Thanks for your help!

**Comment by khandpur** [comment]
`grey_sufficientlyVisible` is a matcher that can be used as an assertion when passed to the assertion api. 
` EarlGrey.selectElement(with: grey_allOf([grey_accessibilityID("Test view 10"), grey_sufficientlyVisible()]))` uses it as a selection mather, not an assert.

**Comment by bellebethcooper** [comment]
Aha, that's the part I wasn't understanding, even after re-reading the docs. Thanks for your help.
