### ISSUE TITLE
Assertion failure in -[GREYElementProvider dataEnumerator]

### ISSUE THREAD

**Issue by fernyb** [google/EarlGrey#86]
I keep getting this issue where I navigate to another view controller then then nothing works,
I do have a custom matcher and I can see that it does match the element I'm looking but I cannot do anything with it. As this is the error I'm getting. 

For some reason it's only on a specific view controller where it doesn't work but everything else works fine.

*** Assertion failure in -[GREYElementProvider dataEnumerator], /Users/tirodkar/egg/google3/third_party/objective_c/EarlGrey/EarlGrey/Provider/GREYElementProvider.m:152

	0   CoreFoundation                      0x000000010cba8e65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010c61edeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010cba8cca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010c0344de -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   EarlGrey                            0x0000000121017437 __37-[GREYElementProvider dataEnumerator]_block_invoke + 2711
	5   EarlGrey                            0x0000000121015708 -[GREYDataEnumerator nextObject] + 72
	6   CoreFoundation                      0x000000010cabd2f5 -[NSEnumerator countByEnumeratingWithState:objects:count:] + 53
	7   EarlGrey                            0x0000000120ff1e79 -[GREYElementFinder elementsMatchedInProvider:] + 1817
	8   EarlGrey                            0x0000000120ff280d -[GREYElementInteraction matchedElementsWithTimeout:error:] + 1117
	9   EarlGrey                            0x0000000120ff42e6 __46-[GREYElementInteraction performAction:error:]_block_invoke + 502
	10  EarlGrey                            0x00000001210248bd __59-[GREYUIThreadExecutor executeSyncWithTimeout:block:error:]_block_invoke + 429
	11  CoreFoundation                      0x000000010cad4a1c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	12  CoreFoundation                      0x000000010caca6a5 __CFRunLoopDoBlocks + 341
	13  CoreFoundation                      0x000000010cac9e02 __CFRunLoopRun + 850
	14  CoreFoundation                      0x000000010cac9828 CFRunLoopRunSpecific + 488
	15  EarlGrey                            0x000000012102338c -[GREYUIThreadExecutor executeSyncWithTimeout:block:error:] + 1932
	16  EarlGrey                            0x0000000120ff3981 -[GREYElementInteraction performAction:error:] + 2049
	17  EarlGrey                            0x0000000120ff310c -[GREYElementInteraction performAction:] + 76
	18  mip_write_review_test               0x0000000120f87380 -[MIPWriteReviewTest test14TapReviewFromProfileScreen] + 240
	19  CoreFoundation                      0x000000010ca971cc __invoking___ + 140

**Comment by khandpur** [comment]
Look at the code it's a sanity check for a valid (non-nil) accessibility element:
`NSAssert(element, @"element should not be nil");`

According to accessibilityElementAtIndex's documentation, it is OK to return nil so we should be accepting of nil elements and not fail.

**Comment by tirodkar** [comment]
@fernyb, is there anything special about the View Controller that this seems to be failing on. While it is ok to have accessibilityElementAtIndex return nil, we only iterate over the number of elements in provided to us in the accessibility element count. Are you finding that a nil value is being iterated over or do you think the index might be incorrect?

**Comment by tirodkar** [comment]
@fernyb, we're planning to send a fix for this. Are you using CocoaPods or another integration method? In case you're using CocoaPods, the fix will be picked up in the next release.

**Comment by fernyb** [comment]
I don't believe there is anything special about the view controller, I just happen to be getting nil here:

https://github.com/google/EarlGrey/blob/master/EarlGrey/Provider/GREYElementProvider.m#L152

I'm using CocoaPods, I'm thinking of trying to use master if the fix is in.

**Comment by fernyb** [comment]
I can confirm if I remove NSAssert my tests work as expected.

**Comment by tirodkar** [comment]
Fernando, feel free to remove the assert and put a nil check for `element` around `[runningElementHierarchy addObject:element];` and submit a Pull Request for it. You can also do something similar in [GREYElementHierarchy](https://github.com/google/EarlGrey/blob/master/EarlGrey/Common/GREYElementHierarchy.m#L137).

**Comment by tirodkar** [comment]
Closing thanks to https://github.com/google/EarlGrey/pull/91 and https://github.com/google/EarlGrey/pull/90.
