### ISSUE TITLE
EarlGrey breaks Xcode UI Tests

### ISSUE THREAD

**Issue by davidshayer** [google/EarlGrey#876]
Xcode had two types of test targets, unit tests and UI tests. Xcode unit tests with EarlGrey run fine. I also want to use Xcode UI tests, but EarlGrey seems to break this. 
When I run an Xcode UI test, I get this runtime error:
`dyld: could not load inserted library '@executable_path/EarlGrey.framework/EarlGrey' because image not found`
I followed all the instructions in the EarlGrey install docs, trying to get `EarlGrey.framework` installed in my UI test target, but it always fails on launch. 
Is this a known issue? How do you work around it?
I'm using Xcode 10.2.1.

**Comment by Liuruyong** [comment]
UITests Scheme > Edit Scheme... > Test > Environment Variables 

Delete  "DYLD_INSERT_LIBRARIES  @executable_path/EarlGrey.framework/EarlGrey"

**Comment by johnhiggs** [comment]
I'm getting this same error in consent when trying to run detox tests on react native project

**Comment by Liuruyong** [comment]
https://github.com/google/EarlGrey/issues/785

**Comment by tirodkar** [comment]
This is known. We developed EarlGrey 2.0 specifically for XCUITest support. Please move your tests to use the earlgrey2 branch.
