### ISSUE TITLE
Fix Rubocop Warnings for configure_earlgrey_pods.rb script and the Podfile.

### ISSUE THREAD

**Issue by tirodkar** [google/EarlGrey#89]
https://codeclimate.com/github/google/EarlGrey/issues?category=&engine=rubocop&page=1

**Comment by bootstraponline** [comment]
This will be fixed when configure_earlgrey_pods is deleted in favor of the gem. The gem already fixes all the rubocop warnings.

In terms of the Podfile, I don't think we should fix `Freeze mutable objects` since no one writes code like that when using cocoapods.

```
SCHEME_FILE = 'EarlGreyExampleTests.xcscheme'.freeze
```

vs

```
SCHEME_FILE = 'EarlGreyExampleTests.xcscheme'
```

**Comment by tirodkar** [comment]
@bootstraponline, thanks for your input. We'll close this our as soon as we have an update on the gem.
